### ISSUE TITLE
doxygen comments using trailing "

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#1003]
https://github.com/swig/swig/issues/2070 creates trouble when running `swig` with `-doxygen`. In any case, comments like
```
        /// Dot between "this" and "other"
```
(in `PETAcquisitionDataInMemory` and elsewhere?) would be formatted nicer with
```
        /// Dot between \c this and \a other
```

By the way, it'd make more sense to put these comments in `DataContainer` as then all derived classes will have this doc.

**Comment by evgueni-ovtchinnikov** [comment]
closed by 9dc7f0fabd48f53fbd11a6646bc3bbbe5c3b65d8
