### ISSUE TITLE
CIL-wrapper test TestGradientMR_2D failures

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#1019]
SIRF-SuperBuild actions with `DEVEL_BUILD=ON` are occasionally failing. e.g. https://github.com/SyneRBI/SIRF-SuperBuild/runs/4007079890?check_suite_focus=true#step:7:827

```
======================================================================
FAIL: test_Gradient (test_SIRF.TestGradientMR_2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/CIL/Wrappers/Python/test/test_SIRF.py", line 99, in test_Gradient
    self.assertTrue(LinearOperator.dot_test(Grad_c, decimal=3))
```

@paskino  Possibly a tolerance issue? (I think we have our own adjoint tests)

**Comment by paskino** [comment]
@epapoutsellis introduced those tests in the latest CIL, which is now able to run `GradientOperator` on SIRF data containers. Maybe we can relax the tolerance?

**Comment by KrisThielemans** [comment]
not sure how your tolerance works. obviously needs to be relative.

**Comment by KrisThielemans** [comment]
@epapoutsellis @paskino can you please resolve this? Various CI tests and docker builds are failing now.

**Comment by KrisThielemans** [comment]
i should have said "can you resolve and/or shed some light on this". Obviously, if a test fails it could be that there is an underlying problem in the gradient or its adjoint.

**Comment by paskino** [comment]
We are working at it.

**Comment by KrisThielemans** [comment]
@paskino fixed by https://github.com/TomographicImaging/CIL/pull/1048?

**Comment by KrisThielemans** [comment]
@paskino we believe this can be closed, or does it need a change in the SuperBuild?

**Comment by paskino** [comment]
Oh yes, it's fixed.
