### ISSUE TITLE
SIRF build error on Ubuntu 20.04

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#1020]
Building SIRF on VM with Ubuntu 20.04 via SIRF-SuperBuild fails with
```
CMake Error at cmake_install.cmake:54 (file): file cannot create directory: /sirf.  Maybe need administrative privileges.
```
The file `cmake_install.cmake` in question is (had to append with `.txt` as GitHub does not work with `.cmake` files):
[cmake_install.cmake.txt](https://github.com/SyneRBI/SIRF/files/7467903/cmake_install.cmake.txt)

All SIRF dependencies seem to build ok.

**Comment by KrisThielemans** [comment]
Did you set `-DCMAKE_INSTALL_PREFIX=blabla`? I guess it defaults to `/usr/local`

**Comment by evgueni-ovtchinnikov** [comment]
`CMAKE_INSTALL_PREFIX` is set to `/home/sirfuser/devel/build/INSTALL`, see
[CMakeCache.txt](https://github.com/SyneRBI/SIRF/files/7468549/CMakeCache.txt)
(and also e.g. line 66  in `cmake_install.cmake.txt`) - I always check variables via `ccmake` before the build.

**Comment by KrisThielemans** [comment]
ok. can you just `make` again (not parallel) and post log here?

**Comment by evgueni-ovtchinnikov** [comment]
[make_log.txt](https://github.com/SyneRBI/SIRF/files/7468813/make_log.txt)

**Comment by KrisThielemans** [comment]
ok. L54 in `cmake_install.cmake` wants to install `config.py`. This is done here
https://github.com/SyneRBI/SIRF/blob/8d269178a6e20086f5d379998d3c9e7c68adca41/CMakeLists.txt#L195
This says that `PYTHON_DEST` is empty, and that is indeed the case in your cache.

next question is how this happened. Maybe you can give exact steps related to running CMake?

**Comment by evgueni-ovtchinnikov** [comment]
To the best of my recollection, I just followed your instructions of yesterday to the letter.

Should I delete `devel` and repeat, logging my steps?

**Comment by KrisThielemans** [comment]
I guess so. sorry. Or if you did everything from command line, you get them via `history`

**Comment by evgueni-ovtchinnikov** [comment]
it appears history logs commands from any terminal (and I used several), so is not very helpful

I will repeat then, doing everything from one terminal now

**Comment by evgueni-ovtchinnikov** [comment]
These are steps before running `make` in  `~/devel/build`:
[build_log_before_make.txt](https://github.com/SyneRBI/SIRF/files/7469539/build_log_before_make.txt)

**Comment by evgueni-ovtchinnikov** [comment]
Sorry, this time forgot about `CXX` and `CC` (because did not need to install `g++` and `gcc`).
```
sirfuser@vagrant:~/devel/build$ which g++-8
/usr/bin/g++-8
sirfuser@vagrant:~/devel/build$ which gcc-8
/usr/bin/gcc-8
sirfuser@vagrant:~/devel/build$ export CXX=g++-8 CC=gcc-8
sirfuser@vagrant:~/devel/build$ make >make_log.txt 2>&1
```

**Comment by evgueni-ovtchinnikov** [comment]
now it breaks at ISMRMRD...
[make_log_new.txt](https://github.com/SyneRBI/SIRF/files/7469774/make_log_new.txt)

**Comment by KrisThielemans** [comment]
I notice a few things:
- `VirtualBox/scripts/*.sh` permissions were wrong (not executable). I've fixed that
-  Python install
```
    Found existing installation: PyQt5 5.14.1
ERROR: Cannot uninstall PyQt5 5.14.1, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps PyQt5==5.14.1'.
```
interesting of course. "I find it, but I cannot reinstall it.". Presumably this is an install via `apt` which conflicts with one with `pip`. We might have to work around this in the install script, but this is unrelated to your problems, so we can leave that for later.

> now it breaks at ISMRMRD...

removing `CMakeCache.txt` is sadly not enough for the SuperBuild. It will have created lots of caches in `builds/*/build`, which will use the wrong compiler etc and settings. I'm afraid you'll have to delete the whole `~/devel/build` directory again. Sorry.

Still, I'm not sure if it's going to help, as clearly you specified `CMAKE_INSTALL_PREFIX` in your first attempt, and it wasn't picked up. So I'm a bit mystified. Anyway, restart again...

**Comment by evgueni-ovtchinnikov** [comment]
deleted `devel`, rebuilt - same again...
[build_log.txt](https://github.com/SyneRBI/SIRF/files/7477133/build_log.txt)
[make_log.txt](https://github.com/SyneRBI/SIRF/files/7477136/make_log.txt)
[cmake_install.cmake.txt](https://github.com/SyneRBI/SIRF/files/7477137/cmake_install.cmake.txt)

**Comment by KrisThielemans** [comment]
ok. Seems we have various problems with setting `PYTHON_DEST_DIR`. I'll attempt a PR

**Comment by KrisThielemans** [comment]
When building CIL, another problem will be https://github.com/SyneRBI/SIRF-SuperBuild/issues/624
