### ISSUE TITLE
Units in STIR

### ISSUE THREAD

**Issue by skarrea** [SyneRBI/SIRF#1022]
Is there a reason for the inconsistent usage of units in the documentation of functions in [STIR.py](https://github.com/SyneRBI/SIRF/blob/master/src/xSTIR/pSTIR/STIR.py). Two examples of where I'd want units in the documentation are in the `EllipticCylinder` class methods and in the `SeparableGaussianImageFilter.set_fwhms`. From the STIR user guide, it seems the units are mm in both of these cases.

I'd also like `SeparableGaussianImageFilter.set_max_kernel_sizes` to specify that `mks` is max dimensions of the kernel in voxels.  

In my opinion, this would also partly solve #826 if the [user guide](https://github.com/SyneRBI/SIRF/blob/master/doc/UserGuide.md) is updated accordingly.

**Comment by KrisThielemans** [comment]
> Is there a reason for the inconsistent usage of units in the documentation of functions in STIR.py. 

can you give an example of inconsistent usage please? I guess we all know about "incomplete documentation", but not about "inconsistent documentation".

The User guide [states that all distances are in mm](https://github.com/SyneRBI/SIRF/blob/master/doc/UserGuide.md#Units_and_index_ordering). We could add explicit statements about mm in the shape and filter classes if you feel that's helpful (a PR would be welcome, in which case ideally you also modify the matlab doc or even C++ doxygen, sorry about that). It is definitely a good idea to state explicitly that the kernel sizes are in voxel units.
you suggestions for adding explicit mm to the shape classes sounds good to me (although

**Comment by skarrea** [comment]
Inconsistent as in units are used explicitly in some parts of the documentation, but not in others. The units are, for example, given explicitly in describing spacing and offset in `ImageData.initialize`. 

I'd be happy to make a PR adding units (mm) to shape classes and to the `SeparableGaussianImageFilter` methods in the matlab documentation, python documentation and the [user guide](https://github.com/SyneRBI/SIRF/blob/master/doc/UserGuide.md). Unfortunately I'm not to familiar with C++ Doxygen documentation...

**Comment by skarrea** [comment]
closed by #1024.
