### ISSUE TITLE
Remove installation step for boost random from workflow once PR #936 is merged

### ISSUE THREAD

**Issue by johannesmayer** [SyneRBI/SIRF#1030]
For PR #936 to ensure the creation of Shepp Logan Exe by the SuperBuild there is a workaround in the PR manually installing boost random during the workflow.

Once the issue https://github.com/SyneRBI/SIRF-SuperBuild/issues/636 gets sorted and the superbuild automatically does this , this manual installation needs to be removed again.

**Comment by paskino** [comment]
See https://github.com/SyneRBI/SIRF-SuperBuild/pull/637
