### ISSUE TITLE
version_major() and version_minor() do not work in MATLAB

### ISSUE THREAD

**Issue by luciferlys** [SyneRBI/SIRF#1047]
I called ```sirf.Utilities.examples_data_path()``` in MATLAB and got error messages like:
```hash
Unable to resolve the name sirf.Utilities.version_major.
```
Then I checked ```install/matlab/+sirf/+Utilities/examples_data_path.m``` in my SIRF VM, I found [https://github.com/SyneRBI/SIRF/blob/e844ae8b18b4b0ad377c4da11af1ea17afc8d360/src/common/%2Bsirf/%2BUtilities/examples_data_path.m.in#L28-L31](url)
```MATLAB
if ~isempty(SIRF_DATA_PATH)
    p = [ SIRF_DATA_PATH filesep 'examples' filesep petmr];
elseif ~isempty(SIRF_INSTALL_PATH)
    p = [ SIRF_INSTALL_PATH filesep 'share' filesep ['SIRF-' version_major() '.' version_minor() ] filesep 'data' filesep 'examples' filesep petmr ];
```
```examples_data_path()``` can work correctly when ```SIRF_DATA_PATH``` is set. However, I didn't set ```SIRF_DATA_PATH``` at the first time so error occurred when calling ```version_major()``` and ```version_minor()```. I also tried to call ```version_major()``` and ```version_minor()``` directly in MATLAB, got the same error message:
```bash
Unable to resolve the name sirf.Utilities.version_major.
Unable to resolve the name sirf.Utilities.version_minor.
```
The installed version in my VM is ```version_major.m.in``` and ```version_minor.m.in```, but not ```version_major.m``` and ```version_minor.m```.

I think this could be a bug, please check it.

**Comment by KrisThielemans** [comment]
The `version*.m.in` files should not be located in `+sirf/Utilities` as otherwise they will be copied into the install directory. Instead, they should be configured of course.

Also, the help text is inaccurate
https://github.com/SyneRBI/SIRF/blob/e844ae8b18b4b0ad377c4da11af1ea17afc8d360/src/common/%2Bsirf/%2BUtilities/version_major.m.in#L23
