### ISSUE TITLE
Write ImageData to file when the string name contains a dot "."

### ISSUE THREAD

**Issue by ClaireDelplancke** [SyneRBI/SIRF#1066]
For an object `image` of ImageData type, the command `image.write("test_1.0")` creates three files:
 
test_1.ahv 
test_1.hv 
test_1.0.hv

so that for the two first files, every character after the point gets deleted.

**Comment by ClaireDelplancke** [comment]
Hi again, any idea on that? Would be very helpful in order to keep in the same folder reconstructions with different values of the regularisation parameter.

**Comment by evgueni-ovtchinnikov** [comment]
@ClaireDelplancke I am afraid this is not a SIRF issue: the actual writing is performed by STIR `write_to_file` functions, so you need to seek help from UCL/STIR developers - or just avoid using dots in filenames

**Comment by ClaireDelplancke** [comment]
Ok, thanks @evgueni-ovtchinnikov. I close the issue then.

**Comment by ClaireDelplancke** [comment]
The solution is to include the extension in the name,  `image.write("test_1.0.hv")`. See https://github.com/UCL/STIR/issues/1013.
