### ISSUE TITLE
Silencing WARNING (setting SIRF ImageData modality)

### ISSUE THREAD

**Issue by Imraj-Singh** [SyneRBI/SIRF#1078]
I am creating an image data object and filling it like so:

```
im = pet.ImageData()
im.initialise(arr.shape, tuple(res))
im.fill(arr)
```
Where arr is the numpy array of data and res is the physical resolution. The data template is taken simply from the SIRF examples. When running my algorithm I get the following warning, which I would like silence:

**WARNING: forward_project. Imaging modality unknown for either the image or the projection data or both.**

I have tried `sirf.STIR.set_verbosity(False)` but to no avail. Perhaps there is a way of assigning my own modality to the ImageData object.

Thanks,
Imraj

**Comment by evgueni-ovtchinnikov** [comment]
@Imraj-Singh To silence messages from STIR redirect them to files:
```
msg_red = MessageRedirector('info.txt', 'warn.txt', 'errr.txt')
```

**Comment by KrisThielemans** [comment]
can also redirect to `/dev/null` which presumably would be faster.

However, we do need to fix the underlying issue of (being able to) set the modality, which was easy before as it was always PET, but no longer...

**Comment by KrisThielemans** [comment]
that's correct. however, that's a fairly serious break with backwards compatibility I guess. First release 3.1 or even 3.2 and then do that?

**Comment by KrisThielemans** [comment]
@Imraj-Singh you should be able to set the modality to "PT" (or "NM") now to avoid this warning. @samdporter, this might be of interest for you as well.
