### ISSUE TITLE
Prior get_value() SIRF exposure

### ISSUE THREAD

**Issue by samdporter** [SyneRBI/SIRF#1085]
https://github.com/SyneRBI/SIRF/blob/b8a7d15f72e5ad70d4ee68252e88d83480469231/src/xSTIR/pSTIR/STIR.py#L1891

Please expose the value of the prior function in SIRF
i.e `def get_value(): ...` or `def __call__() ...`

**Comment by KrisThielemans** [comment]
@paskino @samdporter please confirm CIL convention.

**Comment by samdporter** [comment]
`__call__() `

**Comment by samdporter** [comment]
Please can we also change`get_gradient()` to `gradient() ` for CIL compatibility?

**Comment by KrisThielemans** [comment]
`ObjectiveFunction` has `get_value()`, `value()` and `__call__`, and `gradient()` with one `get_gradient()` aliases. We should do that the same for `Prior`
