### ISSUE TITLE
Exposing more STIR priors in SIRF

### ISSUE THREAD

**Issue by Imraj-Singh** [SyneRBI/SIRF#1087]
Hi,

At present, it seems as though only Parallel Level Sets and Quadratic Prior are exposed in SIRF. It would be interesting to have Relative Difference Prior too.

We did have a go at simply extending the quadratic prior wrapper just changing names of: https://github.com/SyneRBI/SIRF/blob/448f4d23c5125d11940e76f12c04696befaa2fe9/src/xSTIR/pSTIR/STIR.py#L2034 but it seems that simply wrapping the class and changing names was not enough. Perhaps due to the RDP [C++ class not being exposed in STIR](https://github.com/SyneRBI/SIRF/blob/448f4d23c5125d11940e76f12c04696befaa2fe9/src/xSTIR/cSTIR/cstir.cpp#L144)?

Kind regards,
Imraj

**Comment by KrisThielemans** [comment]
I got confused by your statement "C++ class not being exposed in STIR". Of course it exists and is "exposed" in C++ STIR 😄 . I guess you mean sirf.STIR.

You need to add the class to sirf.STIR C++, C wrappers and Python. I'm sure @evgueni-ovtchinnikov can help but it'd be best if you start. Create a draft PR with what you have already. Might be a good idea to read the https://github.com/SyneRBI/SIRF/blob/master/doc/DeveloperGuide.md
