### ISSUE TITLE
generating MR test-data fails on GHA for the superbuild

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#1094]
GHA on SIRF-SuperBuild are failing with `DEVEL_BUILD=ON` when generating the MR test-data, see e.g. https://github.com/SyneRBI/SIRF-SuperBuild/pull/695. Error is
```
/home/runner/install/bin/ismrmrd_generate_cartesian_shepp_logan: error while loading shared libraries: libismrmrd.so.1.7: cannot open shared object file: No such file or directory
```
This is likely a bug introduced in #1076, related to finding the ISMRMRD libraries. 

For recent CMake, the [code](https://github.com/SyneRBI/SIRF/blob/96be7726d90cec2020a0801c970d9b7860767d87/src/xGadgetron/cGadgetron/tests/CMakeLists.txt#L77) does not actually add the location of the ISMRMRD library to `LD_LIBRARY_PATH`.

For older CMake, we seem to gamble on `${CMAKE_INSTALL_PREFIX}/lib`
https://github.com/SyneRBI/SIRF/blob/96be7726d90cec2020a0801c970d9b7860767d87/src/xGadgetron/cGadgetron/tests/CMakeLists.txt#L80
This is what we did before #1076 (and therefore in 3.2.0, and hence non-devel builds).

Confusingly, the SIRF-SuperBuild [seems to be (still) running CMake 3.17.5](https://github.com/SyneRBI/SIRF-SuperBuild/runs/6182534932?check_suite_focus=true#step:3:148), so should be executing the "old CMake" version. So I'm not sure what's going on.

**Comment by paskino** [comment]
> you could decide to put some diagnostics on SIRF/master yet (e.g. printing LIBRTPATH, which could help diagnose that problem...)

https://github.com/SyneRBI/SIRF-SuperBuild/pull/695#pullrequestreview-954115201
