### ISSUE TITLE
sinogram .hs template file needs changing

### ISSUE THREAD

**Issue by samdporter** [SyneRBI/SIRF#1102]
https://github.com/SyneRBI/SIRF/blob/dbdc03c1b3e75b1a380bb0be62851189174e7ce7/examples/Python/SPECT/acquisition_model.py#L105

Altering the template_sinogram.hs file to have the right number of slices & z-spacing will remove the need for this (confusing) line. I'll do it, but submitting an issue to make sure that I don't forget.

**Comment by KrisThielemans** [comment]
fixed in #1104
