### ISSUE TITLE
Document AcquisitionModel::norm and ensure no constant term present

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#1106]

**Comment by evgueni-ovtchinnikov** [comment]
It actually does 2 iterations for by default, applying the operator 3 times (2 iterations of CG turned out to deliver the same accuracy as previously used 3 iterations of the power method - but do let me know if you need higher accuracy). 

The eigensolver source is in `src/common/include/sirf/common/JacobiCG.h`, and the methods `PETAcquisitionModel::norm` and `MRAcquisitionModel::norm` are in `src/xSTIR/cSTIR/include/sirf/STIR/stir_x.h` and `src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h` respectively.

**Comment by ClaireDelplancke** [comment]
I'd like to have much more iterations, typically 100, in order to have more confidence in the result!

**Comment by ClaireDelplancke** [comment]
Thanks Evgueni. I've installed SIRF with the SyperBuild - is there a way to incorporate this change in my current installation?

**Comment by evgueni-ovtchinnikov** [comment]
@ClaireDelplancke I believe you can just pull SIRF master and build SIRF
