### ISSUE TITLE
generation of MR phantom can use wrong executable

### ISSUE THREAD

**Issue by samdporter** [SyneRBI/SIRF#1113]
https://github.com/SyneRBI/SIRF/blob/6fc60a4b81e67f38f8a4343563cc509b0b8ec19e/src/xGadgetron/cGadgetron/tests/CMakeLists.txt#L42-L44
means we are looking for an installed version of the executable, as opposed to the one we just compiled. This means that in some situations, it won't be found, in other situations it will find an old one.

**Comment by KrisThielemans** [comment]
This was incorrect. SIRF doesn't build `ismrmrd_generate_cartesian_shepp_logan`, as it is from ISMRMRD.

The problem we were facing is because we manually removed HDF5 libraries and rebuild SIRF but forgot to rebuild ISMRMRD.
