### ISSUE TITLE
Typo error 

### ISSUE THREAD

**Issue by epapoutsellis** [SyneRBI/SIRF#1115]
There is a typo error in the `MessageRedirector` class. [`errr` should be `err`](https://github.com/SyneRBI/SIRF/blob/c3866f01b2a431234135b17ea84050940e38b656/src/Registration/pReg/Reg.py#L50).

**Comment by epapoutsellis** [comment]
thank you @evgueni-ovtchinnikov .

**Comment by paskino** [comment]
Using 3 `r` in the creator is very error prone, IMO.
