### ISSUE TITLE
Improving HKEM coding from SIRF

### ISSUE THREAD

**Issue by danieldeidda** [SyneRBI/SIRF#1117]
https://github.com/UCL/STIR/blob/b1227dda0537530040cde4c48d79fbb661233495/src/iterative/KOSMAPOSL/KOSMAPOSLReconstruction.cxx#L760-L764

If this function was exposed to SIRF it would make the use of  kernels more flexible and possibly use them for different algorithms then OSEM. The user would still need to set a KOSMAPOSL object for the parameters and the prior images. 
The function would calculate `kernelised_image_out = K * image_to_kernelise`  where K is the kernel
@samdporter

**Comment by evgueni-ovtchinnikov** [comment]
@danieldeidda how/where are you going to use this function and what should I use for `current_alpha_estimate`?

**Comment by danieldeidda** [comment]
This could be used in the HKEM exercise  ( https://github.com/danieldeidda/SIRF-Exercises/blob/master/notebooks/Synergistic/HKEM_reconstruction.ipynb ): we set the parameters (ex recon.set_sigma_m() etc) and then we can call compute_kernelised_image(). Current_alpha_estimate in this case could be uqual to image_to_kernelise as an example, but the user could use any image they want as side information.

**Comment by evgueni-ovtchinnikov** [comment]
@danieldeidda SIRF cannot call `compute_kernelised_image` because it is private - can you make it public?

**Comment by danieldeidda** [comment]
Ah right let me have a look!

**Comment by danieldeidda** [comment]
the function is now public

**Comment by evgueni-ovtchinnikov** [comment]
@danieldeidda thanks!

**Comment by KrisThielemans** [comment]
only on STIR master of course. but you can check on STIR 5.1

**Comment by evgueni-ovtchinnikov** [comment]
@danieldeidda has this issue been fixed by PR #1121?

**Comment by danieldeidda** [comment]
yes and #1165
