### ISSUE TITLE
Cannot set compiler flag -std=gnu++14 for g++-8 on VM

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#1129]
Trying to build SIRF on one of my VMs, I get lots of build errors like
```
‘enable_if_t’ in namespace ‘std’ does not name a template type
```
which, according to StackOverflow, can be cured by the compiler flag `-std=c++14` or `-std=gnu++14`.

I did try to add `-std=gnu++14` to `CMAKE_CXX_FLAGS` in `ccmake`, but it did not work: the actual compilation line showed by `make VERBOSE=1` turned out to be
```
cd /home/sirfuser/devel/build/builds/SIRF/build/src/xGadgetron/cGadgetron && /usr/bin/g++-8 -DBOOST_ALL_NO_LIB -DGADGETRON_TOOLBOXES_AVAILABLE -D_WIN32_WINNT=0x0501 -I/home/sirfuser/devel/build/sources/SIRF/src/xGadgetron/cGadgetron -I/home/sirfuser/devel/build/sources/SIRF/src/xGadgetron/cGadgetron/include -I/home/sirfuser/devel/build/sources/SIRF/src/iUtilities -I/home/sirfuser/devel/build/sources/SIRF/src/iUtilities/include -I/home/sirfuser/devel/build/sources/SIRF/src/common -I/home/sirfuser/devel/build/sources/SIRF/src/common/include -I/home/sirfuser/devel/build/sources/SIRF/src/Synergistic/cSyn -I/home/sirfuser/devel/build/sources/SIRF/src/Synergistic/cSyn/include -I/home/sirfuser/devel/build/sources/SIRF/src/xSTIR/cSTIR/include -I/home/sirfuser/devel/build/sources/SIRF/src/xSTIR/cSTIR -I/home/sirfuser/devel/build/sources/SIRF/src/Registration/cReg/include -I/home/sirfuser/devel/build/sources/SIRF/src/Registration/NiftyMoMo/include -isystem /home/sirfuser/devel/build/INSTALL/include -isystem /usr/include/hdf5/serial -isystem /home/sirfuser/devel/build/INSTALL/include/ITK-4.13 -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -std=gnu++14 -O3 -DNDEBUG -std=gnu++14 -fPIC -fopenmp -std=gnu++11 -MD -MT src/xGadgetron/cGadgetron/CMakeFiles/cgadgetron.dir/cgadgetron.cpp.o -MF CMakeFiles/cgadgetron.dir/cgadgetron.cpp.o.d -o CMakeFiles/cgadgetron.dir/cgadgetron.cpp.o -c /home/sirfuser/devel/build/sources/SIRF/src/xGadgetron/cGadgetron/cgadgetron.cpp
```
resulting expectedly in the same error
```
In file included from /home/sirfuser/devel/build/INSTALL/include/gadgetron/hoNDArray.h:7,
                 from /home/sirfuser/devel/build/sources/SIRF/src/xGadgetron/cGadgetron/include/sirf/Gadgetron/NonCartesianEncoding.h:68,
                 from /home/sirfuser/devel/build/sources/SIRF/src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h:53,
                 from /home/sirfuser/devel/build/sources/SIRF/src/xGadgetron/cGadgetron/cgadgetron.cpp:38:
/home/sirfuser/devel/build/INSTALL/include/gadgetron/NDArray.h:60:14: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
```
Any idea why/how/when `-std=gnu++11` got added to `CMAKE_CXX_FLAGS` and how to get rid of it?

**Comment by KrisThielemans** [comment]
I guess there's 2 issues here:
# why do we get the compilation errors now and not before?

Obviously, Gadgetron has moved on from C++11 quite a while ago, but as far as I know, the version we pinned should still compile with G++-8. So, are you trying a more recent Gadgetron?

# how to change from c++-11 to c++-14?
we set C++ version here
https://github.com/SyneRBI/SIRF/blob/a057ccae4d478dc70f7e5ae595095b5b0c8230b1/CMakeLists.txt#L38-L39
Although stackoverflow posts often recommends setting the compiler flag, far better is to tell CMake what to do. I believe that setting the CMake variable `CMAKE_CXX_STANDARD` to `14` would do the trick. (As far as I remember, the `UseCXX` macro uses the most recent version between the value of the variable and the value of its argument).

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans
On issue 1: the VM in question was created last year, it runs under Ubuntu 20.04 and has Gadgetron master built on it. I just wanted to see whether our issue #1128 is still present when one uses Gadgetron master - then I could try to create a Gadgetron issue for it. So I updated SIRF and tried to build it, and ran into reported issues.

On issue 2: `UseCXX(14)` does not help, I still get `-std=gnu++11` in the compilation command for `cgadgetron.cpp`. Where should I set `CMAKE_CXX_STANDARD` to `14` - in `SIRF-SuperBuild`?

Meanwhile, I am trying to run just the compilation command edited manually. I already have found that `gnu++14` is not enough (I got `'is_trivial_v' is not a member of 'std'`), StackOverflow suggests `c++17`. I tried both `c++17` and `gnu++17` and got `cannot deduce template arguments for ‘multiplies’ from ()`. Will try now to rebuild `range-v3`, as the solution of similar Gadgetron issue #887 suggests (I did previously rebuild it with `c++14`, so I do not have much hope actually).

**Comment by KrisThielemans** [comment]
issue 1: ok great. Gadgetron `master` indeed requires C++ 17. https://github.com/gadgetron/gadgetron/blob/a5c27ebbaef693a6cc254d69b85c973cc37d31a0/CMakeLists.txt#L134

issue 2: you can set it via `SIRF_EXTRA_FLAGS` or whatever it's called, or while testing just 
```
cd builds/SIRF/build
cmake -DCMAKE_CXX_STANDARD=17 .
```
However, due to caching, I'm not 100% sure it will override it.

I note that since https://github.com/gadgetron/gadgetron/pull/805 (March 2020), Gadgetron exports a CMake config file. We should therefore use that in the future as opposed to our own ["find a library" etc](https://github.com/SyneRBI/SIRF/blob/a057ccae4d478dc70f7e5ae595095b5b0c8230b1/src/xGadgetron/cGadgetron/CMakeLists.txt#L45). We can then test the [Gadgetron version](https://github.com/gadgetron/gadgetron/blob/a5c27ebbaef693a6cc254d69b85c973cc37d31a0/CMakeLists.txt#L53) to see what C++ version we need, if necessary (although in principle CMake should then sort that out automatically).

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans found where `gnu++11` comes from: in `xGadgetron/CMakeLists.txt` we have:
```
if (CMAKE_VERSION VERSION_LESS "3.1")
   set (CMAKE_CXX_FLAGS "--std=c++11 ${CMAKE_CXX_FLAGS}")
else ()
   set (CMAKE_CXX_STANDARD 11)
endif ()
```
I suggest we set `CMAKE_CXX_STANDARD` to 11 only if it is not defined:
```
if (CMAKE_VERSION VERSION_LESS "3.1")
   set (CMAKE_CXX_FLAGS "--std=c++11 ${CMAKE_CXX_FLAGS}")
else ()
   if (NOT DEFINED CMAKE_CXX_STANDARD)
      set (CMAKE_CXX_STANDARD 11)
   endif ()
endif ()
```
Do I do a PR for this or just edit?

**Comment by KrisThielemans** [comment]
It's confusing/dangerous to set this stuff in 2 places. I think we should delete those lines there, and handle it all in the main `CMakeLists.txt`, so move the following up
https://github.com/SyneRBI/SIRF/blob/a057ccae4d478dc70f7e5ae595095b5b0c8230b1/src/CMakeLists.txt#L28
and do something like
```cmake
set (default_CXX_version 11)
if (NOT DISABLE_Gadgetron)
  find_package(gadgetron someversion)
  if (gadgetron_FOUND)
     set(default_CXX_version 17)
  else()
    message(WARNING "Gadgetron not found, so toolboxes will not be used. Set gadgetron_DIR if you do have it.")
  endif()
endif()
UseCXX(default_CXX_version)
```
Clearly, that needs a new PR, but I agree you should first see if it works by local editing 😄 .

Note that our macro [UseCXX](https://github.com/SyneRBI/SIRF/blob/a057ccae4d478dc70f7e5ae595095b5b0c8230b1/cmake/SetC%2B%2BVersion.cmake) avoids setting it the user overrides.
