### ISSUE TITLE
Synthetic TOF data

### ISSUE THREAD

**Issue by Enza-994** [SyneRBI/SIRF#1145]
Hello,
I'm writing to ask you how it is possible to generate synthetic TOF data, precisely which is the parameter that has to be set to change the number of tof bins. I'm suing last version of SIRF (3.4.0) from the master branch.

I've tried with: 
template_acq_data = pet.AcquisitionData('Siemens_mMR', span=1, max_ring_diff=15, view_mash_factor=1,tof_mash_factor=1), but I'm obtaining always a tof dimension=1, with template_acq_data.shape equal to (1, 357, 252, 344). 
And is there a folder with some tof pet data for testing sirf?
Thank you.

**Comment by KrisThielemans** [comment]
Currently there is no example file. Sorry. If you run `recon_test_pack/run_test_listmode.sh` you'll get some. Most important fields are
```
number of dimensions := 5
matrix axis label [5] := timing positions
!matrix size [5] := 5
matrix axis label [4] := segment
!matrix size [4] := 7
matrix axis label [3] := view
!matrix size [3] := 252
matrix axis label [2] := axial coordinate
!matrix size [2] := { 1,2,3,4,3,2,1}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 344
%TOF mashing factor := 82
; normal ones
Number of TOF time bins :=410
Size of timing bin (ps) :=10
Timing resolution (ps) :=400
```
Note that for the above to work, you'd need to use a scanner with TOF info (the mMR is a non-TOF scanner), such as the Signa.

Finally, you will need to use STIR TOF branch. Hopefully that'll become STIR master in a few weeks.
