### ISSUE TITLE
SIRF Reading & Writing and gadgetron_ismrmrd_client collide

### ISSUE THREAD

**Issue by johannesmayer** [SyneRBI/SIRF#1156]
I encountered a problem executing the following steps:
- reading an ISMRMRD raw file (from patient data) with SIRF and then writing it back to file.
- calling the `gadgetron_ismrmrd_client`  on that file to reconstruct
- (I only checked the output for a DICOM writer in the XML configuration file for the gadget chain)

all reconstructions yield zeros.

I have found the solution:
https://github.com/SyneRBI/SIRF/blob/93f280fbfc95f914642d1a532a65882d83938eb5/src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_data_containers.h#L62

to `false`  for all acquisitions will solve this problem.

**Comment by evgueni-ovtchinnikov** [comment]
> `false` for all acquisitions will solve this problem

@johannesmayer ... and will create problems elsewhere (`as_array`, `fill`, `norm`, `dot`, ...)

Better try your steps with these lines in `MRAcquisitionData::read` commented out:
```
			if( TO_BE_IGNORED(acq) )
				continue;
			else
```

**Comment by johannesmayer** [comment]
I checked again and I ran the following reconstruction (using the "old" Gadgetron commit that's used in the current Superbuild) 

```
preprocessed_data = preprocess_acquisition_data(acq_data)

    # Perform reconstruction of the preprocessed data.
    # 1. set the reconstruction to be for Cartesian GRAPPA data.
    recon_gadgets = ['AcquisitionAccumulateTriggerGadget',
            'BucketToBufferGadget', 
            'GenericReconCartesianReferencePrepGadget', 
            'GRAPPA:GenericReconCartesianGrappaGadget', 
            'GenericReconFieldOfViewAdjustmentGadget', 
            'GenericReconImageArrayScalingGadget', 
            'ImageArraySplitGadget',
            'PhysioInterpolationGadget(phases=30, mode=0, first_beat_on_trigger=true, interp_method=BSpline)']

    recon = Reconstructor(recon_gadgets)
    recon.set_gadget_property('GRAPPA', 'send_out_gfactor', True)

    # 2. set the reconstruction input to be the data we just preprocessed.
    recon.set_input(preprocessed_data)

    # 3. run (i.e. 'process') the reconstruction.
    print('---\n reconstructing...\n')
    recon.process()

    # retrieve reconstruced image and G-factor data
    image_data = recon.get_output('Image PhysioInterp')

    image_data = image_data.abs()
    image_data.write("output.dcm")
```

Left: reconstruction including the `TO_BE_IGNORED`, right without it. So it seems not to be just about the client.

![tmprecon_sirf_with_ignore](https://user-images.githubusercontent.com/10499392/206521539-083398b1-dbda-4b25-b59d-965c72ea49c4.gif) ![tmprecon_sirf_without_ignore](https://user-images.githubusercontent.com/10499392/206521506-389b6b39-9bac-4657-90e6-50027ded7dfd.gif)

**Comment by evgueni-ovtchinnikov** [comment]
@johannesmayer so I understand removing those 3 lines fixed the issue? If so, could you please create a PR, and if GHA builds succeed merge it - or I could do it if you are busy.

**Comment by evgueni-ovtchinnikov** [comment]
see PR #1161
