### ISSUE TITLE
NiftyImageData.allocate('random') should check type

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#1184]
we should check the data_type in the following https://github.com/SyneRBI/SIRF/blob/0fa2e54993a97c4a68d6a590519395b87d8cdfe8/src/Registration/pReg/Reg.py#L362-L366
In particular if the images are complex, then we should generate a random complex vector

**Comment by evgueni-ovtchinnikov** [comment]
outdated, closing
