### ISSUE TITLE
IterativeReconstructor needs get_objective_function method

### ISSUE THREAD

**Issue by samdporter** [SyneRBI/SIRF#1188]
`IterativeReconstructor` class needs `get_objective_function` STIR method exposed

1. It would be nice to have
2. Causes `get_subset_sensitivity` method to fail

This is currently commented out in [STIR.py](https://github.com/SyneRBI/SIRF/blob/78926376b98f73a7e4c7f05bae39e5cd7086ef8e/src/xSTIR/pSTIR/STIR.py#L2861). Looks like this has been attempted, but hasn't worked. Might be an idea to comment out the `get_subset_sensitivity` method for now

**Comment by evgueni-ovtchinnikov** [comment]
fixed by https://github.com/SyneRBI/SIRF/commit/a32bf4b21c1ebef55d907e26ed9338b29076dd2f
