### ISSUE TITLE
ImageData.allocate() does not support kw None for Gadgetron.and Reg 

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#1212]
CIL's [doc for allocate](https://github.com/TomographicImaging/CIL/blob/fb95d17772aea6d6e1f9b0e3f5642afafebc0d1e/Wrappers/Python/cil/framework/framework.py#L2623C9-L2623C81) says
```
type value: number or string, default None allocates empty memory block
```
I don't know what "empty" means, but I guess it is "uninitialised"? @gfardell @paskino ?

`None` is supported for STIR, but not for the [Gadgetron](https://github.com/SyneRBI/SIRF/blob/d3956345ec6e56421017a6aca34c73747dbae664/src/xGadgetron/pGadgetron/Gadgetron.py#L526-L527) nor [Reg](https://github.com/SyneRBI/SIRF/blob/d3956345ec6e56421017a6aca34c73747dbae664/src/Registration/pReg/Reg.py#L319)

I suppose we could just `clone()`? .

- [ ] fix this issue
- [ ] revert 160d5e5 from #838

**Comment by KrisThielemans** [comment]
By the way, this code looks a bit wasteful
https://github.com/SyneRBI/SIRF/blob/d3956345ec6e56421017a6aca34c73747dbae664/src/xGadgetron/pGadgetron/Gadgetron.py#L526-L527
as `out.fill(value)` should work as well and is clearer. On the other hand, that will do the virtually same at the moment (!)
https://github.com/SyneRBI/SIRF/blob/d3956345ec6e56421017a6aca34c73747dbae664/src/xGadgetron/pGadgetron/Gadgetron.py#L407

**Comment by KrisThielemans** [comment]
for reference, the STIR/STIR implementation is [here](https://github.com/SyneRBI/SIRF/blob/d3956345ec6e56421017a6aca34c73747dbae664/src/xSTIR/pSTIR/STIR.py#L652C19-L655C18)

**Comment by paskino** [comment]
> I don't know what "empty" means, but I guess it is "uninitialised"? @gfardell @paskino ?

It should read allocated but not initialised, i.e. we do not care about the values in it.

Therefore, `clone` is a good suggestion.
