### ISSUE TITLE
NiftyResampler norm crashes on MR data with multiple repetitions

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#1225]
With https://github.com/SyneRBI/SIRF/pull/1186  `norm` on the `NiftyResampler` was introduced. While running the [MCIR reconstruction](https://github.com/paskino/SIRF-Contribs/blob/MR_MCIR_2023/src/notebooks/simulating_motion_2.ipynb) I call it and python crashes.

A minimal example to reproduce it is

```python

import sirf.Reg as pReg
import sirf.Gadgetron as pMR
import numpy as np
import os

from cil.utilities.display import show2D

from sirf.Utilities import  examples_data_path
acq_data = pMR.AcquisitionData(os.path.join
            (examples_data_path('MR'),'simulated_MR_2D_cartesian.h5')
        )
# ad1.sort()
preprocessed_data = pMR.preprocess_acquisition_data(acq_data)
recon = pMR.FullySampledReconstructor()
recon.set_input(preprocessed_data)
recon.process()
im_ms = recon.get_output()

max_shift = 20.


t_x=max_shift
t_y=0
tm = pReg.AffineTransformation(np.array(\
        [[1, 0, 0, t_x], \
            [0, 1, 0, t_y], \
            [0, 0, 1, 0  ], \
            [0, 0, 0, 1  ]]))


im_ms1 = im_ms * 1.1

# Create resampler
mf_resampler = pReg.NiftyResample()
# mf_resampler[ind] = NiftyResampleWithNormCache()
mf_resampler.set_reference_image(im_ms)
mf_resampler.set_floating_image(im_ms1)
mf_resampler.add_transformation(tm)
mf_resampler.set_padding_value(0)
mf_resampler.set_interpolation_type_to_linear()

mf_resampler.norm()
```

I am running this on SIRF from the https://github.com/SyneRBI/SIRF/tree/ignore-acq branch

**Comment by evgueni-ovtchinnikov** [comment]
@paskino `im_ms` needs to be `NiftiImageData`, so after `im_ms = recon.get_output()` add
```
im_ms = pReg.NiftiImageData(im_ms)
```

**Comment by evgueni-ovtchinnikov** [comment]
Just what I was afraid of - repetition is not the only extra dimension:

> MR data have many different dimensions, obviously 3 spatial ones, but the additional ones (at least defined in ISMRMRD) are:
>
>contrast
phase
repetition
set

and I have just remembered David mentioning 11 dimensions.

Makes the situation still more complicated...

**Comment by DANAJK** [comment]
I would argue that trying to squash everything into 3 dimensions is more complicated, and more confusing, than using multiple array dimensions. I made comments about this in [Feb 2022.](https://github.com/SyneRBI/SIRF/issues/1044#issuecomment-1029854823)
