### ISSUE TITLE
time frame handling in listmode reconstruction

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#1249]
- We do not have a `set_time_interval` yet for the list-mode objective function. It looks like this can be done in STIR by taking the objective function and setting its (public) `frame_defs` member. See also https://github.com/UCL/STIR/issues/1417
- Our demo sets a time interval for the creation of the scatter etc [here](https://github.com/SyneRBI/SIRF/blob/2c66faff3bc0f12c864cfc2a2931eba5ade60ba0/examples/Python/PET/listmode_reconstruction.py#L145), but as listmode reconstruction will be using all events, there is going to be a mismatch, so this is a bug.

@evgueni-ovtchinnikov easy to add a `set_time_interval` method to the listmode objective function?

**Comment by evgueni-ovtchinnikov** [comment]
I understand it is not in STIR yet? Once you make it available in STIR, should not be difficult to access it from SIRF.

**Comment by KrisThielemans** [comment]
It doesn't need STIR modifications luckily.

Essentially a copy of `ListmodeToSinograms::set_time_interval`, i.e. adding `set_time_interval` to `xSTIR_PoissonLLhLinModMeanListDataProjMatBin3DF` (as [here](e.g. https://github.com/SyneRBI/SIRF/blob/2c66faff3bc0f12c864cfc2a2931eba5ade60ba0/src/xSTIR/cSTIR/include/sirf/STIR/stir_x.h#L141-L148 )) and exposing it in exactly the same way

**Comment by evgueni-ovtchinnikov** [comment]
fixed by #1253
