### ISSUE TITLE
randoms support for GE Signa

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#137]

**Comment by KrisThielemans** [comment]
Relevant STIR code is in https://github.com/UCL/STIR/blob/72ba889720a83314a8f1e258cf65d4bab9483be6/src/utilities/construct_randoms_from_GEsingles.cxx

We will need to make the loop there a function in STIR, such that we can call it from SIRF. It would be nice to do that in the `release_4` branch of STIR, such that it will be included in STIR 4.1 (hopefully released soon)

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans: I understand `unsigned int SinglesFromGEHDF5::read_singles_from_file(const std::string& rdf_filename)` reads singles from a file in RDF format containing  `ListModeData` - where can I find such a file? Also, will `stir::read_from_file<ListModeData>` be able to read from it?

**Comment by KrisThielemans** [comment]
The function actually works with both "sinogram" and "listmode" data in RDF9.  The VQC data should have 
- list data in `spatial-calibration-VQC\VQC_Phantom_Dataset_Share\LST\LST_30501_PET_Scan_for_VQC_Verification`. Note that I believe that the Zenodo version is compressed, but we have the uncompressed file (but this wouldn't matter for the randoms stuff).
- sinogram data in `spatial-calibration-VQC\VQC_Phantom_Dataset_Share\PTRAW\30001_PET_Scan_for_VQC_Verification` (you'll get the RDF after `nm_extract`). This is also compressed so not usable for actual reconstruction, but should be ok for the randoms/singles. We do have the uncompressed data as well at UCL (not sure if you have that link already).


Note that the randoms in this scan are very low (point sources) so not a great test of it all, but at least you can see if it doesn't fall over... We should soon get more GE PET/MR data from Newcastle, and RDF9 PET/CT from GE.
