### ISSUE TITLE
install demos and documentation

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#181]
we need to copy the examples into `${CMAKE_INSTALL_PREFIX}/share/SIRF/examples` and `${CMAKE_INSTALL_PREFIX}/share/SIRF/doc`

should use version number

create a script to "git clone SIRF-data".

Migrated from https://github.com/CCPPETMR/SIRF-SuperBuild/issues/102

**Comment by paskino** [comment]
I'm thinking to create an `install` target in CMake to handle this. Any obvious objection?

I think it'd also be fine as we discussed that we needed a `make install`.

**Comment by KrisThielemans** [comment]
https://cmake.org/cmake/help/v3.8/command/install.html#installing-files

will automatically create the `install` target for you. no need to add it by hand

**Comment by paskino** [comment]
Yes, I meant that one.

**Comment by rijobro** [comment]
let's not install `data` yet and postpone that for later.

**Comment by KrisThielemans** [comment]
@paskino let's leave this for after rc1
