### ISSUE TITLE
"out" as an optional argument

### ISSUE THREAD

**Issue by mehrhardt** [SyneRBI/SIRF#194]
As requested by @KrisThielemans in CCPPETMR/Hackathon-SIRF#1. Functionals and operators and SIRF should have the optional argument "out" to avoid using additional memory.

This is standard for Numpy, e.g. https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.matmul.html#numpy.matmul and ODL, e.g. https://github.com/odlgroup/odl/blob/master/odl/trafos/fourier.py line 146 (note that for the latter everything is a little more complicated) or https://odlgroup.github.io/odl/generated/odl.tomo.backends.astra_cpu.astra_cpu_forward_projector.html?highlight=out.

The idea is that an operator A can be called in two different ways.

```1) y = A(x)```

```2) A(x, out=y)```

While option 1) looks simpler, option 2) allows to evaluate A without creating new memory for y as it assumes this already exists.

What A does with out (checking of sizes etc) is optional, however, it is important that is overwrites the memory and does not reallocate new memory to out (which would break this syntax!).

**Comment by evgueni-ovtchinnikov** [comment]
we try to make our matlab scripts look as close to python's as possible, and matlab does not directly support keywords (workarounds are rather ugly)
i would rather follow c style -  output arg comes first (cf. e.g. memcpy) - and have 2) simply as A(y, x)

**Comment by mehrhardt** [comment]
Another possibility would be to just not support this option in MATLAB.

**Comment by KrisThielemans** [comment]
This is a difficult decision of course. The reason for having the `out` syntax in Python is compatibility with numpy and ODL, as @mehrhardt mentioned. So, there's no reason to use complicated work-arounds for Matlab. However, @evgueni-ovtchinnikov has a good point.

Any reason we cannot support both `y=A(x)` and `A(y,x)` in C++, Matlab and Python, and also add `A(x,out=y)` in Python? (It will mean more complicated Python argument processing of course. [This might help](https://stackoverflow.com/questions/1419046/python-normal-arguments-vs-keyword-arguments)).

**Comment by evgueni-ovtchinnikov** [comment]
stir can overwrite both images and acquisition data, no problem to have both ways there

on mr side, i did not yet manage to figure out how to overwrite acquisitions stored in hdf5 file, so i create a new file and delete the old instead, so no real difference between `y=A(x)` and `A(x, y)` - having said that, with file storage scheme there can hardly be any performance gains in using `A(x, y)` anyway

in summary, both ways are possible, we just need to decide on syntax

i would vote for `A(y, x)` as the simplest way to keep matlab scripts looking almost the same as python's

_but_

i would also remind you that in user guide we promise to use the following scheme instead of `y = A(x)`:
    
    A.set_input(x)
    A.process()
    y = A.get_output()

if we are to keep this promise, then instead of `A(x, y)` we should have

    A.set_input(x)
    A.set_output(y)
    A.process()

finally, our acquisition sensitivity model has `normalise` and `unnormalise` methods essentially of `A(x, y)` syntax but with `y = x` and their `y = A(x)` equivalents `invert` and `forward`

**Comment by paskino** [comment]
It seems to me we are becoming a bit stiff. If one thing can't be done in one language that's not a good reason why it should not be done in the other that supports it. 
If people using Python or Matlab would find "standard" syntax they'll adopt SIRF easier maybe?

@mehrhardt has a very good point which affects performance significantly. So clearly I'd propend for C style in C/C++ `A(y,x)` and language dependent for the wrappers. 
The 2 languages do diverge so wildly that at some point we need to get different strategies.

**Comment by paskino** [comment]
@evgueni-ovtchinnikov are you saying that you never have the MR data in memory? Or when Gadgetron has it you don't have access to it?

**Comment by evgueni-ovtchinnikov** [comment]
i wrote about the file storage scheme (the default one, as i run out of memory on VM for real problems) - no problem with memory storage scheme, which the user can opt for

**Comment by KrisThielemans** [comment]
@johannesmayer do you know how to overwrite acquisition data in an existing ISMRMRD file?

@evgueni-ovtchinnikov , get point about `set_output`! This is ITK-like. I think we can make it optional? If people didn't call `set_output`, everything is as-is. If they did, `get_output` would just return what they've set it to. Would that work?

Can you be a bit more explicit abou tthe `AcquisitionSensitivityModel`? My memory fails me...

**Comment by evgueni-ovtchinnikov** [comment]
`AcquisitionSensitivityModel.normalise(x)` normalizes x, `AcquisitionSensitivityModel.invert(x)` returns new normalised data obtained from `x` without changing `x`, same situation with the other two methods i mentioned

**Comment by evgueni-ovtchinnikov** [comment]
`set_ouput(y)` is equivalent to `A(x, out=y)` and `A(y, x)' - can be done except for mr acquisition data in hdf5 file, where it might cause confusion (if the user knows that `y` is in say `y.h5` they will be expecting this file to contain the computed `y` - instead, `y` will be put in a new temporary file, which will be deleted after the script terminates)

**Comment by paskino** [comment]
For reference, in CIL we implemented the `out` parameter as of https://github.com/vais-ral/CCPi-Framework/pull/136

**Comment by ashgillman** [comment]
Small, premature comment on Python implementation:

instead of `def method(x, *args, **kwargs)`, `def method(x_or_y, x=None, out=None)` would be better, avoiding `*args` and `**kwargs` where possible avoids ambiguity and helps out IDEs with autocomplete.

Then

```
def method(x_or_out, x=None, out=None):
    """Blah"""
    if x is not None and out is not None:
        # can't have both
        warn('usage method(y, x) or method(x, out=y)')

    if x is None:    # method(x) or method(x, out=y)
        x = x_or_out
    else:            # method(y, x)
        out = x_or_out

    return c_method(x, y)
```

But that could go into a little helper function.

**Comment by evgueni-ovtchinnikov** [comment]
If I am not mistaken, we now have `out` in all types used by CIL except reconstructors, for which we have to stick to the usage scheme promised in our User's Guide (`set_input` and `get_output`), so I am closing the issue.
