### ISSUE TITLE
integrate SPDHG into SIRF

### ISSUE THREAD

**Issue by mehrhardt** [SyneRBI/SIRF#218]
As discussed, SPDHG will be integrated into CIL vais-ral/CCPi-Framework#154 which can then be used for SIRF. An example of SPDHG to be used with and without subsets and with and without regularization https://github.com/CCPPETMR/Hackathon-SIRF/blob/convert_spdhg_to_cil/examples/Python/PET/interactive/spdhg_reconstruction.py has been completed with 5efd25a49b41e7212a4e3f01bedb7cebc6c018e6. After CIL vais-ral/CCPi-Framework#154 is in, it could be included on the master branch of SIRF.

**Comment by KrisThielemans** [comment]
This is done in CIL
