### ISSUE TITLE
CMake 3.13 and SWIG Policy CMP0078 is not set

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#242]
as in https://github.com/UCL/STIR/issues/298

**Comment by KrisThielemans** [comment]
Also need to replace `SWIG_ADD_MODULE` with `SWIG_ADD_LIBRARY`

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov @paskino this might be a 10 min exercise. It results in much less warnings during the build. Worth a look. If it turns complicated, then postpone.

**Comment by paskino** [comment]
`SWIG_ADD_LIBRARY` was introduced as of [CMake 3.9](https://cmake.org/cmake/help/v3.9/release/3.8.html?highlight=swig_add_module), which is our minimum required version. This change can be safely introduced in our `CMakeLists.txt`. 

The CMake Policy CMP0078 requires checking of CMake version as it was [introduced](https://cmake.org/cmake/help/v3.14/policy/CMP0078.html#policy:CMP0078) in version 3.13.

**Comment by KrisThielemans** [comment]
that commit is probably too simple. In STIR I have
```cmake
if (CMAKE_VERSION VERSION_LESS "3.8")
    SWIG_ADD_MODULE(stir python stir.i ${STIR_REGISTRIES})
  else()
    SWIG_ADD_LIBRARY(stir LANGUAGE python TYPE MODULE SOURCES stir.i ${STIR_REGISTRIES})
  endif()
```

**Comment by paskino** [comment]
That's because in STIR the minimum required version of CMake is [2.8.3](https://github.com/UCL/STIR/blob/master/CMakeLists.txt#L31) and not  [3.9](https://github.com/CCPPETMR/SIRF/blob/master/CMakeLists.txt#L36) as in SIRF.

**Comment by KrisThielemans** [comment]
I  meant the `LANGUAGE` etc stuff that I needed to add. sorry

**Comment by paskino** [comment]
I see. According to the docs `TYPE MODULE` is default so no need to specify, but I'd specify the rest. 

Good you spotted it.
