### ISSUE TITLE
Implement DataContainer methods in C++

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#283]
As documented in the [UserGuide](https://github.com/CCPPETMR/SIRF/blob/add_to_sirf_classes/doc/UserGuide.md#datacontainer) and being implemented in *Python only* in this [PR]
(https://github.com/CCPPETMR/SIRF/pull/237#issuecomment-449058718)

This issue is to see whether we can implement this in C++.

`sirf.DataContainer` has the method `copy` as an alias to `clone`. 
A number of methods are currently implemented on CCPi and not on SIRF `DataContainers`:
1. (Pixelwise) binary operations:
    1. `add(self, other , out=None, *args, **kwargs)`
    1. `subtract(self, other, out=None , *args, **kwargs):`
    1. `multiply(self, other , out=None, *args, **kwargs)` present with different signature `multiply(self, other)`
    1. `divide(self, other , out=None ,*args, **kwargs)` present with different signature `divide(self, other)`
    1. `power(self, other , out=None ,*args, **kwargs)`
    1. `maximum(self, other , out=None ,*args, **kwargs)`
1. all inline algebra is missing, achievable by using the above methods.
1. (Pixelwise) unary operations:
    1. `abs(self, out=None, *args,  **kwargs)`
    1. `sign(self, out=None, *args,  **kwargs)`
    1. `sqrt(self, out=None, *args,  **kwargs)`
1. reductions
    1. `sum(out=None, *args,  **kwargs)`

**Comment by KrisThielemans** [comment]
@paskino, please assign to appropriate milestone

**Comment by KrisThielemans** [comment]
Is this done? If not, it would be best to convert the above into a checklist such that we can see what's done already.

**Comment by evgueni-ovtchinnikov** [comment]
1. (Pixelwise) binary operations: 
- [x] `add(self, other, out=None)`
- [x] `subtract(self, other, out=None)`
- [x] `multiply(self, other, out=None)`
- [x] `divide(self, other, out=None)`
- [ ] `power(self, other, out=None)`
- [ ] `maximum(self, other, out=None)`
2. (Pixelwise) unary operations: 
- [ ] `abs(self, out=None)`
- [ ] `sign(self, out=None)`
- [ ] `sqrt(self, out=None)`
3 Reductions:
- [ ] `sum(self)`
4. Inline algebra
- [x] achievable by using the above methods with `out=self`.
