### ISSUE TITLE
cGadgetron locks access to HDF5 data

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#290]
We cannot run multiple recons on the same data at the same time. (This can easily happen when using the SIRF-Exercises, when you try multiple notebooks). We get an error that HDF5 has locked the file
```
unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
```
I guess this is because we open read/write. Can we open read-only? That should resolve this (see e.g. https://github.com/h5py/h5py/issues/1066#issuecomment-402618924).

Caveat: I'll confess I haven't really checked if this is due to the acquisition data. I'm hoping we're never writing to the same image in these demos?

**Comment by evgueni-ovtchinnikov** [comment]
ismrmrd's dataset class constructor does not provide an option to open file as read-only

we could inherit our own dataset type from ismrmrd's and add a constructor with read-only flag - good move do you think?

**Comment by DANAJK** [comment]
You might need to be a bit careful regarding default output filenames and default group names within these files. It's possible to append dataset groups (named with date and time) over multiple runs to a single hdf5 output file.

**Comment by KrisThielemans** [comment]
After fixing, will have to update the doc for the SIRF-Exercises

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov please create an issue on ISMRMRD (or even PR).

**Comment by KrisThielemans** [comment]
check if we are still compatible with ISMRMRD master

**Comment by evgueni-ovtchinnikov** [comment]
I believe a much simpler solution is to set storage scheme to `memory` and clone the acquisition data read from file.
