### ISSUE TITLE
PDHG algorithm for PET recon with SIRF

### ISSUE THREAD

**Issue by epapoutsellis** [SyneRBI/SIRF#455]
[Demo](https://github.com/CCPPETMR/SIRF-Contribs/blob/H4_OS_FISTA/src/Python/sirf/contrib/reconstruction/PDHG_CIL_vs_SIRF.py) that compares the PET reconstruction with PDHG from CIL using data fidelity:
1. `KullbackLeibler` from CIL
 1. `pet.PoissonLogLikelihoodWithLinearModelForMeanAndProjData` 

Hacks to make PDHG from CIL to work with SIRF

1.  We need to compute the [`norm`](https://github.com/CCPPETMR/SIRF-Contribs/blob/H4_OS_FISTA/src/Python/sirf/contrib/reconstruction/utils_SIRF_CIL_reconstruction.py#L19) of the `AcquisitionModel`. Currently it uses the [`PowerMethod`](https://github.com/vais-ral/CCPi-Framework/blob/composite_operator_datacontainer/Wrappers/Python/ccpi/optimisation/operators/LinearOperator.py#L27) from the `LinearOperator` class from CIL, however we suggest to add the `PowerMethod` in the `AcquisitionModel` class.

2. For the `PoissonLogLikelihoodWithLinearModelForMeanAndProjData`, we need

      1. `convex_conjugate` method to compute the convex conjugate of 
           `PoissonLogLikelihoodWithLinearModelForMeanAndProjData`. In CIL, we are using [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.xlogy.html)
           which is the convex conjugate of [`scipy.special.kl_div`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.kl_div.html)

      1. compute the `proximal` of the [`convex conjugate`](https://github.com/CCPPETMR/SIRF-Contribs/blob/H4_OS_FISTA/src/Python/sirf/contrib/reconstruction/utils_SIRF_CIL_reconstruction.py#L61)

     1. the `__call__` method for [`PoissonLogLikelihoodWithLinearModelForMeanAndProjData`](
https://github.com/CCPPETMR/SIRF-Contribs/blob/H4_OS_FISTA/src/Python/sirf/contrib/reconstruction/utils_SIRF_CIL_reconstruction.py#L23). Currently, we have this [method](https://github.com/CCPPETMR/SIRF-Contribs/blob/H4_OS_FISTA/src/Python/sirf/contrib/reconstruction/utils_SIRF_CIL_reconstruction.py#L23). In the [ STIR KullbackLeibler ](http://stir.sourceforge.net/documentation/doxy/html/classstir_1_1PoissonLogLikelihoodWithLinearModelForMean.html) I believe that [get_value](https://github.com/CCPPETMR/SIRF/blob/master/src/xSTIR/pSTIR/STIR.py#L1292)
computes 

```
\sum \overline{y_b} - y_{b}\log\overline{y_b}     ( 1 )
```

and not
```
KL = sum \overline{y_b} - y_{b} log \overline{y_b}  - y_{b} + y_{b} log y_{b}  ( 2 )
```
3)   From `PoissonLogLikelihoodWithLinearModelForMeanAndProjData` we would like

`get_background_term`
`get_acquisition_data`

so we can avoid writing these [2 lines](
https://github.com/CCPPETMR/SIRF-Contribs/blob/H4_OS_FISTA/src/Python/sirf/contrib/reconstruction/PDHG_CIL_vs_SIRF.py#L133)

**Comment by KrisThielemans** [comment]
A few comments:

- adding `PowerMethod` in the `AcquisitionModel` class seems weird (a generic method inside an acquisition model?) I guess that's not what you meant.

- `convex_conjugate` and its proximal I don't know really what it'd involve. Maybe someone can elaborate on what is actually needed? Probably best in separate issue?

- adding `__call__` seems trivial to do in the `add_cil` branch.

- point 3. please create a separate issue for this such that we can comment on where the appropriate place would be.

**Comment by paskino** [comment]
@KrisThielemans we have the Power Method as static method of the LinearOperator class, for this reason we thought to add it to the AcquisitionModel. However, we can put it in [`SIRF.py`](https://github.com/CCPPETMR/SIRF/blob/master/src/common/SIRF.py) as function, maybe?

**Comment by KrisThielemans** [comment]
done in CIL, with some remaining issues listed separately already. #804
