### ISSUE TITLE
Matlab bad class check

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#466]
Accidentally called an `ImageDataProcessor` with a 3-D array as opposed to a `sirf.STIR.ImageData`.

However, the error check in the underlying code is:
```
assert(strcmp(input.class_name(), 'ImageData'))
```

A 3-D array doesn't have any dot indexing, (i.e., `3D_arr.class_name` is impossible), leading to an unrelated error:
```
Dot indexing is not supported for variables of this type.
```
I think something like:
```
assert(strcmp(class(gpu_mlem_obj), class(sirf.STIR.ImageData)))
```
would be better. 

Thoughts?

P.S. I haven't fixed this particular bug, because it could be in other places. Probably needs a search and replace.

**Comment by evgueni-ovtchinnikov** [comment]
sorry cannot do matlab at the moment, licence expired in september, stfc still negotiating a new campus-wide one with mathworks
