### ISSUE TITLE
Expose AXPBY to MATLAB/Python

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#475]
In CIL we are adding a small C library to speed up some calculations. 

The first method I[ expose](https://github.com/vais-ral/CCPi-Framework/blob/7718ebe1cbc6b5a0ba852e0fa00a4ba4f2908170/Wrappers/Python/ccpi/framework/framework.py#L826) is a static method to calculate `a*X+b*Y`, named `axpby`. 

I think it would be useful to have the same method exposed in SIRF with the same signature. In CIL this is by no means finished and could be agreed upon.

**Comment by paskino** [comment]
The current signature is

```python

def axpby(x,y,out,A,B,dtype=numpy.float32):
    ...
```
Maybe it'd be better as below?

```python

def axpby(a, x, b, y, out, dtype=numpy.float32):
    ....

```

**Comment by paskino** [comment]
For compatibility, I think it'd be better not to have a `staticmethod` for `axpby`.

**Comment by KrisThielemans** [comment]
@paskino why is this still open?

**Comment by evgueni-ovtchinnikov** [comment]
clearly outdated
