### ISSUE TITLE
Gadgetron DICOM writer fails with no error

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#481]
I was trying to use the MR DICOM writer. There was no error, but no output was being produced either. It took me a while to think about checking the gadgetron server, which said:
```
DicomFinishGadget::process, does not supprot ISMRMRD_CXFLOAT data type
Gadget (DicomFinish) process failed
Gadget (DicomFinish) Close Called with flags = 0
Gadget (DicomFinish) Close Called with flags = 1
```
Is there any way we can return this information and print it ourselves?

I've flagged this for this particular use case, but presumably it would be useful elsewhere (i.e., implement it everywhere we call Gadgetron gadgets).

**Comment by evgueni-ovtchinnikov** [comment]
I am out of my depth here, you better ask Hansen
