### ISSUE TITLE
Script osem_reconstruction.m crashes Matlab on recon.setup call

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#524]
Script `osem_reconstruction.m` crashes Matlab on recon.setup call.

Other scripts using OSMAPOSL, e.g. `reconstruct_from_listmode.m` and `osem_reconstruction.py`, work fine, which is weird as debug print shows the crash happens in C++ code.

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans: Traced the trouble to `PoissonLogLikelihoodWithLinearModelForMeanAndProjData::distributable_sensitivity_computation`.

**Comment by evgueni-ovtchinnikov** [comment]
Tried starting MATLAB with `-singleCompThread` - still crashes. Same for setting the number of threads to 1 by `maxNumCompThreads(1)`. :(

**Comment by KrisThielemans** [comment]
I doubt this is  a MATLAB threading conflict. Even if it's anything to do with threading at all. Best to try STIR  without openmp first

**Comment by evgueni-ovtchinnikov** [comment]
With STIR built without openmp works.

**Comment by evgueni-ovtchinnikov** [comment]
Same trouble with `hkem_reconstruction.m`.

**Comment by KrisThielemans** [comment]
Note that this is on Windows. We haven't tested on Linux nor OSX

**Comment by KrisThielemans** [comment]
won't fix due to matlab support on hold
