### ISSUE TITLE
Travis OSX failing

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#539]
As per [this PR](https://travis-ci.org/CCPPETMR/SIRF/builds/645919419?utm_source=github_status&utm_medium=notification) on my fork, OSX jobs give the following error:
```
fatal: reference is not a tree: ec87ff4183b7d938bdb9513bca570d18c9502a99
CMake Error at /Users/travis/build/CCPPETMR/SIRF-SuperBuild/builds/SIRF/tmp/SIRF-gitclone.cmake:40 (message):
    Failed to checkout tag: 'ec87ff4183b7d938bdb9513bca570d18c9502a99'
```

**Comment by evgueni-ovtchinnikov** [comment]
I keep getting similar error messages now and then

**Comment by KrisThielemans** [comment]
this seems obsolete. Closing therefore. Do reopen if that was inappropriate.
