### ISSUE TITLE
Norm for GE Signa.

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#55]

**Comment by KrisThielemans** [comment]
Need to use `BinNormalisationFromGEHDF5` if it's a HDF5 files

**Comment by KrisThielemans** [comment]
Use
https://github.com/UCL/STIR/blob/master/src/include/stir/IO/GEHDF5Wrapper.h
```
static bool check_GE_signature(const std::string& filename);
```
if `true`, then read with `BinNormalisationFromGEHDF5`
```
