### ISSUE TITLE
Module deprecation missing on VM

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#552]
Running `ctest` on VM got `no module named deprecation` error. Had to do `sudo pip istall deprecation`.

**Comment by KrisThielemans** [comment]
This is a VM issue. Please file in approriate place.

However, this has been addressed by @paskino in https://github.com/CCPPETMR/CCPPETMR_VM/pull/143. I believe I also asked to put this in our installation instructions. Not sure if that happened.

More worrying is why we need it.

**Comment by rijobro** [comment]
Apologies, I added it in https://github.com/CCPPETMR/SIRF/pull/497, where I wanted to deprecate `process` in favour of `forward`/`back`/`direct`/`adjoint`. I can remove it if it's causing too much hassle.

**Comment by KrisThielemans** [comment]
if it serves a purposes, it's fine of course. Should be added to our list of required Python modules.

I suggest we do that by addressing #124. Seems a 5 minute job to copy the list into that file. Then in the install instructions we just link to the file. Later on, in the VM, we use it to pip install.

**Comment by KrisThielemans** [comment]
Also missing on TRAVIS.

**Comment by evgueni-ovtchinnikov** [comment]
VM now has deprecation, so closing the issue
