### ISSUE TITLE
matlab catch-up

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#555]
make a list of things that need to be done

- [ ] `SeparableGaussianImageProcessor`
- [ ] `set_image_data_processor` for STIR (#556)

**Comment by rijobro** [comment]
- [ ]  matlab niftypet projector

**Comment by KrisThielemans** [comment]
- [ ] min/max threshold (#643)

**Comment by KrisThielemans** [comment]
- [ ] doc for `GeometricalInfo` currently says https://github.com/SyneRBI/SIRF/blob/75364cb9367da94dabca8f79cbb976fcd5eb1d3a/src/common/%2Bsirf/%2BSIRF/GeometricalInfo.m#L2

**Comment by paskino** [comment]
In Python STIR.py and in `AcquisitionModel` we updated the default signature of `forward` and `backward` https://github.com/SyneRBI/SIRF/pull/821#issuecomment-756064065

 - [ ] add instance member `num_subsets` and `subset_num` to `AcquisitionModel` in MATLAB
 - [ ] use these as default values for `backward` and `forward`

**Comment by KrisThielemans** [comment]
we've stopped supporting MATLAB.
