### ISSUE TITLE
stir.make_Poisson_loglikelihood seems to ignore the model parameter

### ISSUE THREAD

**Issue by francescaleek** [SyneRBI/SIRF#567]
Attenuation model is not used in objective function if specified within `pet.make_Poisson_loglikelihood` 
```python
obj_fun_attn = pet.make_Poisson_loglikelihood(acquired_data_with_attn,  model=am_with_attn)
```
it only works when doing the following
```python
obj_fun_attn.set_acquisition_model(am_with_attn)
```

**Comment by KrisThielemans** [comment]
tested in python

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov  can you look at this one?

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans: So far as I can see from these two lines:
```
def make_Poisson_loglikelihood(acq_data, model = 'LinearModelForMean'):
...
    obj_fun = PoissonLogLikelihoodWithLinearModelForMeanAndProjData()
                                      ~~~~~~~~~~~~~~~~~~
```
`model` argument does not specify the acquisition model. My guess is, it specifies particular Poisson LogLikelihood model - cannot really say anything more useful, I am afraid, being out of my depth here.

**Comment by rijobro** [comment]
Seems there are two different meanings of model here. One being the `AcquisitionModel` (which is what @francescaleek expected), the other being the "model" used for the likelihood (e.g., `LinearModelForMean`). Model seems like a confusing name for the latter, we should maybe change it (e.g., `likelihood_type`).

@evgueni-ovtchinnikov perhaps an error should be thrown here?

```
def make_Poisson_loglikelihood(acq_data, likelihood_type = 'LinearModelForMean'):
    if likelihood_type=='LinearModelForMean':
        obj_fun = PoissonLogLikelihoodWithLinearModelForMeanAndProjData()
    else:
       raise error("unknown likelihood type, here's a list of possible entries...")
```

**Comment by rijobro** [comment]
For @francescaleek 's desired functionality, we would also need: 

```
def make_Poisson_loglikelihood(acq_data, likelihood_type = 'LinearModelForMean', model=None):
    if likelihood_type=='LinearModelForMean':
        obj_fun = PoissonLogLikelihoodWithLinearModelForMeanAndProjData()
    else:
       raise error("unknown likelihood type, here's a list of possible entries...")

    if model is not None:
        obj_fun.set_acquisition_model(model)
```

**Comment by KrisThielemans** [comment]
I thinl @rijobro's suggestion is very good. The intention was that we'd be able to figure out the likelihood type from the model anyway (after all, we only need to know what the domain and range are). So I even think that the `likelihood_type` will become irrelevant.

**Comment by KrisThielemans** [comment]
let's use `acq_model` as parameter name
