### ISSUE TITLE
geometrical_info are not copied with algebra in Gadgetron DataContainer

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#568]
Currently when doing [`multiply`](https://github.com/CCPPETMR/SIRF/blob/master/src/xGadgetron/cGadgetron/gadgetron_data_containers.cpp#L813), [`divide`](https://github.com/CCPPETMR/SIRF/blob/master/src/xGadgetron/cGadgetron/gadgetron_data_containers.cpp#L829) and [`axpby`](https://github.com/CCPPETMR/SIRF/blob/master/src/xGadgetron/cGadgetron/gadgetron_data_containers.cpp#L790) in `GadgetronImageData` the geometrical info are not copied despite [`cSIRF_multiply`](https://github.com/CCPPETMR/SIRF/blob/master/src/common/csirf.cpp#L137) calls [`new_data_container_handle()`](https://github.com/CCPPETMR/SIRF/blob/master/src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_data_containers.h#L722) which calls [`set_meta_data`](https://github.com/CCPPETMR/SIRF/blob/master/src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_data_containers.h#L731).

[This](https://github.com/paskino/SIRF/commit/655be5f3eed9b5d1e2231ad8a2558813f4cd0d34) branch adds a fix.

**Comment by evgueni-ovtchinnikov** [comment]
looks like this fix has been merged
