### ISSUE TITLE
MR_TESTS_PYTHON fails for Gadgetron master

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#572]
`test1.test_main` fails with: 
```
    Start 1: MR_TESTS_PYTHON

1: Test command: /usr/bin/python "-m" "nose" "--with-coverage" "--cover-package=sirf.Gadgetron" "src/xGadgetron/pGadgetron/"
1: Test timeout computed to be: 10000000
1: Message received with ID: 5
1: Input stream has terminated
1: Message received with ID: 5
1: Input stream has terminated
1: EMessage received with ID: 5
1: Input stream has terminated
1: Message received with ID: 5
1: Input stream has terminated
1: EMessage received with ID: 5
1: Input stream has terminated
1: Message received with ID: 5
1: Input stream has terminated
1: E
1: ======================================================================
1: ERROR: test1.test_main
1: ----------------------------------------------------------------------
```
and the output from the Gadgetron server is:
```
03-11 09:11:14.859 INFO [Server.cpp:40] Accepted connection from: ::ffff:127.0.0.1
03-11 09:11:14.860 INFO [ConfigConnection.cpp:112] Connection state: [CONFIG]
03-11 09:11:14.861 INFO [HeaderConnection.cpp:82] Connection state: [HEADER]
03-11 09:11:14.861 INFO [StreamConnection.cpp:75] Connection state: [STREAM]
03-11 09:11:14.861 DEBUG [Stream.cpp:52] Loading Gadget RemoveROOversampling of class RemoveROOversamplingGadget from 
03-11 09:11:14.871 DEBUG [Gadget.h:130] Shutting down Gadget ()
03-11 09:11:14.872 ERROR [Core.cpp:18] [Connection Main Thread] ERROR: Unable to load ISMRMRD XML header
03-11 09:11:14.872 INFO [Core.cpp:76] Connection state: [FINISHED]
```

**Comment by rijobro** [comment]
@evgueni-ovtchinnikov any ideas?

**Comment by KrisThielemans** [comment]
looks like it cannot read the input file with ISMRMRD

**Comment by rijobro** [comment]
It's running on AcquisitionData (which has XML), but @johannesmayer thinks the XML that it's referring to isn't the input file, but rather the configuration string that gets sent from SIRF to the Gadgetron server. 

I've built Gadgetron in Debug mode with a breakpoint when an error is thrown, but the stack doesn't make much sense to me, so I can't figure out where the problem is.

**Comment by evgueni-ovtchinnikov** [comment]
Most likely, the acquisition data has old xml header (Gadgetron master requires version 4).

**Comment by rijobro** [comment]
@evgueni-ovtchinnikov what's the generate shepp logan command (and arguments) you use for generating data? I'll try to put it into the Cmake process.

**Comment by KrisThielemans** [comment]
are we guaranteed to have ISMRMRD executables in the path? (not all of them are built all the time).

Also, I guess you cannot be sure that the Gadgetron that's running is the same as the ISMRMRD version we're compiling with...

sigh.

**Comment by evgueni-ovtchinnikov** [comment]
executable: `ismrmrd_generate_cartesian_shepp_logan`
arguments:
fully sampled: `-r 2`
undersampled: `-a 2 -w 64`

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov @johannesmayer this seems to be the issue we talked about

**Comment by KrisThielemans** [comment]
> are we guaranteed to have ISMRMRD executables in the path? (not all of them are built all the time).

Possibly we could do this as follows: if ` ismrmrd_generate_cartesian_shepp_logan` is found, use it to generate the test data, otherwise use the existing data. Difficulty however is that ideally we don't let this overwrite the existing data, as that'll create trouble with `git` and subsequent SuperBuild updates. Therefore, the tests will need to be passed the filename (maybe that's trivial, I don't know).

> you cannot be sure that the Gadgetron that's running is the same as the ISMRMRD version we're compiling with..

this is going to create major problems in any case, so if the test fails, I think that would be reasonable enough

**Comment by evgueni-ovtchinnikov** [comment]
we could add subfolder `data` to `examples` to hold newly generated data

can cmake delete files? (because `ismrmrd_generate_cartesian_shepp_logan` would add to existing file)

**Comment by KrisThielemans** [comment]
Obsolete. Everything works fine now.
