### ISSUE TITLE
warning in gadgetron_image_wrap.h

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#573]
Compiling with VS 2015 gives
```
c:\users\krisf\documents\devel\sirf\src\xgadgetron\cgadgetron\include\sirf\gadgetron\gadgetron_image_wrap.h(319): warning C4715: 'sirf::ImageWrap::head': not all control paths return a value
```
I haven't checked, but it doesn't  sound good.

**Comment by evgueni-ovtchinnikov** [comment]
`ISMRMRD::ImageHeader& head()` must return a reference to an image header.
For as long as the image data type is one of the 8 allowed, returning a value is guaranteed.
Otherwise a reference that could have been returned is nowhere to get from.
