### ISSUE TITLE
Large amount of (excess?) code for coil container

### ISSUE THREAD

**Issue by johannesmayer** [SyneRBI/SIRF#579]
@ckolbPTB @evgueni-ovtchinnikov @rijobro 

I wanted to suggest reviewing the amount of classes necessary for handling coilmaps in SIRF.
In gadgetron_data_containers.h I think there are 8 classes dedicated to coil map handling and I think this is too much.

I would suggest to not have all these other abstract classes flying around because in the end coil maps are just images, and we already have a class for that.

I would suggest something of the like:
```
class CoilDataContainer : public DataContainer 
{
public:
    
    forward( GadgetronImageData& individ_channels, const GadgetronImageData&  combined_image) const; //alias: apply_coilmaps
    backward ( GadgetronImageData& combined_image, const GadgetronImageData&  individual_channels) const; //alias: combine_coilmaps

    compute_coilmaps( const MRAcquisitionData& acq_dat );         
    compute_coilmaps( const GadgetronImageData& img_dat );

    set_coil_maps(const GadgetronImageData& csm);
    std::shared_ptr<GadgetronImageData> get_sptr_coil_maps() const ;

protected:
    std::shared_ptr<GadgetronImageData> csm_;
}
```

This would make it really easy to implement the `forward()` and `backward()` method because in implementation you have an object of class `GadgetronImagesVector` and you need to have a matching set of coilmaps, then they can be multiplied and added.

**Comment by rijobro** [comment]
You obviously know more than me on this, but if coil maps are simply images, shouldn't `CoilDataContainer` inherit from `ImageData`, not `DataContainer`?

**Comment by johannesmayer** [comment]
The coildata container should hold some form of image data, but actually it is not an image container itself. 

Ideally it would just be a wrapper holding some coilmaps as images with methods on how to compute them and how to apply them.

**Comment by rijobro** [comment]
Sounds reasonable to me. @evgueni-ovtchinnikov ?

**Comment by evgueni-ovtchinnikov** [comment]
I agree that the implementation of coil data is much too cumbersome. I thought of simplifying it a number of times but each time postponed as not crucial.

Treating coil data as GadgetronImageData would be of course much simpler but I could not quite stomach the idea of if-then-erlses involved when the data type is known. It just occured to me right now though that if those if-then-elses started with checking for complex_float_t first then things would be not that bad really!

**Comment by johannesmayer** [comment]
Why do we need to check for data type? Coilmaps are always complex...
I could do the simplification, but then I would have to ensure backwards compatibility, correct?

**Comment by evgueni-ovtchinnikov** [comment]
> Why do we need to check for data type? Coilmaps are always complex...

My point precisely - if you just declare a coil map as `GadgetronImageData` (or as a wrapper around it), then a number of operations on it would involve using `IMAGE_PROCESSING_SWITCH` (see `gadgetron_image_wrap.h`) and iterators would use `NumRef`, which essentially uses similar if-then-else construct.

> I could do the simplification, but then I would have to ensure backwards compatibility, correct?

To keep backward compatibility you just need to make sure that all existing functionality of coil data is preserved. One of the cornerstones of the Object Oriented coding is that the implementation of a type must be totally independent from its specification  (public section of the class declaration in `.h`, which ideally must have method prototypes only).

**Comment by johannesmayer** [comment]
But which container class should we keep then? 

Because there is `CoilDataAsCFImage`, `CoilDataVector`, `CoilImagesVector` and `CoilSensitivitiesAsImages` plus four more abstract classes...
But actually needed would probably be only the last one...

**Comment by evgueni-ovtchinnikov** [comment]
You need two classes: for coil images and for coil sensitivities (as we have it in `Gadgetron.py`).

**Comment by KrisThielemans** [comment]
only thing to do is the duplication of the FFT code.
