### ISSUE TITLE
Operator == for ImageData conflicts with the one for NiftiImageData

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SynerBI/SIRF#584]
@rijobro: I have implemented `operator==` for `ImageData`, but run into a conflict with the one in `NiftiImageData`: executing
```
nifti_image = NiftiImageData3D(image)
print(image == nifti_image)
``` 
where `image` is an `ImageData`, raises AssertionError in `NiftiImageData.__eq__` (which is bewildering as `ImageData.__eq__` should have been called).

I added `or isinstance(other, SIRF.ImageData)` in `NiftiImageData.__eq__`, but I got
```
'NiftiImageData<dataType>::are_equal_to_given_accuracy: Image 2 not initialised.' exception caught at line 360 of /home/sirfuser/devel/buildVM/sources/SIRF/src/Registration/cReg/cReg.cpp
```

If I comment out `NiftiImageData.__eq__` (which should be ok because I have `__eq__` in the base class), then the above problem disappears, and my Python ctests run ok, but `SYN_TEST_PYTHON` fails:
```
2:       Start 10: SYN_TEST_PYTHON
2: 10/10 Test #10: SYN_TEST_PYTHON .........................***Failed    1.89 sec
2: 
2: # --------------------------------------------------------------------------------- #
2: #                             Starting STIR to Nifti test...
2: # --------------------------------------------------------------------------------- #
2: 
2: WARNING: Unable to determine patient position. Internally this will generally be handled by assuming HFS
2: 
2: Saving image to file (results/stir_to_nifti.nii)...F
2: ======================================================================
2: FAIL: test_pSynergistic.test
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
2:     self.test(*self.arg)
2:   File "/home/sirfuser/devel/buildVM/sources/SIRF/src/Synergistic/tests/test_pSynergistic.py", line 209, in test
2:     try_stirtonifti(nifti_filename)
2:   File "/home/sirfuser/devel/buildVM/sources/SIRF/src/Synergistic/tests/test_pSynergistic.py", line 50, in try_stirtonifti
2:     raise AssertionError("Conversion from STIR to Nifti failed.")
2: AssertionError: Conversion from STIR to Nifti failed.
```

**Comment by rijobro** [comment]
You're right, that is strange.

If `image == nifti_image` calls the `==` operator in `NiftiImageData`, then which one is called for `nifti_image == image`?

**Comment by rijobro** [comment]
> If I comment out NiftiImageData.__eq__ (which should be ok because I have __eq__ in the base class), then the above problem disappears, and my Python ctests run ok, but SYN_TEST_PYTHON fails

This is probably because you're now using a different implementation of the `==` operator. If you check differently, there's no guarantee you'll get the same boolean output as to whether they match or not.

**Comment by evgueni-ovtchinnikov** [comment]
The problem is not with the boolean output not being the same - it should not raise any assertion error, or 'image not initialised' error.

**Comment by evgueni-ovtchinnikov** [comment]
`nifti_image == image` raises the same eror in `NiftiImageData.__eq__`

**Comment by rijobro** [comment]
The first one is causing the "uninitialised image" error, the second one uses the `==` to check if it successfully convert a `STIRImageData` to a `NiftiImageData`. If it fails, it raises an AssertionError.

**Comment by rijobro** [comment]
some things to try:

- `print(type(image))` <- I don't think `image` can be of type `ImageData`, as that's an abstract class. So what type is it? My guess is `NiftiImageData`, since the `NiftiImageData::__eq__` method is being used.
- If it complains that the image is uninitialised, you could try converting it to `NiftiImageData` explicitly and then doing the comparison, e.g.: `nifti_image == sirf.Reg.NiftiImageData(image)`.

**Comment by evgueni-ovtchinnikov** [comment]
Pending thorough investigation, successfully applied this workaround:

* renamed `__eq__` to `equal` in `SIRF.ImageData` and `NiftiImageData`
* added `__eq__` simply calling `equal` in `SIRF.ImageData`
* added `__eq__` trying to call `NiftiImageData.equal` and if this fails, calling `SIRF.ImageData.equal`

BTW, is it possible to run synergistic tests only? `ctest -VV -R SYN_TEST*` does not work.

**Comment by rijobro** [comment]
I suspect you would have to do:
`ctest -VV -R SYN_TEST`
or 
`ctest -VV -R "SYN_TEST*"`

**Comment by KrisThielemans** [comment]
seems interesting Python behaviour, possibly an artefact of how we wrap the C++ code at first glance, I don't think this would happen on the C++ side (do we have a test in C++ as well?).

@evgueni-ovtchinnikov don't forget to close this issue with the relevant commit. thanks!

**Comment by evgueni-ovtchinnikov** [comment]
@rijobro: neither works, likely because all SIRF tests sit inside `SIRF_TEST` and `ctest` does not see them (e.g `ctest -R Gadgetron` works ok). Such a nuisance having to wait several minutes after each attempt to fix just one small test...

@KrisThielemans: have not had any problems with C++ tests.

**Comment by KrisThielemans** [comment]
> neither works, likely because all SIRF tests sit inside SIRF_TEST and ctest does not see them

interesting problem! Your're running from a SuperBuild project? I guess you'll have to manually change directory into `builds/SIRF/build` and do the `ctest` from there.

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans: thanks a lot, it works!
