### ISSUE TITLE
Constant generation of temp files when wrongly mixing AcquisitionData and numpy

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF#591]
If you do `np.dot(AcquisitionData,np.array)` it will not crash, but instead generate a lot (not sure how many, I cancelled execution) of .s .sh temp files. 

This should instead either do the correct thing (take the acquisition dataas `np.array` and do `np.dot`) or error due to incompatible types/operation. 

Hot to reproduce: In the example `PET/acquisition_model.py ` add, after line 152
https://github.com/CCPPETMR/SIRF/blob/36c3d58dd283dd4bbfa1ca83d9f8b29a94c4a0ff/examples/Python/PET/acquisition_model.py#L152

**CAUTION**: be ready to break execution. 

```
import numpy as np
y0=np.random.rand(*simulated_data_as_array.shape)
np.dot(y0,simulated_data)
```

**Comment by KrisThielemans** [comment]
We cannot change `np.dot` but don't know what method of `AcquisitionData` will be called by `np.dot`. Seems we need to use a Python debugger to step into `np.dot` to find out.

**Comment by evgueni-ovtchinnikov** [comment]
1. This is not SIRF problem, and I believe we assume basic knowledge of numpy, are we not?
2. Our data containers have their own `dot` method, so the user can do it this way:
```
random_data = AcquisitionData(simulated_data).fill(y0)
s = random_data.dot(simulated_data)
```

**Comment by AnderBiguri** [comment]
Hi @evgueni-ovtchinnikov ! While I completely agree with your assessment that this is not a SIRF problem and that its comming from a bug in the script, not proper utilization, I think we should do something about it though. My rationale was:

1. Its not crazy to thing that an object that basically is an image container is compatible with `np.array` operations. 

2. If a bug caused by something that is not necessarily a blatant misinterpretation of python/numpy/SIRF can cause thousands of files on your hard drive appear, we should try to avoid it (same rationale you can not do `rm -rf \` anymore n many linux distros)

But I am new here! Don't take it as criticism, its more of an explanation why I opened this issue.

**Comment by KrisThielemans** [comment]
I'm reopening. I agree that this isn't a bug per se, but where-ever things can go horribly wrong, we should put in some basic error checks, just like we throw exceptions in other places.

It isn't high priority of course.

**Comment by evgueni-ovtchinnikov** [comment]
How can we possibly check what the user passes to numpy.dot?

**Comment by KrisThielemans** [comment]
Indeed, we cannot. The idea therefore is to try and see what method that `np.dot` is calling from the SIRF object. Presumably there's something wrong there (i.e. it should have error-ed out). This seems hard though, but @AnderBiguri  was going to see with a Python debugger if he could get some idea if what's going on.

**Comment by AnderBiguri** [comment]
I am still a bit new with the python debugger, but when I debug, the call to `np.dot` it directly goes to `DataContainer.__rmul__` and it is called repeatedly. Each time a couple of temp files are created on this line (which I assume is expected behavior)
https://github.com/CCPPETMR/SIRF/blob/d129c0a86c91afbe3a9a260379e362fb73a105f5/src/common/SIRF.py#L281

I am however unable to see who calls this function iteratively. It should be `np.dot`.[ I know this is implemented in C](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/arraytypes.c.src#L3425) , but would that call the python code? I doubt so.  In any case, I have no idea how to debug this further and @evgueni-ovtchinnikov is likely right that it has no clear way of being solved.

**Comment by evgueni-ovtchinnikov** [comment]
closing as clearly none of us have sufficient expertise to debug `numpy.dot`
