### ISSUE TITLE
synerbi transition:

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#614]
See https://github.com/orgs/SynerBI/projects/1#card-35844051

---

- [x] website update existing or new from scratch?, 
- [x] mailing lists (@KrisThielemans), 
- [x] github [organisation](https://github.com/CCPPETMR/SIRF/projects/4#card-35657657)
- [x] zenodo (with David and Ben),
- [ ] `ccppetmr@stfc.ac.uk`?
- [x] [slack](https://slack.com/intl/en-gb/help/articles/201663443-Change-your-workspace-or-org-name-and-URL) (@paskino)
- [x] hub.docker.com (@casperdcl)
  + [x] SuperBuild docker (@casperdcl)
- [x] ccp.petmr.devel email (we will leave this as-is. too much work)
  + [ ] @ccp-petmr-codebot user, 
  + [ ] youtube user
  + [x] slack admin
  + [x] JISCMAIL admin
  + [ ] googlegroups admin, 
  + [ ] github-stats owner and fixes
- [x] travis
- [x] codacy
- [ ] coverage
- [ ] coverall
what else?
 - [x] ResearchGate
 - [x] ResearchFish (not necessary. this is managed by UKRI. we have no control)

Name: www.ccpsynerbi.ac.uk. Others SyneRBI.

Contacts page needs to be kept in sync!

**Comment by paskino** [comment]
I am not the owner of the slack channel and cannot rename it. Who may be? 
 - @casperdcl 
 - @bathomas  
 - @KrisThielemans  
 - @evgueni-ovtchinnikov

**Comment by KrisThielemans** [comment]
> I am not the owner of the slack channel and cannot rename it. Who may be?

**Comment by KrisThielemans** [comment]
Note somewhat confusing to have checklists here and in https://github.com/SynerBI/SIRF/projects/4#card-35657657. The latter is more up-to-date at present. I suggest to keep it that way (but tick off here as well)

**Comment by rijobro** [comment]
> I am not the owner of the slack channel and cannot rename it. Who may be?

Not me either. 

![image](https://user-images.githubusercontent.com/33289025/78536487-d4d27580-77e5-11ea-8196-86a162ec1ca6.png)

**Comment by casperdcl** [comment]
> I am not the owner of the slack channel and cannot rename it. Who may be? 

Me neither

**Comment by casperdcl** [comment]
NVM the bot seems to have admin access (Kris/Edo you should have the credentials). Or I can change it... what do you want it changed to?

Currently:

Name: `CCP PETMR`
URL: `ccppetmr`

Maybe consider just `SIRF`/`sirf`?

**Comment by casperdcl** [comment]
P.S. @paskino I made both of us admins now; @KrisThielemans I made you owner.

**Comment by KrisThielemans** [comment]
thanks. Sadly I have no idea what NVM is... sorry!

**Comment by casperdcl** [comment]
nvm=nevermind :) don't know why I capitalised it. Anyway you should be able to change things using your own account now.

**Comment by KrisThielemans** [comment]
:-) so... which bot are you talking about then? (I'm clearly on top of all this!)

**Comment by casperdcl** [comment]
![image](https://user-images.githubusercontent.com/10780059/78550884-c774b580-77fc-11ea-8591-7cf016b3fe54.png)

**Comment by KrisThielemans** [comment]
sorry @casperdcl I still have no clue...

**Comment by rijobro** [comment]
looks like a screenshot from slack

**Comment by KrisThielemans** [comment]
While hunting for why some Travis jobs failed, I found that the github-stats fail
https://travis-ci.org/github/SynerBI/SIRF-SuperBuild/jobs/672298976#L1660 with `HTTP Error 404: NOT FOUND`. @casperdcl is this related to the transition? By the way, is there some (very brief) doc on the github-stats anywhere?

**Comment by KrisThielemans** [comment]
HDF5 jobs are failing because we try to download from https://www.ccpsynerbi.ac.uk/sites/www.ccpsynerbi.ac.uk/files/downloads/hdf5-1.10.1.tar.gz which doesn't exist yet

**Comment by casperdcl** [comment]
> github-stats

Yes I saw they are failing (but at least not causing jobs to fail)

> HDF5

Any reason we're not hosting that on github? We can easily add that as a release asset or even in a separate repo. Both would provide direct download URLs.

**Comment by KrisThielemans** [comment]
@paskino @evgueni-ovtchinnikov can you please update the contacts page to be in sync with the above? Example: slack is now synerbi.slack.com. github org changes, ResearchGate changed (maybe not URL). zenodo not yet. check the checklist!

**Comment by casperdcl** [comment]
Zenodo would require a new release but it should "just work" with no further configuration.

**Comment by KrisThielemans** [comment]
> > HDF5
>
> Any reason we're not hosting that on github? We can easily add that as a release asset or even in a separate repo. Both would provide direct download URLs.

Clearly, ideally we don't host his stuff ourselves. In the past, we've had trouble with the HDF5 and FFTW websites being accessible, hence this lousy work-around.

Putting it on github is probably a better idea. I don't really want to have a repo with the source of HDF5 and FFTW though. Those projects aren't in great shape as far as version tracking goes etc, and  it'd lead us astray.

I have no idea about "release assets". If this can be done with minimal maintenance effort, it'd be great. We'd probably need help though... (I'm hoping that the synerbi website will be up soon.)

**Comment by casperdcl** [comment]
Just created a repo [SynerBI/assets](https://github.com/SynerBI/assets) with a release tag [SynerBI/assets@latest](https://github.com/SynerBI/assets/releases/tag/latest) which we can freely update with more binaries in future (using https://github.com/SynerBI/assets/releases/edit/latest).

So we can now use this URL instead:

https://github.com/SynerBI/assets/releases/download/latest/hdf5-1.10.1.tar.gz

Note that if you do a trace on this URL you'll notice that the file is actually hosted on AWS.

**Comment by KrisThielemans** [comment]
excellent. thanks!

@paskino @evgueni-ovtchinnikov are there any other files (e.g. FFTW) that need to be there? Please do so, and add a commit at https://github.com/SynerBI/SIRF-SuperBuild/pull/372

**Comment by KrisThielemans** [comment]
I've added codacy https://app.codacy.com/gh/SyneRBI.

I've also expanded our check-list again. @casperdcl maybe you can tick a few off that you've already done.

**Comment by KrisThielemans** [comment]
also badges in README #708. Probably same for the the superbuild.

**Comment by KrisThielemans** [comment]
@casperdcl I need some advice I'm afraid.

- https://codecov.io/gh/SyneRBI/SIRF doesn't update (last commit 6 months ago).
-https://coveralls.io/github/CCPPETMR/SIRF doesn't update either, but that's not a surprise. I've enabled the SyneRBI repo but https://coveralls.io/github/SyneRBI/SIRF says I need to add a `.coveralls.yml` with a repo taken for travis-pro

I don't understand what happened that we don't have any `yml` config files, nor really what I have to do. Would you be able to help?

**Comment by casperdcl** [comment]
doesn't look like `.coverage` is being generated (at least not in the expected location). TL;DR travis logs (after `ctest` passes):

```bash
$ pushd ../SIRF
$ codecov
    Error running `['/usr/bin/python2', '-m', 'coverage', 'xml', '-i']`: Command '['/usr/bin/python2', '-m', 'coverage', 'xml', '-i']' returned non-zero exit status 1
    - Ignored: [Errno 2] No such file or directory: '/home/travis/build/SyneRBI/SIRF/coverage.xml'
Error: No coverage report found
$ coveralls
coverage.misc.CoverageException: Data file '/home/travis/build/SyneRBI/SIRF/.coverage' doesn't seem to be a coverage data file: Couldn't use data file '/home/travis/build/SyneRBI/SIRF/.coverage': no such table: coverage_schema
```

**Comment by KrisThielemans** [comment]
SuperBuild badges sorted

**Comment by paskino** [comment]
Shall we close this @KrisThielemans ?

**Comment by KrisThielemans** [comment]
`coverage` and `coveralls` have their own issues I believe.

I guess we're not fixing the owner nor the email address.

so yes, let's close
