### ISSUE TITLE
NiftyReg dot() type error

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF#627]
for something like: 

```
examples_path = SIRF_PATH + '/data/examples/Registration'
x = sirf.Reg.NiftiImageData3D(rexamples_path + "/test.nii.gz") #ref_aladin 
T = na.get_transformation_matrix_forward()
y = sirf.Reg.NiftiImageData3D(examples_path + "/test2.nii.gz") #flo_aladin

nr = sirf.Reg.NiftyResample()
nr.set_reference_image(x)
nr.set_floating_image(y)
nr.set_interpolation_type_to_linear()
nr.add_transformation(T)
# Add this on test_pReg.py#L950 to test.

# NOTE: you need PR #626 for this to work. Otherwise shaw domain/range
x = nr.domain_geometry().allocate(value = 'random')
y = nr.range_geometry().allocate( value = 'random')
y_hat = nr.direct(x)
this_errors = y_hat.dot(y)
```
The error reads:

```
File "/home/anderbiguri/SIRF/build/sources/SIRF/src/Registration/pReg/tests/test_pReg.py", line 960, in try_niftymomo
this_errors = y_hat.dot(y)
File "/home/anderbiguri/SIRF/build/INSTALL/python/sirf/SIRF.py", line 101, in dot
assert_validities(self, other)
File "/home/anderbiguri/SIRF/build/INSTALL/python/sirf/Utilities.py", line 396, in assert_validities      type(y)))
AssertionError: Expecting same type input, got <class 'sirf.Reg.NiftiImageData'> and <class 'sirf.Reg.NiftiImageData3D'>
```

Apparently it returns a different class when you do `allocate()` (`NiftiImageData3D`, as the original variable type) and when you do `direct()` (`NiftiImageData`), but both are  supposed to be conceptually the same thing.

Any suggestions on how to fix this are welcomed. 

I can think of 

1. Change `direct()` to return `NiftiImageData3D`. This will likely cause lots of errors down the chain of functions that expect this method's output to be `NiftiImageData`. 
2. Change `dot()` so it allows some cases of different classes as input. 

You can test this code adding it on `test_pReg.py#L950` and using PR #626 (or simply swap domain/range in the code).

**Comment by rijobro** [comment]
If you look at the source code (`Reg.py`), does the `.dot` method check that the argument type matches that of `self`? From the error: `AssertionError: Expecting same type input`, I'm guessing that this is the case.

Probably just changing it to check that the input is of type `NiftiImageData` would solve this one.

**Comment by AnderBiguri** [comment]
@rijobro `.dot()` is not in `Reg.py` .... I will try to hunt it. Yes, the obvious solution here is my proposed 2): make sure `.dot()` accepts things that are similar enough even if they are not the same class. Is that OK? Can I change the code that way? I have no idea if this is what you guys want or it breaks some other thing I am not aware of, this is why I asked for suggestions.

**Comment by rijobro** [comment]
Just had a look and it lives in `SIRF.py`. I don't see why it can't check that the input argument is a `DataContainer`, since in the C++ level, they only get converted to that:
```
extern "C"
void*
cSIRF_dot(const void* ptr_x, const void* ptr_y)
{
	try {
		DataContainer& x =
			objectFromHandle<DataContainer >(ptr_x);
		DataContainer& y =
			objectFromHandle<DataContainer >(ptr_y);
		float s;
		std::complex<float> z(0.0, 0.0);
		x.dot(y, &z);
		return dataHandle(z);
	}
	CATCH;
}

```

**Comment by rijobro** [comment]
This is the problematic check in `.dot()` by the way:
```
assert_validities(self, other)
```

**Comment by AnderBiguri** [comment]
@rijobro  so `assert(isinstance(other,DataConatiner))` (or some similar syntax) should work right? I will give that a go. 

This code does not check for same size inputs (at least number of elements). Does `cSIRF_dot` do that, or should I add that check too?

**Comment by rijobro** [comment]
Just looked through the source code and in `DataContainer.h`:
```virtual void dot(const DataContainer& dc, void* ptr) const = 0;```
This means that it is an abstract method and needs to be overloaded. If you look at one of the overloaded examples (in this case `NiftiImageData`:
```
template<class dataType>
void NiftiImageData<dataType>::dot(const DataContainer& a_x, void* ptr) const
{
    const NiftiImageData<dataType>& x = dynamic_cast<const NiftiImageData<dataType>&>(a_x);
    assert(_nifti_image->nvox == x._nifti_image->nvox);
    double s = 0.0;
    for (unsigned i=0; i<this->_nifti_image->nvox; ++i)
        s += double(_data[i] * x._data[i]);
    float* ptr_s = static_cast<float*>(ptr);
    *ptr_s = float(s);
}
```
So you can see that it will cast the input into a `NiftiImageData`. And if it's not, that will create an error. 

How about in `def dot()` in `SIRF.py` something along the lines of:
```
if isinstance(self,NiftiImageData):
    assert(isinstance(other,NiftiImageData))
else:
    assert_validities(self, other)
```

**Comment by rijobro** [comment]
@evgueni-ovtchinnikov any reason that `dot` should be implemented for each image class? Couldn't it be defined in `ImageData` using the iterators?

**Comment by AnderBiguri** [comment]
@rijobro I see. So _a priori_, `dot` does requires that they are the same class because we can not make assumptions that the C++ implementation can cast. 

About your example code: is `NiftyImageData3D` an instance of `NiftyImageData` ? Or did you just make some assumptions for the illustrative example?

**Comment by rijobro** [comment]
`NiftiImageData3D` is a child of `NiftiImageData` so should return `True`. Hierarchy of this part of SIRF is as follows:
```
DataContainer
    ImageData
        NiftiImageData
            NiftiImageData3D
            NiftiImageData3DTensor
                NiftiImageData3DDisplacement
                NiftiImageData3DDeformation
```

**Comment by evgueni-ovtchinnikov** [comment]
> Couldn't it be defined in ImageData using the iterators?

It could, but performance will suffer (ifs, extra memory transactions). Not crucial (bottlenecks are elsewhere), but somehow cannot quite stomach that.
