### ISSUE TITLE
use of `assert` in C++ code

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#631]
we have some checks done via `assert` in C++.
https://github.com/SyneRBI/SIRF/search?l=C%2B%2B&q=assert
However, these are not seen in normal running (only when compiled in debug mode). Therefore, they are unsafe.

We need to convert this to normal run-time checks and throw exceptions.

In fact, Codacy tells us that `assert` in Python isn't great either as compiled version (I guess pypy and cpython) don't see them either.

**Comment by rijobro** [comment]
Some in the registration are intentional, e.g.:
https://github.com/SyneRBI/SIRF/blob/439ed1ec2fe2b037096f3112ab8d5c035f2082ca/src/Registration/cReg/NiftiImageData.cpp#L286-L297
Much like in STIR, they check that each element is in range, which slows things down and shouldn't be necessary most of the time.

**Comment by AnderBiguri** [comment]
@rijobro but if `#define NDEBUG ` is not defined or `assert.h` included, they do nothing. 

http://www.cplusplus.com/reference/cassert/assert/ says:
>  Therefore, this macro is designed to capture programming errors, not user or run-time errors, since it is generally disabled after a program exits its debugging phase.

On top of the my all around complain ( sorry :D ) that error messages are not clear, even if it would work.

**Comment by KrisThielemans** [comment]
of course. Ideally though we have debugging checks for anything that's callable by python/matlab. Otherwise the innocent user can crash their environment. In this case, we're not exposing index access, so that's not a problem.

I guess (like `std::whatever` and STIR), we should have `at` access as well, which does perform the check always.

**Comment by evgueni-ovtchinnikov** [comment]
@rijobro: can you sort out Reg's asserts please? I will do the rest.

**Comment by evgueni-ovtchinnikov** [comment]
done my part

@rijobro: where check is always needed, you may like to simply replace `assert` with my new macro `ASSERT` (see `LocalisedException.h`); when you are done (and Travis is green), close the issue please
