### ISSUE TITLE
assert_validities dimensions should use any()

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#633]
SuperBuild currently failing ([link](https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/jobs/674690137)) because of a problem with `assert_validities`. In `Utilities.py`, should be something like `any(x.dimensions() != y.dimensions())` as opposed to just `x.dimensions() != y.dimensions()`

**Comment by AnderBiguri** [comment]
@rijobro @KrisThielemans hum...

But tuple comparison should work like this. i.e. 

```
a=(123,12,1)
b=(113,12,1)
print(a==b)
> False
```

Could the problem be that some `dimensions()` do not return a tuple?

**Comment by AnderBiguri** [comment]
Issue is likely that @evgueni-ovtchinnikov and myself both tried to fix the `dimensions()` function, and merging has brought it up together. 

This is the correct function, returning a tuple:
https://github.com/SyneRBI/SIRF/blob/master/src/Registration/pReg/Reg.py.in#L240

But Evgueni added this one in master to give me a hand with my PR. Works, but does not return a tuple, so we agreed that we'd use my version. We simply need to remove this last one. 
https://github.com/SyneRBI/SIRF/blob/master/src/Registration/pReg/Reg.py.in#L254
