### ISSUE TITLE
ListmodeToSinograms:get_time_at_which_prompt_rate... has wrong name

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#640]
This function actually compares the prompt-count with the argument, not the prompt rate (which is counts/s).

If we keep comparing to prompt-count, then it needs to be renamed, and the argument type needs to change from float to `unsigned long`.

**Comment by rijobro** [comment]
so it's actually the cumulative number of counts so far?

**Comment by rijobro** [comment]
ahh prompts per count?
