### ISSUE TITLE
STIR python no output

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#650]
I'm running a reconstruction that's taking much longer than expected. I can see all 28 cores working at 100%, so something must be going wrong. 

SIRF-STIR uses an `int` - the higher the value, the more output. I put it all the way up to 10, which is higher than any of the STIR verbosity values, so everything should be being printed, including projection feedback. However, I only see the SIRF output:
```
Reconstructing gate 1...
Using CPU projector...
raw data: ../../EM_g1.hs
applying attenuation (please wait, may take a while)...
AcquisitionSensitivityModel contains norm and attenuation...
Setting AcquisitionSensitivityModel...
setting up, please wait...
reconstructing, please wait...
```
Any idea what's going on? @AnderBiguri - do I remember seeing an issue/PR from you recently about output verbosity?

**Comment by KrisThielemans** [comment]
impossible to know with this amount of information.

Obviously, will depend on what you did with the redirect, and where the files are. Maybe you have a mistake in the NiftyPETSTIR stuff regarding verbosity?

**Comment by rijobro** [comment]
I noticed it in the ctests as well, but realised that it's because the adjoint and niftypet tests were setting verbosity to `0`. PR here: https://github.com/SyneRBI/SIRF/pull/651.

Doesn't solve my problem, unfortunately, where I haven't used the `set_verbosity` method.

> ..., and where the files are

What does this mean?

**Comment by KrisThielemans** [comment]
do you use `MessageRedirector`? If not, I don't know what its default values are. If you do, output will be in the relevant files

**Comment by AnderBiguri** [comment]
> Any idea what's going on? @AnderBiguri - do I remember seeing an issue/PR from you recently about output verbosity?

Just about the adjoint test verbosity I am afraid. Nothing to do with this. Sorry :(

**Comment by rijobro** [comment]
Thanks, the problem was that I was using the following. I'm confused as to why I ever saw output, but glad it's solved.

```
# direct all engine's information and warnings printing to files
msg_red = MessageRedirector('info.txt', 'warn.txt')
```
