### ISSUE TITLE
NiftiImageData::dump_header extras

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#656]
can we print `qform_code`, `sform_code`, `srow_x`, `y`, `z` as well? Useful for getting a better overview of what's in the header (some programs need sform).

**Comment by rijobro** [comment]
Attaching the [output](https://github.com/SyneRBI/SIRF/files/4623137/output-sirf_print_nifti_info.txt) from running `sirf_print_nifti_info`. 

It contains `qform_code`, `sform_code`. From looking at the [documentation](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h), I think the `srow_x`, `y`, `z` are the separate rows of the `sto_ijk`, which are also output. Is that what you were looking for?

**Comment by KrisThielemans** [comment]
ok. great. Apologies!

@ALEXJAZZ008008 this could be useful for you. `sirf_print_info_info` executable would do this, but you can also call it from python.
