### ISSUE TITLE
Running SIRF examples on Travis?

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#662]
would it be possible to run the non-interactive Python demos on Travis. They tend to create figures, which probably will fail on travis, but maybe there's a way to just let this pass? It would allow us to do a minimal automatic test on them.

**Comment by evgueni-ovtchinnikov** [comment]
tried with `fully_sampled_recon_single_chain.py` but only succeeded after sizeable amount of editing (there seem to be some docopt conflict with @casperdcl runner - had to hardcode options)

**Comment by KrisThielemans** [comment]
Is there a travis job you could point us to? or some other info.

**Comment by evgueni-ovtchinnikov** [comment]
job 2427 (passed)

**Comment by evgueni-ovtchinnikov** [comment]
the new test is `test4.py` (in `pGadgetron/tests`)

**Comment by KrisThielemans** [comment]
that test looks useful. thanks.

However, i guess I wasn't quite clear what I meant (sorry).

I was wondering if we can the *actual* demos to Travis. That way, we (somewhat) prevent the demo being out-of-date, and only discover problems when someone runs the demo by hand. Obviously, the demos are not intended for testing, and therefore most don't do any checking of output. However, just the fact that they run or not would be useful to know.

Problems that I'd anticipate are 
- matplotlib failing (as no X environment on Travis). Might be solvable by using `Agg` (via `.matplotlibrc`, see https://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server, or apparently `xvfb`, see https://stackoverflow.com/questions/35403127/testing-matplotlib-based-plots-in-travis-ci
- demos asking for input of the user, which happens with `show` I believe. Might be solvable by just taking input from `/dev/null` (choosing defaults).

This can be tested on the VM by doing `DISPLAY="" python demo.py </dev/null` I guess.

I certainly don't want to make the demos more complicated to cope with this. Maybe we do it only for a few where it doesn't create trouble.

**Comment by KrisThielemans** [comment]
great. thank!
