### ISSUE TITLE
Build errors on Windows 10

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#665]
building SIRF `master` on my Windows 10 laptop produces lots of error messages like this one:
```
10>sirf_inverse_transform.obj : error LNK2019: unresolved external symbol "protected: virtual class sirf::NiftiImageData3DDeformation<float> * __cdecl sirf::NiftiImageData3DDeformation<float>::get_inverse_impl_nr(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_nr@?$NiftiImageData3DDeformation@M@sirf@@MEBAPEAV12@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z) referenced in function "public: class sirf::NonRigidTransformation<float> * __cdecl sirf::NiftiImageData3DDeformation<float>::get_inverse_impl_nr(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_nr@?$NiftiImageData3DDeformation@M@sirf@@QEBAPEAV?$NonRigidTransformation@M@2@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z)
10>sirf_inverse_transform.obj : error LNK2019: unresolved external symbol "protected: virtual class sirf::NiftiImageData3DDeformation<float> * __cdecl sirf::NiftiImageData3DDeformation<float>::get_inverse_impl_vtk(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_vtk@?$NiftiImageData3DDeformation@M@sirf@@MEBAPEAV12@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z) referenced in function "public: class sirf::NonRigidTransformation<float> * __cdecl sirf::NiftiImageData3DDeformation<float>::get_inverse_impl_vtk(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_vtk@?$NiftiImageData3DDeformation@M@sirf@@QEBAPEAV?$NonRigidTransformation@M@2@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z)
10>sirf_inverse_transform.obj : error LNK2019: unresolved external symbol "protected: virtual class sirf::NiftiImageData3DDisplacement<float> * __cdecl sirf::NiftiImageData3DDisplacement<float>::get_inverse_impl_nr(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_nr@?$NiftiImageData3DDisplacement@M@sirf@@MEBAPEAV12@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z) referenced in function "public: class sirf::NonRigidTransformation<float> * __cdecl sirf::NiftiImageData3DDisplacement<float>::get_inverse_impl_nr(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_nr@?$NiftiImageData3DDisplacement@M@sirf@@QEBAPEAV?$NonRigidTransformation@M@2@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z)
10>sirf_inverse_transform.obj : error LNK2019: unresolved external symbol "protected: virtual class sirf::NiftiImageData3DDisplacement<float> * __cdecl sirf::NiftiImageData3DDisplacement<float>::get_inverse_impl_vtk(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_vtk@?$NiftiImageData3DDisplacement@M@sirf@@MEBAPEAV12@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z) referenced in function "public: class sirf::NonRigidTransformation<float> * __cdecl sirf::NiftiImageData3DDisplacement<float>::get_inverse_impl_vtk(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_vtk@?$NiftiImageData3DDisplacement@M@sirf@@QEBAPEAV?$NonRigidTransformation@M@2@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z)
```

**Comment by rijobro** [comment]
Have you successfully built the registration component on Windows before? 

The `get_inverse_impl_nr` and `get_inverse_impl_vtk` makes it look like it's linked to #657, but without a Windows machine, that's as close as I can get to figuring out what's wrong.

Do you have VTK on your Windows machine? I would only expect `get_inverse_impl_vtk` to get built if VTK is present. (It's not currently part of the SuperBuild, so it won't be built automatically.)

**Comment by KrisThielemans** [comment]
I have the opposite:
```
 -- One or more of the following components are missing: Registration, ISMRMRD and STIR (with ITK). Synergistic code will not be built.
11>  -- STIR not built with ITK.
11>  -- Either Registration or ISMRMRD or STIR (with ITK) have not been built.
...
C:\Users\krisf\Documents\devel\build-VC\SIRF-SuperBuild\sources\SIRF\src\Registration\cReg\NiftiImageData3DDeformation.cpp(118): error C2908: explicit specialization; 'sirf::NonRigidTransformation<dataType> *sirf::NiftiImageData3DDeformation<dataType>::get_inverse_impl_nr(const std::shared_ptr<const sirf::NiftiImageData<dataType>>) const' has already been instantiated [C:\Users\krisf\Documents\devel\build-VC\SIRF-SuperBuild\builds\SIRF\build\src\Registration\cReg\Reg.vcxproj]
...
C:\Users\krisf\Documents\devel\build-VC\SIRF-SuperBuild\sources\SIRF\src\Registration\cReg\NiftiImageData3DDeformation.cpp(153): error C2908: explicit specialization; 'sirf::NonRigidTransformation<dataType> *sirf::NiftiImageData3DDeformation<dataType>::get_inverse_impl_vtk(const std::shared_ptr<const sirf::NiftiImageData<dataType>>) const' has already been instantiated [C:\Users\krisf\Documents\devel\build-VC\SIRF-SuperBuild\builds\SIRF\build\src\Registration\cReg\Reg.vcxproj]
```
and same errors for `NiftiImageData3DDisplacement.cpp`.

This is with `USE_ITK=OFF` in the SuperBuild. Checking the SIRF CMakeCache.txt it has
```
VTK_DIR=VTK_DIR-NOTFOUND
```

**Comment by rijobro** [comment]
The VTK component is independent of the ITK component. So you could in theory have STIR with ITK and no VTK, or vice versa. It's really strange that you have `VTK_DIR=VTK_DIR-NOTFOUND`, yet `get_inverse_impl_vtk` is getting compiled.

**Comment by rijobro** [comment]
When you break the error message up, my understanding is that it can't build:
```
sirf::NiftiImageData3DDeformation<dataType>::get_inverse_impl_vtk
```
because it `has already been instantiated`:
```
C:\...\SIRF-SuperBuild\builds\SIRF\build\src\Registration\cReg\Reg.vcxproj]
```
The latter looks like the build directory to me. Very confusing, but I can't really help as I have no Windows experience.

**Comment by KrisThielemans** [comment]
[doc on error c2908](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2908?view=vs-2019) (not that it helps).

By the way the `.vcxproj` is the "project file" for VS (equivalent to a "Makefile").

**Comment by KrisThielemans** [comment]
> Do you have VTK on your Windows machine? I would only expect get_inverse_impl_vtk to get built if VTK is present. (It's not currently part of the SuperBuild, so it won't be built automatically.)

This statement is incorrect. `get_inverse_impl_vtk` always gets built, it just throws if VTI isn't found at configure-time. This is a bit confusing, but not the cause of this error.

**Comment by KrisThielemans** [comment]
I've tried many variations, but not with success. For instance, I've moved all implementations to the `.cpp`, in particular moving the implementation of `get_inverse` after the ones for `get_inverse_impl*`. I've also got rid of `get_inverse_impl_nr` in `NonRigidTransformation` and replaced it with a single `NonRigidTransformation* get_inverse_impl()`. This just pushed the problem to that function.

I have no idea therefore. The only thing that resolves it for me is to remove all `get_inverse*` functions from `NonRigidTransform`. Somewhat surprisingly, this doesn't seem to create problems elsewhere (still checking).

It's of course even weirder that I get an error about duplicates, while @evgueni-ovtchinnikov gets one about missing functions.

I wonder if this isn't a compiler bug. I'm using VS 2015 Community Edition. @evgueni-ovtchinnikov which version of VS do you use?

**Comment by rijobro** [comment]
Hi, two possible sources of the source of the error:

1. In https://github.com/SyneRBI/SIRF/pull/657, I used covariance (à la https://github.com/SyneRBI/SIRF/pull/277). I wonder if I did something wrong there, I'll have a check.
2. Could the problems be from multiple inheritance? Maybe things are being compiled in a funny order.

**Comment by KrisThielemans** [comment]
1. I can't see anything wrong in the code really, but that doesn't mean it isn't there of course.
2. You are using multiple inheritance but with `NiftiImageData3DTensor` which doesn't seem to be involved.

a mystery.

**Comment by rijobro** [comment]
> You are using multiple inheritance but with NiftiImageData3DTensor which doesn't seem to be involved.

Well `NiftiImageData3DDeformation` and `NiftiImageData3DDisplacement` inherit from `NiftiImageData3DTensor`, so they still both inherit from `DataContainer` and `Transformation`. I have no idea if this could cause a problem, just throwing ideas out there.

**Comment by KrisThielemans** [comment]
I've created a cut-down version of the code in an attempt to simplify things. https://github.com/KrisThielemans/VStest

Of course, with this one, VS is happy...

@evgueni-ovtchinnikov maybe you could try the VStest? If it works for you, could you try to beef it up until we reproduce the problem?

**Comment by KrisThielemans** [comment]
Confirmed that disabling all of this in `NonRigidTransform` (which then becomes an empty class) makes SIRF compile on VS. It's a bit ugly, but would allow us to move on. @rijobro, ok ? I can do a PR

**Comment by rijobro** [comment]
Should we put it inside of an `ifndef _WIN32`? That way, it's only commented out for windows.
