### ISSUE TITLE
travis fails due to libvtk7.dev

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#667]
#657 causes Travis failures [with](https://travis-ci.org/github/SyneRBI/SIRF/jobs/689973341#L1558)
```
E: Unable to locate package libvtk7-dev
```
Travis jobs seem all currently to be running with `xenial` which doesn't have that package.
https://packages.ubuntu.com/search?keywords=libvtk7-dev

I suggest to change default Travis Linux dist to `bionic` but keep 1 or 2 jobs on `xenial`. This is done in the SuperBuild as well. (search for `dist:`)

**Comment by rijobro** [comment]
Sorry, not sure how I didn't notice that one. PR incoming.
