### ISSUE TITLE
Reference vs Float image NiftyF3dSym

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF#670]
I noticed that when I do 

```
reg_alg = sirf.Reg.NiftyF3dSym()
reg_alg.set_reference_image(image1)
reg_alg.add_floating_image(image2)
reg_alg.process()
```

The text printed says that `image2` is being used as reference image and `image1` as floating image. 

Is this expected (i.e. sirf reference is different than NiftyReg reference) or is it a bug somewhere (maybe printing?)?.

**Comment by ALEXJAZZ008008** [comment]
I also see the same problems and have to manually flip it in my
applications. It is the other way around in Aladin
