### ISSUE TITLE
Loading a deformation to array, filling the deformation with the array and then writing it results in a change to the deformation

### ISSUE THREAD

**Issue by ALEXJAZZ008008** [SyneRBI/SIRF#672]
If I load a deformation field, convert it to array, fill a new deformation object loaded from the same file as the original deformation and then write the deformation again it does not result in the same deformation as the original deformation field.

Here is the code I used to test it:
~~~~
import sirf.Reg as reg


input_path = "/home/alex/Documents/jrmomo/run_momo/run_evaluation/temp/results/local_one_second_one_cycle_2D_tof_signal_test_fast/evaluation/reconstructed_static/DVF_1.nii"
output_path = "/home/alex/test_dvf.nii"

test_dvf_array = reg.NiftiImageData(input_path)
test_dvf_array = test_dvf_array.as_array()

test_dvf_object = reg.NiftiImageData(input_path)
test_dvf_object.fill(test_dvf_array)
test_dvf_object.write(output_path)
~~~~

Here is an example of the change to the volume:

![image](https://user-images.githubusercontent.com/27929624/82842585-04425c00-9ed2-11ea-84f3-7d1e4caaf4bd.png)

![image](https://user-images.githubusercontent.com/27929624/82842612-17edc280-9ed2-11ea-8c2e-4442448c7469.png)

Since seeing this issue I rebuilt SIRF which resulted in the following error when I tried to construct a NiftiImageData3DDeformation object:
~~~~
sirf.Utilities.error: ??? "'Trying to construct a NiftiImageData3DTensor.\\n\\t\\tExpected params: ndim = 5, nu = 3, nt = 1, intent_code = Vector\\n\\t\\tActual params:   ndim = 5, nu = 3, nt = 1, intent_code = None' exception caught at line 169 of /home/alex/Documents/new_SIRF-SuperBuild/SIRF-SuperBuild_build/sources/SIRF/src/Registration/cReg/cReg.cpp; the reconstruction engine output may provide more information"
~~~~

**Comment by rijobro** [comment]
Very strange. Does the problem still occur if you use one object (rather than filling to another)?

```
test_dvf = reg.NiftiImageData(input_path)
test_dvf_array = test_dvf.as_array()
test_dvf.fill(test_dvf_array)
test_dvf.write(output_path)
```

**Comment by rijobro** [comment]
Also, could you create a separate issue for the reader? I imagine they're unrelated.

**Comment by ALEXJAZZ008008** [comment]
I tested with the following code and had the same result:

~~~~
import sirf.Reg as reg


input_path = "/home/alex/Documents/jrmomo/run_momo/run_evaluation/temp/results/local_one_second_one_cycle_2D_tof_signal_test_fast/evaluation/reconstructed_static/DVF_1.nii"
output_path = "/home/alex/test_dvf.nii"

test_dvf_object = reg.NiftiImageData(input_path)
test_dvf_array = test_dvf_object.as_array()

test_dvf_object.fill(test_dvf_array)
test_dvf_object.write(output_path)
~~~~

**Comment by ALEXJAZZ008008** [comment]
I think the reader isn't an issue as such, it's because the intent code is not set in my DVFs, do you think it would be better to throw a warning rather than an exception in this circumstance? The data is the same and I know it is valid, it's just a flag

**Comment by KrisThielemans** [comment]
>  do you think it would be better to throw a warning rather than an exception in this circumstance? The data is the same and I know it is valid, it's just a flag

I'm afraid I prefer throwing an error. it prevents people doing the wrong thing. Possibly some flag could be used to change the error into a warning, but that seems hard to implement. Suggestions welcome... Unless of course very few people set the `intent_code`, in which case we'd have to revise this.

But this discussion doesn't belong in this issue of course, so if we continue it, please create a new issue.

**Comment by rijobro** [comment]
I've replicated the error myself. Seems not to occur with a scalar image, just with tensors. Implies I do something wrong with the order of indexing there. I'll fix it now. 

I remember making some modifications around the time of the last hackathon in Abbingdon, so I must have overlooked tensors. 

I've added some test cases, so shouldn't happen again once it's fixed.
