### ISSUE TITLE
Deformation vs Displacement field docs

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF#673]
I see that you can get both, and with a chat with @KrisThielemans seems that Deformation fields will have absolute locations of sampling points while Displacement fields will have relative ones.

I have not seen this documented anywhere in SIRF, maybe we should add it somewhere? Either the classes themselves or at least in the samples?

**Comment by rijobro** [comment]
Yes, something like this:
```
x' = def(x) = disp(x)+x
```
Would you be able to add in the documentation where you see fit? If it belongs in the classes, then it would be `NiftiImageData3DDeformation.h`, `NiftiImageData3DDisplacement.h`, and the corresponding classes in Matlab and Python.

**Comment by AnderBiguri** [comment]
@rijobro Sure I'll have a look. Maybe in the place where they are obtained/loaded/saved, somewhere easily accessible from the python side, getting into the C code for variable documentation seems too deep

**Comment by KrisThielemans** [comment]
Would need to be in .h as well. Not everybody is python or Matlab.

Alternatively could be in the userguide., Assuming that amidst actually reads it...

**Comment by rijobro** [comment]
@AnderBiguri thanks. I would put them in the class definitions, so 6 places in total (C++, M, P for each def, disp). User guide too would be good, since it can just be copied and pasted.
