### ISSUE TITLE
HDF CXX

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#685]
New CMake error when building on OSX:
```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find HDF5 (missing: CXX) (found suitable version "1.12.0",
  minimum required is "1.12.0")
```
I wonder if it could be related to https://github.com/UCL/STIR/pull/550? Just a guess.

**Comment by rijobro** [comment]
In hindsight, I guess it can't be related to UCL/STIR#550, since that's on `master` branch and I'm building on top of `release_4`...

**Comment by rijobro** [comment]
Problem also present on ubuntu.

**Comment by KrisThielemans** [comment]
building how?

likely cause https://github.com/SyneRBI/SIRF-SuperBuild/pull/402 (but the PR was green)

could have to do `find_package(HDF5 COMPONENTS C CXX)`, but weird you're getting this now

**Comment by rijobro** [comment]
> building how?

On both OSX and ubuntu, they are part of the superbuild, but I'm currently installing STIR and SIRF manually. i.e. `cd SB-build && cd builds/STIR/build && make -j install && cd ../../SIRF/build && make -j install`.

Disabling HDF5 support in STIR seems to have enabled both the OSX and ubuntu STIR & SIRF compilations to complete successfully.

**Comment by KrisThielemans** [comment]
hmm. something in the `STIRConfig.cmake` then. It'll do a `find_package(HDF5)` I guess.

**Comment by rijobro** [comment]
I think I use system HDF5 for both if that helps narrow it down.

**Comment by KrisThielemans** [comment]
i can't look at this now. What's in the `STIRConfig.cmake` in `STIR_DIRS`?

**Comment by rijobro** [comment]
Relevant bit in `STIRConfig.cmake` looks like this: 
```
if ()
  message(STATUS "HDF5 support in STIR enabled.")
  find_package(HDF5  COMPONENTS CXX REQUIRED)
  include_directories(${HDF5_INCLUDE_DIRS})

  set(STIR_BUILT_WITH_HDF5 TRUE)
endif()
```

**Comment by paskino** [comment]
The CMake error seems to imply that the version of HDF5 found is not suitable. What is the version found? Or I misunderstand?

Does it work if we build HDF5 as part of SuperBuild?

**Comment by KrisThielemans** [comment]
questions:
- do we currently disable STIR's HDF5 support by default in the SIRF-SuperBuild?
- I assume this is only with STIR post-release 4.0.x (i.e. after the merge of the Signa PR)?

If the answer is "yes" and "yes", there's no reason to delay 2.2 and go ahead with tagging

**Comment by KrisThielemans** [comment]
@rijobro can you run CMake with `-DHDF5_FIND_DEBUG=ON`? Post the CMake log as a file here

**Comment by rijobro** [comment]
> do we currently disable STIR's HDF5 support by default in the SIRF-SuperBuild?

Enabled by default: `option(STIR_DISABLE_HDF5_SUPPORT "Disable STIR use of HDF5 libraries" OFF)`. Happy to switch it to `ON`.

**Comment by KrisThielemans** [comment]
ok.  Please do that. there's nothing in SIRF currently that uses STIR's HDF5 support anyway.

I'm therefore postponing resolving this to 2.3. @evgueni-ovtchinnikov please tag SIRF but wait for the above for the SIRF-SuperBuild.

**Comment by evgueni-ovtchinnikov** [comment]
tagged SIRF

**Comment by evgueni-ovtchinnikov** [comment]
last tick in checklist section 2: we do not seem to have release candidates as Releases

**Comment by KrisThielemans** [comment]
This is due to a CMake `FindHDF5.cmake` bug, see https://gitlab.kitware.com/cmake/cmake/-/issues/20909

**Comment by KrisThielemans** [comment]
Addressed in STIR with a work-around the CMake problem, see https://github.com/UCL/STIR/issues/614.
