### ISSUE TITLE
virtual methods not working correctly when passing between wrapped (python) and C++

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#686]
I have the following code:
```
import sirf.STIR as pet
pet.AcquisitionData.set_storage_scheme('memory')
out = pet.AcquisitionData("sino.hs")
out.axpby(1,2,out)
```
The `axpby` goes to the method in `DataContainer`, in `SIRF.py`. That method then calls `cSIRF_axpby` in `csirf.cpp`. `DataHandles` are cast to `DataContainer`, and then the correct virtual implementation of `axpby` is chosen (e.g., `PETAcquisitionData`).

I know that `out` is `ProjDataInMemory`, and so should go to the virtual function there (`ProjDataInMemory::axpby`). However, it ends up in `ProjData::axpby`.

Whilst debugging, I do some casting:

```
template<class Type>
static
void
print_quick(const Type * obj, const std::string &var_name, const std::string &class_name)
{
    std::cout << var_name << " is " << class_name << "? " << (stir::is_null_ptr(obj) ? "No" : "Yes") << "\n";
}

void
PETAcquisitionData::axpby(
const void* ptr_a, const DataContainer& a_x,
const void* ptr_b, const DataContainer& a_y
)
{
    float a = *(float*)ptr_a;
    float b = *(float*)ptr_b;

    // Are they PETAcquisitionData?
    const PETAcquisitionData *x_temp = dynamic_cast<const PETAcquisitionData*>(&a_x);
    const PETAcquisitionData *y_temp = dynamic_cast<const PETAcquisitionData*>(&a_y);
    print_quick(x_temp, "x_temp", "PETAcquisitionData");
    print_quick(y_temp, "y_temp", "PETAcquisitionData");

    // Are they ProjData?
    const ProjData* x = x_temp->data().get();
    const ProjData* y = y_temp->data().get();
    print_quick(x, "x", "ProjData");
    print_quick(y, "y", "ProjData");

    // Are they ProjDataInMemory
    ProjDataInMemory* this_pdim = dynamic_cast<ProjDataInMemory*>(this->data().get());
    const ProjDataInMemory* x_pdim = dynamic_cast<const ProjDataInMemory*>(x);
    const ProjDataInMemory* y_pdim = dynamic_cast<const ProjDataInMemory*>(y);

    print_quick(this_pdim, "this_pdim", "ProjDataInMemory");
    print_quick(x_pdim, "x_pdim", "ProjDataInMemory");
    print_quick(y_pdim, "y_pdim", "ProjDataInMemory");
```
Worryingly, I get the following output:
```
x_temp is PETAcquisitionData? Yes
y_temp is PETAcquisitionData? Yes
x is ProjData? Yes
y is ProjData? Yes
this_pdim is ProjDataInMemory? Yes
x_pdim is ProjDataInMemory? No
y_pdim is ProjDataInMemory? No
```
If I do in place `axpby` from python, I get the following output:
```
x_temp is PETAcquisitionData? Yes
y_temp is PETAcquisitionData? Yes
x is ProjData? Yes
y is ProjData? Yes
this_pdim is ProjDataInMemory? No
x_pdim is ProjDataInMemory? No
y_pdim is ProjDataInMemory? No
```
I noticed this a long time ago, but sidestepped it by using strings to tell me what to cast to:

https://github.com/SyneRBI/SIRF/blob/8df41e4e6d3248dd889159271b2e5339c5728812/src/Registration/cReg/cReg.cpp#L556-L570

**Comment by rijobro** [comment]
Interestingly, they successfully cast to `ProjDataFromStream`, but not `ProjDataInMemory`:
```
x_temp is PETAcquisitionData? Yes
y_temp is PETAcquisitionData? Yes
x is ProjData? Yes
y is ProjData? Yes
this_pdim is ProjDataInMemory? No
x_pdim is ProjDataInMemory? No
y_pdim is ProjDataInMemory? No
```
This is despite the fact that the constructor inside of `PETAcquisitionDataInMemory` creates a `ProjDataInMemory`:
```
_data = stir::shared_ptr<stir::ProjData>
                          (new stir::ProjDataInMemory(MAKE_SHARED<stir::ExamInfo>(*sptr_exam_info), sptr_proj_data_info));
```

**Comment by rijobro** [comment]
Ah, I'm starting to get somewhere. The constructor for `PETAcquisitionData` in python creates a `PETAcquisitionDataInFile` on the C++ level, which creates a `ProjDataFromStream`, not a `ProjDataInMemory`.

Still not sure how to fix my problem though, suppose I would need to get SIRF to convert the `ProjDataFromStream` to `ProjDataInMemory`.

**Comment by rijobro** [comment]
I realise now that there is a constructor for `ProjDataInMemory` that takes a `ProjData` as argument so I suppose that's what I need!

**Comment by KrisThielemans** [comment]
> The constructor for PETAcquisitionData in python creates a PETAcquisitionDataInFile on the C++ level, which creates a ProjDataFromStream, not a ProjDataInMemory.

but this should depend on the flag "in memory"?

>  suppose I would need to get SIRF to convert the ProjDataFromStream to ProjDataInMemory.

but not always.

this needs @evgueni-ovtchinnikov

**Comment by rijobro** [comment]
Sorry, it turns out the name of this issue is incorrect.

@evgueni-ovtchinnikov PR #688 gives the functionality I desire (sinos are now stored as `ProjDataInMemory` if `storage_scheme==memory`). Is it OK with you?

**Comment by evgueni-ovtchinnikov** [comment]
PR #688 looks ok to me
