### ISSUE TITLE
No checks on non-master PRs

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#695]
I wanted to create a `v3.0` branch and push changes that would break backwards compatibility there. However, it seems that Travis and Codacy don't work in this case. See here: https://github.com/SyneRBI/SIRF/pull/694.

Any thoughts?

**Comment by KrisThielemans** [comment]
you need to go into Travis And Codacy settings for the repo, and enable that branch there. We've disabled checks on all branches except a few, as otherwise we have double runs (for the PR and for the branch). Arguably it would be better to push branches to another clone, and only work via PRs, but fine.

**Comment by rijobro** [comment]
Thanks, managed to turn Codacy on, but not sure about Travis. From the Travis [docs](https://docs.travis-ci.com/user/pull-requests/):

> To only build pull requests targeting specific branches you can use the branches: only: key, which will also restrict the branches that trigger builds.

We have `Build Pushed Pull Requests` to `ON`, and don't use the `branches: only` command in our `.travis.yml`. So as far as I can tell, it seems that Travis should build **all** PRs (but doesn't).

**Comment by KrisThielemans** [comment]
correct. I see the requests at https://travis-ci.org/github/SyneRBI/SIRF/requests

I see the branch at
https://travis-ci.org/github/SyneRBI/SIRF/branches
but they say "cancelled". not by me...

**Comment by rijobro** [comment]
I cancelled the v3.0 ones, because they were trying to build the `v3.0` branch, which is currently identical to `master`. The one that I want but is missing from the requests is https://github.com/SyneRBI/SIRF/pull/694, which is a PR to `v3.0`.

**Comment by rijobro** [comment]
My fault! The most recent commit contained `[ci skip]`, so the whole thing never got built.
