### ISSUE TITLE
SIRF will no longer build with STIR master

### ISSUE THREAD

**Issue by ALEXJAZZ008008** [SyneRBI/SIRF#718]
If you try you get multiple of the following error with minor variations:

~~~~
SIRF/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h:494:33: error: ‘class stir::ProjDataInMemory’ has no member named ‘begin’
             auto iter = pd_ptr->begin();
~~~~

**Comment by ALEXJAZZ008008** [comment]
After building with other versions of STIR this is also true of 4 and 4.0.2
It's also true of the TOF branch

**Comment by KrisThielemans** [comment]
To the best of my knowledge, SIRF and STIR master together do build.
https://travis-ci.org/github/SyneRBI/SIRF is green.

https://github.com/UCL/STIR/pull/558 introduced `stir::ProjDataInMemory::begin()`.

This is indeed on `master` only and not on any of the other branches.

So I don't think you're on STIR `master` now.

**Comment by rijobro** [comment]
> This is indeed on master only and not on any of the other branches.

Also on the `release_4` branch. So just to add to Kris' comment, you'll have to merge STIR `master`/`release_4` into your TOF flight to be able to use SIRF master.

We thought about making current SIRF compatible with older STIR code, but it would result in too many `ifdef`'s.

**Comment by KrisThielemans** [comment]
Given that Travis is fine etc, I suspect that this was due to the problem of finding an out-of-date STIR https://github.com/SyneRBI/SIRF-SuperBuild/issues/414

Feel free to re-open if you disagree
