### ISSUE TITLE
FBP2DReconstructor setup

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#732]
With STIR on master, demo script `fbp2d_reconstruction.py` fails because `set_up` is not called.

In STIR, `FBP2DReconstruction::set_up()` requires an image to be passed to it - where would `fbp2d_reconstruction.py` get that image from?

Adding
```
    image = acq_data.create_uniform_image()
    recon.set_up(image)
```
in `fbp2d_reconstruction.py` does not help - the same error message is issued:
```
ERROR: Reconstruction method called without calling set_up first.
```

**Comment by evgueni-ovtchinnikov** [comment]
forgot to mention: this happens on Windows 10

probably something went wrong with the SIRF or STIR build

**Comment by KrisThielemans** [comment]
one possibly cause was a bug in STIR, fixed here
https://github.com/UCL/STIR/commit/f136283a45f2ea9f961d2d9f1c65383996a86e49#diff-b877aaa82273b772d4a204e76ccc8f73
so your STIR is probably out-of-date.

I'll close this therefore. Do reopen if it still happens.
