### ISSUE TITLE
travis badge shows error despite master being green

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#735]
If you scroll to the bottom of our repository homepage, the Travis badge is grey and says "error". However, when you go to the badge's link: https://travis-ci.org/SyneRBI/SIRF.svg?branch=master, it's green (at the time of writing). Any idea what's going wrong? I updated them from CCPPETMR to SyneRBI recently, so may have made a mistake there but I can't see where. 

Same problem in SuperBuild. 

@casperdcl?

**Comment by rijobro** [comment]
Think it's just the caching of my browser, sorry. https://stackoverflow.com/a/50757046/12411867.

**Comment by casperdcl** [comment]
Refreshing browser cache may help. Sometimes it takes time for badges to update though. Yesterday all badges worldwide were grey & displaying 'inaccessible' for some time
