### ISSUE TITLE
STIR: Print scanner names

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#742]
I just tried to create a D690, with `pet.AcquisitionData('D690')`, which didn't work. I tried `Discovery690`, again that didn't work. I went through the STIR source code and found it should be `Discovery 690`. If there was a `print_all_scanner_names` method, this would have been a bit simpler.

**Comment by KrisThielemans** [comment]
can use [`stir::Scanner::get_all_names()`](https://github.com/UCL/STIR/blob/7ad42836e6d813313b8f2f5a83f8c6d3e04a47fb/src/include/stir/Scanner.h#L173). Note that it's better to return a list than call `print` in my opinion.

(not urgent)
