### ISSUE TITLE
New signature for axpby in Python

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#748]
> The proposal is to make `axpby` a static method of `DataContainer` with the following signature which will give us the full flexibility in the method
> 
> ```python
> @staticmethod
> def axpby(a,x,b,y,out=None):
>    ...
> ```

Please have a look at https://github.com/vais-ral/CCPi-Framework/issues/613

**Comment by paskino** [comment]
After some experimenting I came to [this ](https://github.com/vais-ral/CCPi-Framework/issues/613#issuecomment-653378263)conclusion.

**Comment by KrisThielemans** [comment]
conclusion in https://github.com/UCL/STIR/issues/560

This will need a sequence of steps.

**Comment by KrisThielemans** [comment]
@gfardell I think this can be closed?
