### ISSUE TITLE
unnecessary python try except?

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#751]
The following lines are a nuisance when debugging:

https://github.com/SyneRBI/SIRF/blob/5c94127357399a3b528095a7644f75ab0614c6d7/src/common/SIRF.py#L39-L42

Do we need them? Can't see `input` used anywhere in the file.

**Comment by evgueni-ovtchinnikov** [comment]
@rijobro: I had to put this so that `input` worked in the same way in both Python 2 and 3 - not needed now that we no longer support Python 2.

**Comment by rijobro** [comment]
Ok, well if it helps for python2 support (even if we don't officially support it), we can leave it as it is for now. I'll close the issue.

Just in case someone looks at this in the future, the same `try`/`catch` is also present in `STIR.py.in`.
