### ISSUE TITLE
SIRF requires STIR version 4

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#758]
SIRF requires STIR version 4: 

https://github.com/SyneRBI/SIRF/blob/master/src/CMakeLists.txt#L81

However, it seems the most recent tag of STIR is v5_alpha, causing Travis to fail:

https://travis-ci.org/github/SyneRBI/SIRF/jobs/705373915#L25459-L25465

My understanding is that `find_package` only allows more recent minor and tweak versions. So if major version changes, it won't be happy. Simplest answer I can think of is to do:

```
find_package(STIR REQUIRED)
if (stir version not greater than 4)
    message(FATAL_ERROR "SIRF requires STIR version greater than 4")
endif()
```

Does this sound correct @KrisThielemans?

**Comment by rijobro** [comment]
Alternatively, perhaps the error is because the version number is no longer numerical?

https://github.com/UCL/STIR/blob/fa10cd3cac20bf858287f9a06b602b1a51e1ee97/CMakeLists.txt#L63-L69

Not sure, just some ideas.

**Comment by KrisThielemans** [comment]
ah. apologies. I thought I'd simplify things, and made them harder.

It's up to the package distributor what they mean with versions, but STIR uses a default scheme, that will presumably indeed refuse a more recent major version (makes sense: it's not backwards compatible!).

I think we can indeed do
```
find_package(STIR REQUIRED)
if (STIR_VERSION  VERSION_LESS 4.0)
    message(FATAL_ERROR "SIRF requires STIR version greater than 4")
endif()
```
we can then use in places where needed an `ifdef` or whatever on the version (in C++, `STIR_VERSION` exists as well, see https://github.com/UCL/STIR/blob/fa10cd3cac20bf858287f9a06b602b1a51e1ee97/src/cmake/STIRConfig.h.in#L36)

**Comment by KrisThielemans** [comment]
> perhaps the error is because the version number is no longer numerical?

https://cmake.org/cmake/help/v3.18/command/if.html says
> Any non-integer version component or non-integer trailing part of a version component effectively truncates the string at that point.

which is why I felt safe to append the "pre" stuff. (at least, we could check if we're only an alpha or not)
