### ISSUE TITLE
New SIRF build failures

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#773]
My latest SIRF build failed with these errors:
```
CMake Error at src/CMakeLists.txt:81 (find_package):

Could not find a configuration file for package "STIR" that is compatible

  with requested version "4.0.0".
```
(Linux/OSX) and
```
Collecting docopt>=0.6.1

  Downloading docopt-0.6.2.tar.gz (25 kB)

    ERROR: Error [Errno 2] No such file or directory: '/usr/local/opt/python/bin/python3.7': '/usr/local/opt/python/bin/python3.7' while executing command python setup.py egg_info

ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/usr/local/opt/python/bin/python3.7': '/usr/local/opt/python/bin/python3.7'
```
(OSX).

Both two Xenial builds, one Bionic build and two OSX builds went ok.

Any ideas anyone?

**Comment by KrisThielemans** [comment]
I think the first thing should be fixed with #769 (merged just recently), and was caused by myself, and the second with #771 (under testing, but I see already a failure on OSX), which is our attempt to get round trouble 'brew' ing...

sorry about that.

**Comment by rijobro** [comment]
@evgueni-ovtchinnikov can you close this if master is working for you?

**Comment by evgueni-ovtchinnikov** [comment]
Travis is green after merging master, so closing
