### ISSUE TITLE
STIR python fill methods return self

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#779]
Not a big problem, but our STIR `fill` methods (image and acq data) have `return self` at the end. This means that if I do
```
im.fill(array)
```
then I get the following output `<sirf.STIR.ImageData at 0x7f79b62a9438>`. 

Don't think we should be returning anything since we're modifying `self`.

**Comment by paskino** [comment]
That's interesting. It may turn useful if we would allow such type of coding

```python

a.fill(ndarray).max()
```

**Comment by evgueni-ovtchinnikov** [comment]
I find returning self handy too.
