### ISSUE TITLE
Used to install Niftymomo headers

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#783]
We used to install the NiftyMoMo headers. As of https://github.com/SyneRBI/SIRF/pull/776 we no longer do that, but obviously any pre-installed files will still be there. Some updates to the NiftyMoMo functionality were added in https://github.com/SyneRBI/SIRF/pull/777. Therefore, there may be an issue where your compiler picks up the old `.h` when trying to compile the new `.cpp`. The simple solution if you get this error is to simply delete the old headers: `<SB_install_location>/include/sirf/NiftyMoMo`.

**Comment by rijobro** [comment]
@KrisThielemans is there any way to prepend the header files so that it finds the ones in the source directory ahead of those in the install location?

**Comment by KrisThielemans** [comment]
we had the same problem in STIR. we played around with `target_include_directories` and `BEFORE` etc, see [the manual](https://cmake.org/cmake/help/latest/command/target_include_directories.html). It's tricky in general as SIRF dependencies might not be playing nicely. I would certainly have hoped that SIRF goes and looks for include files in `SIRF/..include/ first, before anything else. If it doesn't, that'd be a bug.
