### ISSUE TITLE
STIR.AcquisitionModelUsingRayTracingMatrix.get_matrix returns a new matrix with default settings

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#794]
https://github.com/SyneRBI/SIRF/blob/b63149f3a9163b9e82b76e6e649e00774cde45e7/src/xSTIR/pSTIR/STIR.py#L1636
just creates a new matrix. Any previous settings are therefore ignored, which seems a bug to me. 

Moreover, it will have memory consequences as any caching will now be done twice. It's less easy to see what to do with this. If we'd return a handle to the same matrix, it could be surprising for people who want to use this matrix to project images/data of different sizes. However, the name implies to me that it's the same matrix. (otherwise, it'd have to be called `get_matrix_clone()` or so)

Do we use this function?

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans: that line simply creates an empty object of type `RayTracingMatrix`, which gets filled with the data (`DataHandle` wrap of `((ProjectorPairUsingMatrix*)this->sptr_projectors_.get())->get_proj_matrix_sptr()`) in the next line.
