### ISSUE TITLE
ImageData has no method max

### ISSUE THREAD

**Issue by ClaireDelplancke** [SyneRBI/SIRF#797]
CIL's  [MixedL21Norm convex conjugate](https://github.com/vais-ral/CCPi-Framework/blob/master/Wrappers/Python/ccpi/optimisation/functions/MixedL21Norm.py#L77) expects `x.max()` to give the element-wise maximum of `x`, but if `x` is of ImageData type, it has no method max.

**Comment by KrisThielemans** [comment]
STIR has `find_max()` and `find_min()`. Not sure about ISMRMRD. Of course, if we store only complex images, that wouldn't mean anything anyway.

@ClaireDelplancke does it actually need `max_abs` (i.e. max of absolute values)?

**Comment by ClaireDelplancke** [comment]
ImageData has complex values by default?
In CIL's [MixedL21Norm.convex_conjugate](https://github.com/vais-ral/CCPi-Framework/blob/master/Wrappers/Python/ccpi/optimisation/functions/MixedL21Norm.py#L55), we want to take the element-wise maximum of an image which is real and non-negative (so in that case, max and max of absolute values are the same.)

**Comment by paskino** [comment]
you could quickly fix this one by adding to `sirf.DataContainer`.

```python

def max(self):
    return numpy.max(self.as_array())
```

This means that we need to check that the methods in CIL and SIRF `DataContainer` are matching., @gfardell @epapoutsellis

**Comment by KrisThielemans** [comment]
`CIL.BlockDataContainer` has [maximum()](https://github.com/vais-ral/CCPi-Framework/blob/825d0e80a1e61062d121756649fc08ec0b06baab/Wrappers/Python/ccpi/framework/BlockDataContainer.py#L195] but no `max()`. That's probably doing something else though. I can't understand it from the doc. A CIL issue?

**Comment by KrisThielemans** [comment]
In C++, we could provide a default implementation in terms of `std::max_element` and iterators, but overload it for those where the engine provides its own implementation.

I guess it should throw if the underlying type is `complex`

**Comment by ClaireDelplancke** [comment]
@KrisThielemans `x.maximum(y)` gives the array which is the element-wise maximum of x and y, in CIL as well as in SIRF.

The implementation of `max()` in CIL is for `CIL.DataContainer` [here](https://github.com/vais-ral/CCPi-Framework/blob/master/Wrappers/Python/ccpi/framework/framework.py#L1085), I don't think it's needed in `CIL.BlockDataContainer`.
