### ISSUE TITLE
Division of a BlockDataContainer of ImageData by a non-zero scalar gives NaN pixels

### ISSUE THREAD

**Issue by ClaireDelplancke** [SyneRBI/SIRF#799]
I believe this is related to Issue #798 but would like to flag it independently in case it's not.

If I define a `CIL.BlockDataContainer` made of `sirf.ImageData` blocks and divide it by a non-zero scalar, some (but not all) pixels are put to NaN.

```python
ImageData = am.domain_geometry()
ImageDatax3 = BlockGeometry(*[ImageData for _ in range(3) ] )
imagex3 = ImageDatax3.allocate('random')
sigma = 1.

print('Image has shape {}, that is {} pixels'.format(imagex3[0].as_array().shape, imagex3[0].as_array().size))

for image in imagex3 / sigma:

    print('New image has shape {}, that is {} pixels'.format(image.as_array().shape, image.as_array().size))
    print('Out of these, {} pixels are NaN'.format(np.isnan(image.as_array()).sum()))
```

outputs

```python
Image has shape (127, 127, 127), that is 2048383 pixels
New image has shape (127, 127, 127), that is 2048383 pixels
Out of these, 2722 pixels are NaN
New image has shape (127, 127, 127), that is 2048383 pixels
Out of these, 2722 pixels are NaN
New image has shape (127, 127, 127), that is 2048383 pixels
Out of these, 2722 pixels are NaN
```

**Comment by KrisThielemans** [comment]
weird. might be easiest to figure out if we have non-random images. As the number of NaNs is non-random, it is likely that there's some structure here?

**Comment by ClaireDelplancke** [comment]
It's the same thing when taking an image constant equal to one or zero, but with a slightly different number of pixels. 

Each time I restart the kernel the number of NaN pixels slightly changes, and the location of such pixels change, even for a constant image. In pictures:
![Unknown-4](https://user-images.githubusercontent.com/52972039/91305599-8da44b80-e7ab-11ea-98bb-06db0ce5ad83.png)

![Unknown-3](https://user-images.githubusercontent.com/52972039/91305510-6e0d2300-e7ab-11ea-8e93-944dd3ec6aaa.png)

**Comment by KrisThielemans** [comment]
entirely weird.  And I presume that the division works ok on a SIRFDataContainer?

**Comment by ClaireDelplancke** [comment]
Yes it does (at least on ImageData.)

**Comment by KrisThielemans** [comment]
@paskino @gfardell over to you then...

**Comment by paskino** [comment]
Yes, @gfardell and I'll pick it up. Will require the fix discussed in #800.

**Comment by paskino** [comment]
Using the following

```python
import numpy
from numpy.linalg import norm
import os
import sys
import shutil
import unittest
from ccpi.framework import BlockDataContainer
import sirf.STIR as pet
from sirf.Utilities import  examples_data_path


def test_divide():
    os.chdir(examples_data_path('PET'))
    # Copy files to a working folder and change directory to where these files are.
    # We do this to avoid cluttering your SIRF files. This way, you can delete 
    # working_folder and start from scratch.
    shutil.rmtree('working_folder/brain',True)
    shutil.copytree('brain','working_folder/brain')
    os.chdir('working_folder/brain')

    cwd = os.getcwd()
    
    image1 = pet.ImageData('emission.hv')
    image2 = pet.ImageData('emission.hv')
    image1.fill(1.)
    image2.fill(2.)
    print (image1.shape, image2.shape)
    
    tmp = image1.divide(1.)
    numpy.testing.assert_array_equal(image1.as_array(), tmp.as_array())
    tmp = image2.divide(1.)
    numpy.testing.assert_array_equal(image2.as_array(), tmp.as_array())
    

    # image.fill(1.)
    bdc = BlockDataContainer(image1, image2)
    bdc1 = bdc.divide(1.)

    shutil.rmtree(cwd)

if __name__ == '__main__':
    test_divide()
```

fails at `tmp = image1.divide(1.)`. It is a SIRF error.

The cause is [this](https://github.com/SyneRBI/SIRF/blob/master/src/common/SIRF.py#L152) line where we use 
`tmp = other + numpy.zeros_like(self.as_array().shape)` aiming at initialising a numpy array with the shape of the `self` DataContainer but we end up allocating it of shape `(3,)`.

Substituting with `tmp = other + numpy.zeros_like(self.as_array())` solves the issue. This must be done with other algebra methods.

**Comment by evgueni-ovtchinnikov** [comment]
have you tried `tmp = other + numpy.zeros(self.dimensions())`?

**Comment by paskino** [comment]
I preferred `zeros_like` because that will make an array of the proper shape/type. `zero` will make one of type `numpy.float64` which may not be what we want or need.

Is there a way to infer what type we may need? I suppose the only types we support are `numpy.float32` or `numpy.complex`?

**Comment by evgueni-ovtchinnikov** [comment]
I suggest we add method `dtype` (with `@property` decorator) to `ImageData` and `AcquisitionData` classes, returning `numpy.float32` for PET data, `numpy.complex64` for MR acquisitions and one of the two depending on `is_real` for MR images

using `as_array` just to determine data shape and type is a bit wasteful, is it not?

**Comment by paskino** [comment]
@evgueni-ovtchinnikov, the method `dimensions` doesn't exist in Gadgetron `ImageData`.

**Comment by paskino** [comment]
Unfortunately I have a build error

```

/home/ofn77899/devel/buildVM/sources/SIRF/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h:617:36: error: ‘class stir::ProjDataInMemory’ has no member named ‘end’
             while (iter != pd_ptr->end())
```

Any idea?

**Comment by evgueni-ovtchinnikov** [comment]
you must be using old versions SIRF and STIR - my `Gadgetron.ImageData` does have `dimensions()` and Visual C++ finds `pd_ptr->end()`

**Comment by paskino** [comment]
STIR is stir_rel_4_00_alpha
SIRF is [update_algebra_python ](https://github.com/SyneRBI/SIRF/tree/update_algebra_python)which is just branched from master

**Comment by evgueni-ovtchinnikov** [comment]
`pd_ptr->end()` is the latest stuff from Richard, it only works on STIR master, I believe.

I checked SIRF master on GitHub, and I see `def dimensions()` on line 348 of `Gadgetron.py`.

**Comment by KrisThielemans** [comment]
Please don't use `stir_rel_4_00_alpha` anymore. use the `release_4` branch. we need it for other stuff in SIRF anyway. If we jump to STIR `master` it creates a bit too high pressure on me for releasing STIR 5...

**Comment by paskino** [comment]
@evgueni-ovtchinnikov yes, you are right `dimensions` exists.
@KrisThielemans I'll use STIR `release_4` branch

**Comment by paskino** [comment]
`release_4` did the trick

**Comment by paskino** [comment]
Tests are added to the SuperBuild here https://github.com/SyneRBI/SIRF-SuperBuild/pull/437
