### ISSUE TITLE
AcquisitionModel is missing the method norm

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#804]
Using CIL minimisation algorithms, oftentimes it is required to calculate the norm of an operator, e.g. in setting up PDHG, the 2 step sizes must be `sigma * tau < (1/operator.norm())**2`.

In CIL, for `LinearOperator` we use the [`PowerMethod`](https://github.com/vais-ral/CCPi-Framework/blob/17d56766525c569b2ebe4a692067bb945311c9f2/Wrappers/Python/ccpi/optimisation/operators/Operator.py#L118), which is an iterative method. `PowerMethod` is a static method of `LinearOperator` and it will work with SIRF `AcquisitionModel`s. 

We cannot add a method using `LinearOperator.PowerMethod` from CIL as this will add a strong dependence on CIL. 

We could copy the `PowerMethod` to SIRF at the Python level to start with.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov can this be closed since you merged #811?

**Comment by evgueni-ovtchinnikov** [comment]
yes it can now, closing...
