### ISSUE TITLE
Add Gadgetron libs to target_link_libraries of cgadgetron

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#805]
Add consistently to cgadgetron CMakeList.txt lines to be able to link with the following libraries, avoiding hard coding of location etc.

```
set( GT_TOOLBOX_CPUCORE "/home/sirfuser/devel/install/lib/libgadgetron_toolbox_cpucore.so") 
set( GT_TOOLBOX_CPUFFT  "/home/sirfuser/devel/install/lib/libgadgetron_toolbox_cpufft.so") 
set( GT_TOOLBOX_CPUNFFT "/home/sirfuser/devel/install/lib/libgadgetron_toolbox_cpunfft.so") 
set( GT_TOOLBOX_LOG     "/home/sirfuser/devel/install/lib/libgadgetron_toolbox_log.so") 


set(GT_LIBS ${GT_LIBS} ${GT_TOOLBOX_CPUCORE}) 
set(GT_LIBS ${GT_LIBS} ${GT_TOOLBOX_CPUFFT}) 
set(GT_LIBS ${GT_LIBS} ${GT_TOOLBOX_CPUNFFT}) 
set(GT_LIBS ${GT_LIBS} ${GT_TOOLBOX_LOG}) 

target_link_libraries(cgadgetron ${GT_LIBS}) 
```

**Comment by KrisThielemans** [comment]
a PR to @johannesmayer 's branch please, NOT  SIRF master. This needs to be put within suitable safe-guards. If I cannot find them, we should be able to disable it, together with the new functionality. I think Richard helped with that already.

**Comment by paskino** [comment]
Yes, sure, that was my aim.

**Comment by johannesmayer** [comment]
this has happened on my RPE branch now. 
should we close this one here then?
