### ISSUE TITLE
DataContainer operators that consider the geometry

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF#822]
Would it make sense to try to have operations that consider the geometry when being applied?

Say having `image_data1` and `image_data2`. Nowadays we can do `image_data1*image_data2` as long as both are the same size, as the code will take the arrays and elemetwise multiply them. 
However, what if the geometries are different? Not only the size of the array, but offsets etc. It could be useful (it is def for me) to be able to do these operations anyway, in a similar manner that we can combine transformations together even if they are of a different type (displacement, deformation, affine, etc)

Certainly there would need to be some parameters/defaults of  stuff like interpolation/boundaries/cropping that would need to be thought with a bit of detail.

**Comment by AnderBiguri** [comment]
PD: I am trying to mask a DVF with an ImageData of different size, and there seems to be no trivial way of doing it, other than re-coding the geometric positioning myself to be able to interpolate the mask to the DVF geometry metadata.

**Comment by KrisThielemans** [comment]
I'd hesitate to hide this kind of stuff behind `operator+` or whatever. If the user wants to add images from different bed-positions, times, motion states etc, then she needs to know what to do and be warned when inadvertently doing the wrong thing (it seems hard/impossible to discover from the data exactly what needs to be done).

however, of course it'd be useful to have functionality that helps/does this.

I can see for instance that you'd want to be able to construct an image that overlaps with both input images (for 2 bed positions). However, even then adding is non-trivial (as there will be some overlap, and you will want to apply weighting). (Note, @danieldeidda has a branch with merging of bed positions for PET). It's more or less impossible to do this without knowing a lot...

From your second comment, I can see you want to multiply a DVF with a mask, but that in itself is quite a specific operation (useful in our context but not anywhere else?). Generalising that to other cases where these data have different sizes seems tricky.

Summary: we should be able to do it,  but I don't see a way to come up with a generic function that will be safe/useful.

**Comment by AnderBiguri** [comment]
I 100% agree that this should not bee easily accessible if it would exist, it should be hidden under some non-misleading function names etc, I'd also would not overload the operators themselves. 

Of course Daniels code came into mind, and I understand that some non-trivial additions is being made there.
You are correct that this would go into "advanced/specific" use of SIRF, but we should allow advanced use! Otherwise we force users not to innovate, I suppose. 

I can also think of an easier and less-confusing alternative: make a function that converts from one geometry to the other (of course, not only metadata, but also pixel values). That ensures that the standard operations would work, but also that no one will accidentally use it, as you are explicitly calling the function. What do you think?

**Comment by KrisThielemans** [comment]
not sure. too woolly to me 😉 . We have the resample stuff. what else are you thinking of?

**Comment by AnderBiguri** [comment]
What do you mean we have the resample stuff? 

What I mean is that if I have `dc1` and `dc2` `DataContainer` objects, with arbitrary geometry information (offsets, pixel sizes etc), I'd like to be able to do maths with them, without me needing to code the geometry trasnforms between pixels. That would need interpolation, translations and trimming/filling, to convert one into the other space, so then I can e.g. add, multiply etc. 

The resampler does not give me an image changed to the float domain, as far as I can see, but maybe I am missing something. 

        mask.get_geometrical_info().print_info()
        dvf.get_geometrical_info().print_info()


        dvf_arr=dvf.as_array()
        res_tenplate=stir.ImageData()
        res_tenplate.initialise((dvf_arr.shape[2],dvf_arr.shape[1],dvf_arr.shape[0]))
        res_tenplate.fill(dvf_arr[:,:,:,0,0])

        resampler = reg.NiftyResample() 
        resampler.set_interpolation_type_to_linear()
        resampler.set_reference_image(res_tenplate)
        resampler.set_floating_image(mask)
        resampler.process()
        
        resampled_mask=resampler.get_output()
        resampled_mask.get_geometrical_info().print_info()

prints the following shapes. for my particular example. The last one, the resampled output, is not in the "image domain" as any of the two I have as input!

```
Offset: (-564.316, -564.316, -0)
Spacing: (2.206, 2.206, 2.76148)
Size: (512, 512, 411)
Dir mat: 
1, 0, 0
0, 1, 0
0, 0, -1

Offset: (0, 0, 0)
Spacing: (2.73438, 2.73438, 2.79999)
Size: (256, 256, 409)
Dir mat: 
-1, 0, 0
0, -1, 0
0, 0, 1


No transformations set, using identity.
Offset: (-128, -128, -0)
Spacing: (1, 1, 1)
Size: (256, 256, 409)
Dir mat: 
1, 0, 0
0, 1, 0
0, 0, -1
```

**Comment by AnderBiguri** [comment]
Clearly my example was wrong, should have been

        res_tenplate.initialise((dvf_arr.shape[2],dvf_arr.shape[1],dvf_arr.shape[0]),  intra_patient_dvf[-1].get_geometrical_info().get_spacing(),  intra_patient_dvf[-1].get_geometrical_info().get_offset())


Will check if that does what I want for my particular problem, and if it does, I guess I'll close this suggestion, as doesn't seem that you like it too much :D .

If the resampling works however, it may still be useful to wrap it as a function in the Reg part.

**Comment by AnderBiguri** [comment]
Resampling works well

**Comment by KrisThielemans** [comment]
> ```
> res_tenplate.initialise((dvf_arr.shape[2],dvf_arr.shape[1],dvf_arr.shape[0]),  intra_patient_dvf...)
> ```

Can you confirm you needed the `shape` arguments in that order? This should not be the case. Related is https://github.com/SyneRBI/SIRF/issues/791

I think we need a constructor (and `initialise`) that just takes a `GeometricalInfo` object, as it has all it needs. Please create an issue for that as well.

**Comment by AnderBiguri** [comment]
@KrisThielemans problem is, DVFs are XYZMN dimensions (M=1,N=2) while ImageData is ZYX. I don't think that is necesarily a bug, just an inconsistency between the convention in SIRF.

**Comment by AnderBiguri** [comment]
Also, I have opened the issue, but I guess there is a way to do it now, which is to clone an object. My issues are because one is a DVF, the other one an image.

**Comment by KrisThielemans** [comment]
> @KrisThielemans problem is, DVFs are XYZMN dimensions (M=1,N=2) while ImageData is ZYX. I don't think that is necesarily a bug, just an inconsistency between the convention in SIRF.

Is this true? If you have `NiftiImageData`, and you register them, does the `NiftiDeformationField` have different shape? Probably not. (of course, all bets are of with mixing `STIRImageData` in the game, as that has a fixed orientation, while `Nifti` doesn't)

**Comment by AnderBiguri** [comment]
It was indeed a STIRImageData, not a Nifti one, as created my mask from CT images.
