### ISSUE TITLE
Ability to modify NiftiImageData metadata

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF#830]
It would be useful to be able to modify some of the metadata stored in `NiftiImageData`. 

Similar to `nifti_tool -mod_hdr  [-mod_field FIELDNAME NEW_VAL] [...] -infiles f1` [here](https://afni.nimh.nih.gov/pub/dist/doc/program_help/nifti_tool.html).

You'd potentially need to update linked metadata, such as the `geometrical_info` class, or if you modify `qto_ijk`, you'd need to also modify `qto_xyz`, etc.

**Comment by KrisThielemans** [comment]
I think we should leave this to dedicated nifti tools such as `nibabel`
