### ISSUE TITLE
Open the new Github "Disscussions" feature

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF#836]
Often, issues that I have, or that some other people have are not really Issues, but questions about how A or B is used. 
This tends to be annoying to have in the Issues tab (my opinion) for devs, and often its useful information for a future reader that has the same question, yet the issue will likely get closed. 

Github has now an optional tab called Discussions that opens a forum-like page to ask questions and leave suggestions for things that don't fully fit conceptually on the Issues tab. 

I suggest SIRF to open that, so this type of content gets removed from Issues.

**Comment by casperdcl** [comment]
opened https://github.com/SyneRBI/SIRF/discussions

can also convert current issue(s) to discussions if you can think of any...
