### ISSUE TITLE
Tag new patch version SIRF 2.2.1?

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#858]
Unittests with [CIL](https://github.com/vais-ral/CCPi-Framework) will fail because of a bug in SIRF's algebra methods in version 2.2.0.

This is fixed in current master and I would suggest to tag master as 2.2.1 so that builds will be green again.

**Comment by KrisThielemans** [comment]
So, I don't think this is a SIRF issue, but a SIRF-SuperBuild issue
