### ISSUE TITLE
PET AcquisitionData does not throw an error when dividing by zero

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#863]
All concrete classes of DataContainer except [`PETAcquisitionData`](https://github.com/SyneRBI/SIRF/blob/90cd6774807649182deda0e50182852596e08536/src/xSTIR/cSTIR/stir_data_containers.cpp#L216) throw an error when there is division by zero .

**Comment by KrisThielemans** [comment]
It's probably federated to STIR. I'm mildly surprised that that it would be different for images and `stir.ProjData` though.

Are you sure this is desired behaviour? Does `numpy` throw an error? (I doubt it)

**Comment by paskino** [comment]
numpy sets the result to `numpy.inf`.

**Comment by KrisThielemans** [comment]
Thought so, I think that's what nearly everyone will expect, and the title should therefore be reverted 😄 .

**Comment by paskino** [comment]
Well, I might open another issue suggesting that we should return `inf` in such case instead of raising an error.
