### ISSUE TITLE
zoom_image() does not change underlying data 

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF#879]
As title says, `zoom_image()` will change the geometry information but not the data.  This can be OK, but should we maybe have some way of informing the user? 

I forgot that that was the case, and I was trying to crop some too-large FOV images, and did:

        image=image.zoom_image(size=  (-1,image.get_geometrical_info().get_size()[1]-250,image.get_geometrical_info().get_size()[2]-150),scaling='preserve_values')

If I check `image.get_geometric_info().print_info()` before and after, I can see that it changed, but if I were to do `image.write("file.hv")` before and after, the output image would be identical in size (checked by opening with amide, for example). 

I think this is intended way of `zoom_image`, yet it kind of make sense to assume it will crop (in some way or another) the underlying data maybe?  Ideally really we'd make sure that `zoom_image` is only used with templates, for example, so its clear that if you have data, you should use `resample` instead of `zoom_image`. Or maybe removing `zoom_image` totally would make sense? 

Ideas?

**Comment by KrisThielemans** [comment]
that sounds very worrying, from a bug up to impossible. 

probably try with a different object as return value

```
image1 = image.zoom_image(...)
```

**Comment by AnderBiguri** [comment]
bug (on my side) indeed. 

Actually, Amide scales up all images to that one which is bigger of all loaded up, which I threw me off.
