### ISSUE TITLE
test failure in PET_TESTS_CPLUSPLUS_1

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#892]
see https://github.com/SyneRBI/SIRF/runs/2346802199?check_suite_focus=true#step:7:1865
```
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```
Also reproduced on my own VM.

**Comment by KrisThielemans** [comment]
https://github.com/SyneRBI/SIRF/actions/runs/750970490 seems to say that it's only for `DEVEL_BUILD=OFF`, which could indicate a problem with STIR (as it should still be testing `SIRF` `master`).

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans which branches of STIR and SIRF did you build on VM?

**Comment by KrisThielemans** [comment]
- STIR: https://github.com/UCL/STIR/commit/56f742977c837ccd51c2f3e5fc1fb8f78c2353cb (i.e. current `master`)
- SIRF: https://github.com/SyneRBI/SIRF/commit/a49138164901d7662a696166c1f56eda34a39989 (i.e. one before `master`, where the last commit only changed the github actions file)

**Comment by KrisThielemans** [comment]
this seems an `std::out-of-range` exception. I'm rebuilding with `RelWithDebInfo` such that hopefully I can see where it is

**Comment by KrisThielemans** [comment]
ok. This is a STIR problem. I'll create the STIR issue soon.
