### ISSUE TITLE
DEPRECATED on Windows

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#898]
SIRF build on Windows failed at this line:
```
using NiftyResample DEPRECATED = NiftyResampler<float>;
```
Removing DEPRECATED fixes it, so apparently on Windows DEPRECATED is used differently - does anyone know how?

**Comment by KrisThielemans** [comment]
https://docs.microsoft.com/en-us/cpp/cpp/deprecated-cpp?redirectedfrom=MSDN&view=msvc-160 doesn't mention anything about `using`, so possibly they don't support it.

I think best thing to do is to create another macro
```c++
// macro for examples like
//  using oldClass DEPRECATED_USING = newclass;
#if defined(_MSC_VER)
  #define DEPRECATED_USING
#else
  #define DEPRECATED_USING DEPRECATED
#endif
```

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans thanks!
