### ISSUE TITLE
rename DEPRECATED to SIRF_DEPRECATED

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#900]
As this macro can occur in .h files, it needs to have a SIRF specific name.

@gfardell maybe you can take the file from #895 but take recent changes from @evgueni-ovtchinnikov ?

**Comment by KrisThielemans** [comment]
amazingly we didn't use the macro anywhere 😄 

Please move the macro to a separate file as in  #895? (Prefer to do that now in 3.0).

**Comment by evgueni-ovtchinnikov** [comment]
done, I believe?

**Comment by KrisThielemans** [comment]
yup! 😄
