### ISSUE TITLE
fbp2d_reconstruction.py throws

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#907]
`fbp2d_reconstruction.py` throws error
```
raw data: C:\Users\wps46139\Documents\GitHub\build\INSTALL\share\SIRF-3.0\data\examples\PET\my_forward_projection.hs

ERROR: BackProjectorByBinUsingInterpolation cannot handle non-zero view-offset. Sorry

File: C:\Users\wps46139\Documents\GitHub\build\INSTALL\python\sirf\STIR.py
Line: 2355
check_status found the following message sent from the engine:
'BackProjectorByBinUsingInterpolation cannot handle non-zero view-offset. Sorry' exception caught at line 895 of C:\Users\wps46139\Documents\GitHub\build\sources\SIRF\src\xSTIR\cSTIR\cstir.cpp; the reconstruction engine output may provide more information
```

**Comment by evgueni-ovtchinnikov** [comment]
same in Matlab

**Comment by KrisThielemans** [comment]
ah yes. with STIR `master`. it's strange though as we have view_offset 0 in [my_forward_projection.hs](https://github.com/SyneRBI/SIRF_data/blob/1781fe1682f533acf40546cd77ffa605d23f8573/examples/PET/my_forward_projection.hs#L34). Yours as well?

**Comment by evgueni-ovtchinnikov** [comment]
yes:
```
View offset (degrees)                    := 0
```

**Comment by KrisThielemans** [comment]
ok. caused by the fact that `my_forward_projection.hs` has view-mashing=2, which in STIR `master` now correctly means that the mashed view is between the original view=0 and view=1, i.e. no longer at azimuthal angle=0.

We could
- change the header to compensate for the offset (slightly weird) (would have to set offset to -0.0081823*180/pi, which is presumably -180/192, with 192 the original number of views).
- replace the forward projection with a file without view mashing

The first option is the least amount of work, but would have to be a comment on why.

This is also the case for the `Utahscat*hs` file, not sure where we use that.

what do you think?

**Comment by evgueni-ovtchinnikov** [comment]
I am afraid I am a bit lost.

* 0.0081823*180/pi = 0.4688, 180/192 = 0.9375 (looks like should be 90/192 - but what all these figures mean?)
* I presume by the forward projection you meant the file `my_forward_projection.hs`? How can I generate a new one without view mashing?

**Comment by KrisThielemans** [comment]
> looks like should be 90/192. 

oops. correct!

> but what all these figures mean?

192 is the original number of views for that scanner (given by number of detectors/2). The actual number of views is 96 (hence view mashing 2). 0.0081823 was the number I got in the debugger.

> I presume by the forward projection you meant the file my_forward_projection.hs? 

yes. sorry

> How can I generate a new one without view mashing?

How did we generate the original one?

ugly trick: copy the file to a new one, edit the number of views (matrix size[?]), use that as a template.

I might favour the first solution though as it avoids creating a new binary file.

**Comment by evgueni-ovtchinnikov** [comment]
So, I should have in `my_forward_projection.hs`
```
View offset (degrees)                    := -0.4688112567
```
Just tried, same error.

> How did we generate the original one?

By projecting an image we constructed - if I cannot find it, can be restored by reconstruction. But you need to tell me how to get projected data without view mashing.

**Comment by KrisThielemans** [comment]
should work with `-0.46875` (I've tried this in STIR directly). it also writing a warning telling you what the offset is).

could be a numerical rounding error difference?

> tell me how to get projected data without view mashing.

I tried above: edit the header to generate a new template, and use that for forward projection (changing  to `matrix size[3]:=192`)

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov I guess this should be closed?

**Comment by evgueni-ovtchinnikov** [comment]
sure
