### ISSUE TITLE
Python: get_linear_acquisition_model does not contain acq_templ and img_templ

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#914]
For CIL we require the members `acq_templ` and `img_templ` to be part of the acquisition model. Once we use `get_linear_acquisition_model` these are not part of the new python object.

A quick fix is to add the members to the new `AcquisitionModel`.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov can you create an issue for a proper fix as discussed (just list some different options) and assign it to 3.1
