### ISSUE TITLE
move examples_data_path code to C++

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#919]
Our python code is no sophisticated, but we don't have this on the C++ level, for instance causing #918. Best to move that code to C++ such that it's usable everywhere.

**Comment by evgueni-ovtchinnikov** [comment]
much more difficult in C++ because of the path separator conundrum, see e.g. https://stackoverflow.com/questions/12971499/how-to-get-the-file-separator-symbol-in-standard-c-c-or
