### ISSUE TITLE
ListmodeToSinograms set_time_interval unit

### ISSUE THREAD

**Issue by szho42** [SyneRBI/SIRF#928]
What is the unit for ListmodeToSinograms.set_time_interval? 

For example, we want to recon only for the second 10 minutes, then,
the start_time (in sec) should be 600
and the end_tme (in sec) should be 1200,

However, it seems that almost no signals are included by giving the start_time and end_time to the function below.
`lm2sino = STIR.ListmodeToSinograms() 
lm2sino.set_time_interval(start_time, end_time)`

thanks

**Comment by szho42** [comment]
1. yeah, clearer information in the documentation is defintely valuabe to the general users. I just simply created a quick fix PR to the doc/UserGuide, #929 .

2. It is our own Listmode data from Siemens biograph. We will try on the NEMA data.

3. Yeah, I did try the function `get_time_at_which_num_prompts_exceeds_threshold` with a small threshold value and get a time shift of more than 6664 seconds, which is a bit confused to me, as the entire acquisition is about 90 mins (5400 seconds). The output from `list_lm_info` command:

`Modality: PT`
`Patient position: HFS`
`Scan start time: 0`
`Time frame start - end (duration), all in secs: 0 - 5460 (5460)`
`number of energy windows:=1`
`energy window lower level[1] := 430`
`energy window upper level[1] := 610`

With the command in STIR, `list_lm_events --time 1 --coincidence 0 --num-events-to-list 1 $listmode_file`, the output for the non-zero start is: `6664894` (which should be msec).

4. In SIRF, with the time shift, we did get some image out. However, the values in the reconstructed activity map are pretty low, compare to the same period reconstructed from the Siemens console. It might be related to the global factor mentioned in #922 ?
or  we should use the scatter estimate and random correction from the **entire** listmode data for the dynamic reconstruction. In our case, we estimate the scatter for each time slice (10mins) independently.

5. Just to confirm that with the `time shift (t_shift)`, to reconstruct the first 10 mins, it needs to set the time interval as `(t_shift, t_shift+600)`, and the 2nd 10 mins would be `(t_shift+600, t_shift+1200)`, and etc?

Thanks

**Comment by KrisThielemans** [comment]
thanks for the patch!

ok, your investigation confirms that the first time-tag is some arbitrary number in your case. You indeed have to offset all times with `t_shift` as you did.

The scale factor is indeed the same as in #922. You should have the same global scale for all time frames (aside from time-frame duration and decay of course)
