### ISSUE TITLE
not defined raw_input in STIR.py

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#932]
What purpose do these lines serve? `raw_input` is undefined.

https://github.com/SyneRBI/SIRF/blob/master/src/xSTIR/pSTIR/STIR.py#L46L49

**Comment by evgueni-ovtchinnikov** [comment]
just for compatibility with Python 2

**Comment by paskino** [comment]
I still don't get it, but if it's for python2 compatibility it can be removed.

**Comment by KrisThielemans** [comment]
after 3.0 please (as correctly put in the milestone!)
