### ISSUE TITLE
numpy requirements

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#935]
After merging PR #881, `numpy` must be at least 1.18.0, otherwise `Gadgetron.calc_cartesian_dcw` fails.

@KrisThielemans @ashgillman I understand `requirements.txt` is for `pip install` - should I add a new line `numpy >= 1.18.0` there?

**Comment by ashgillman** [comment]
Yes, that sounds correct. Note this won't be reflected in the VM yet: SyneRBI/SyneRBI_VM#189

I've just made a quick PR in the web interface as I'm out-of-office, hopefully CI is successful.
