### ISSUE TITLE
Error in Gadgetron.AcquisitionData algebra

### ISSUE THREAD

**Issue by ckolbPTB** [SyneRBI/SIRF#946]
If I have got two Gadgetron.AcquisitionData objects A1 and A2 and if

A) one of them is sorted (i.e. after calling A1.sort()) and one is unsorted OR
B) both of them are unsorted

then A1 + A2 leads to a crashed python kernel. 

If A1 and A2 are unsorted than any mathematical operators are very difficult, therefore it makes sense that this does not work but it would be great if there would be a helpful error message.

**Comment by KrisThielemans** [comment]
Do I understand it correctly that you want
```
if (!A.sorted() || B.sorted())
  throw a_nice_message;
```
I guess ideally we could also check that if they're both unsorted, that they do have the same order (not sure how to do that of course), but that might be too hard to put in right now.

**Comment by ckolbPTB** [comment]
yes, this is what I had in mind.

**Comment by KrisThielemans** [comment]
Actually, given the error message seen in https://github.com/SyneRBI/SIRF/issues/949#issue-920308890, do we check this already?

Also, potentially obsolete after #950?

**Comment by evgueni-ovtchinnikov** [comment]
@ckolbPTB does it work now? Please close the issue if it does.

**Comment by evgueni-ovtchinnikov** [comment]
I believe this error message is clear enough
```
if (!x.sorted() || !y.sorted())
	THROW("binary algebraic operations cannot be applied to unsorted data");
```

**Comment by ckolbPTB** [comment]
I only get the above error message when I try to multiply x and y but if I try to add them, then the kernel dies.

**Comment by evgueni-ovtchinnikov** [comment]
@ckolbPTB in which notebook does this happen?

**Comment by ckolbPTB** [comment]
It does not happen in a notebook anymore (because everything is automatically sorted). We can pospone it to a later release, but at some point it needs to be fixed, because for more advanced applications (e.g. motion correction) this would be a problem.

This should reproduce the problem:
```
import numpy

# Import MR functionality
import sirf.Gadgetron as mr
from sirf.Utilities import examples_data_path

mr_acq = mr.AcquisitionData(examples_data_path('MR') + '/simulated_MR_2D_cartesian_Grappa2.h5')



encode_step_1 = mr_acq.parameter_info('kspace_encode_step_1')
acq_idx_t1 = numpy.arange(0, len(encode_step_1))
acq_dat_t1 = mr_acq.new_acquisition_data(empty=True)

# Create raw data
for jnd in range(len(acq_idx_t1)):
    cacq = mr_acq.acquisition(acq_idx_t1[jnd])
    acq_dat_t1.append_acquisition(cacq)
    
# Comment in the following line to "fix" the error    
# acq_dat_t1.sort()    

print('acq_dat_t1.is_sorted: ', acq_dat_t1.is_sorted())
print('mr_acq.is_sorted: ', mr_acq.is_sorted())

mr_acq + acq_dat_t1
```

**Comment by evgueni-ovtchinnikov** [comment]
it turned out I simply forgot to place `axpby` inside try-catch brackets, fixed now

@ckolbPTB thanks a lot for spotting!
