### ISSUE TITLE
error in preprocessing_acquisition_data: empty result with ISMRMRD 1.4.2.1

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#948]
When my SIRF was compiled with ISMRMR 1.4.2, running `SIRF-Exercises/Introductory/acquisition_model_mr_pet_ct.ipynb` gave
```
mr_acq = mr.AcquisitionData(os.path.join(examples_data_path('MR'),'grappa2_1rep.h5'))
preprocessed_data = mr.preprocess_acquisition_data(mr_acq)

csm = mr.CoilSensitivityData()
csm.smoothness = 50
csm.calculate(preprocessed_data)
```
This gives me an error
```
error: ??? "'Please pass a non-empty container.
```
Trying to investigate:
```
> preprocessed_data.dimensions()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

> xxx=preprocessed_data.as_array()

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-e6795c6316a5> in <module>
----> 1 xxx=preprocessed_data.as_array()

~/devel/install/python/sirf/Gadgetron.py in as_array(self, acq)
    984         assert self.handle is not None
    985         if acq is None:
--> 986             ny, nc, ns = self.dimensions()
    987             z = numpy.ndarray((ny, nc, ns), dtype = numpy.complex64)
    988             acq = -1

ValueError: too many values to unpack (expected 3)
```
This was on my own VM with `SIRF/master`. Something that has changed in ISMRMRD presumably.

Let's postpone this to later of course.

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans 

> When my SIRF was compiled with ISMRMR 1.4.2, running SIRF-Exercises/Introductory/acquisition_model_mr_pet_ct.ipynb gave

1.4.2 (as above) or 1.4.2.1 (as in the issue title)?

I could not reproduce this error with 1.4.2.1, only the error due to the sorting issue (c/o Johannes)

**Comment by KrisThielemans** [comment]
hmmm. I think 1.4.2.1 but as I've deleted it, I don't know.

By the way, I did recompile gadgetron with that ismrmrd library.

anyway, let's leave this one for later once we do the transition.

**Comment by KrisThielemans** [comment]
@ckolbPTB to try

**Comment by ckolbPTB** [comment]
In the current VM version 3.2 this problem does not occur anymore.
