### ISSUE TITLE
error in `CoilSensitivityData.calculate` in SIRF-Exercises

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#949]
When my SIRF is compiled with ISMRMR 1.4.1, running `SIRF-Exercises/Introductory/acquisition_model_mr_pet_ct.ipynb` gave
```
mr_acq = mr.AcquisitionData(os.path.join(examples_data_path('MR'),'grappa2_1rep.h5'))
preprocessed_data = mr.preprocess_acquisition_data(mr_acq)

csm = mr.CoilSensitivityData()
csm.smoothness = 50
csm.calculate(preprocessed_data)
```
This gives me an error
```
error: ??? "'binary algebraic operations cannot be applied to unsorted data'
```
@ckolbPTB do you see this as well?

**Comment by ckolbPTB** [comment]
`preprocessed_data.sort()`

needs to be added after
`preprocessed_data = mr.preprocess_acquisition_data(mr_acq)`

**Comment by johannesmayer** [comment]
thanks.
I can modify the `C++` layer s.t. when it reads in the data it automatically sorts them by time, s.t. actually we never need to call the `sort()` method from `Python` again. It does not do anything anymore anyway.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov any reason why not to call `sort` automatically? I'm assuming that the overhead is low?

**Comment by johannesmayer** [comment]
Ah I just saw, that this is not the problem, (as @ckolbPTB  actually said), but the return value of the `preprocess_acquisition_data()` method is not sorted.

**Comment by KrisThielemans** [comment]
ok. The question is what is the best: let it sort it on time automatically, or let the user do it, or let the CSM stuff call `sort`. Up to the MR experts...

**Comment by johannesmayer** [comment]
Ok, so I proposed a solution in PR #950 (there are now more PR's than issues :dancing_men: ).

Feel free to tell me to do something else 👍
