### ISSUE TITLE
GadgetronImagesVector::reorient potentially wrong in special cases

### ISSUE THREAD

**Issue by johannesmayer** [SyneRBI/SIRF#960]
In the reorientation method for the MR image data, there is a loop over all images and the z-position is computed based on the  index of the loop.

The line 
https://github.com/SyneRBI/SIRF/blob/e214a7d4c59630e29f84adcabbc2888ee85b23fb/src/xGadgetron/cGadgetron/gadgetron_data_containers.cpp#L1546

in 
```

for (unsigned im=0; im<number(); ++im) {
        // Get image header
        ISMRMRD::ImageHeader &ih = image_wrap(im).head();

...
        for (unsigned i=0; i<3; ++i)
                ih.position[i] = offset[i]
                                    + direction[i][0] * (ih.field_of_view[0] / 2.0f)
                                    + direction[i][1] * (ih.field_of_view[1] / 2.0f)
                                    + direction[i][2] * float(im) * geom_info_out.get_spacing()[2];
```

However, the different images in a GadgetronImagesVector are not necessarily 2D slices, so if I acquire multiple repetitions for example in a cine, or multiple contrasts all these 2D slices should be in the same location but I think this will shift them around in space as well. 

A potential better implementation is to use the header flag for the slice number that could be used to shift them instead image number in the container.

**Comment by DANAJK** [comment]
Geometry can be difficult to get correct so there needs to be meaningful comments in the code.

A warning that `get_spacing()` seems to switch the order of dimensions (at least when used on SIRF data read from NIfTIs).

Assuming the code is meant to convert between the 'DICOM' offset (centre top left voxel) and the location of the image 'origin' after FT from k-space, the code should take account of whether the array length is odd or even - but this doesn't seem to do that.

**Comment by KrisThielemans** [comment]
yes indeed.

somewhat scary to fix this now for 3.1. Do we have sufficient test cases for this to feel confident enough to get this in?

> A warning that get_spacing() seems to switch the order of dimensions (at least when used on SIRF data read from NIfTIs).

might be, but this is unrelated to this issue, so let's keep that discussion elsewhere 😄 

> Assuming the code is meant to convert between the 'DICOM' offset (centre top left voxel) and the location of the image 'origin' after FT from k-space

SIRF's `geom_info_out.get_offset()` should indeed correspond to DICOM conventions. I don't know what `ISMRMRD::ImageHeader.position` is documented [here](https://ismrmrd.github.io/apidocs/1.5.0/struct_i_s_m_r_m_r_d_1_1_i_s_m_r_m_r_d___image_header.html#a48a93a4f92ebb3ffaf63e25e0cf858bb)

> the code should take account of whether the array length is odd or even

No idea why that should be. Can you explain? As it is unrelated to what @johannesmayer found, so maybe it should be a different issue as well? (I'm relatively sure @rijobro got that code from the Gadgetron code itself, but not 100% sure!)

**Comment by johannesmayer** [comment]
> somewhat scary to fix this now for 3.1. Do we have sufficient test cases for this to feel confident enough to get this in?

I didn't mean to squeeze this into 3.1 but I discovered it randomly today, so I opened the issue. 
I have not found anything failing because of this. 
I would not put this into 3.1 but check this more carefully first, i.e. and write a test that should fail because of this into the MR `C++` tests (that have been included more recently than the geometry).

There is one test for the MR reorientation already method 

https://github.com/SyneRBI/SIRF/blob/2088072a1cc705da3a69f8603174a6d6bdd57937/src/Synergistic/tests/test_cSynergistic.cpp#L236

but I think it might not cover all the cases (haven't read them carefully tbh)

**Comment by DANAJK** [comment]
If `get_spacing()` puts the slice spacing in the first dimension, then it is relevant here because this code uses `get_spacing()[2]`

**Comment by johannesmayer** [comment]
@DANAJK so I dug in there a bit and there is another thing that is unclear to me.

I can have multiple slices of a certain width whose centre has a certain distance, e.g. slices with an in-plane resolution 1.5mm of width 8mm that are 16mm apart. If interpolated to another coordinate system, at let's say 1.5mm 3D isotropic resolution these interpolated images should have a gap between them.

But our current approach is to fix the offset of the slice stack by the offset of the slice-sorted first image in our container, and then assume the slice spacing (in the example above 16mm) as the spacing[2].

The individual `ISMRMRD::ImageHeader` still contain this information, so when using the DICOM writer this should be fine since it writes individual 2D slices that read this info from the individual ISMRMRD images in the container, but if converted into nifti these gaps would actually not be taken into consideration?

**Comment by DANAJK** [comment]
My understanding is that NIfTI only gives information about the locations of the slice centres. DICOM in effect treats every slice as independent and so can cope with thicknesses that are not the same as the separation between slice centres.

**Comment by KrisThielemans** [comment]
I agree. Very few file formats contain information on slice-thickness vs slice-spacing. Hardly any support non-regular spacing. DICOM does this by being a horribly complicated file format to read ...

Ideally we should put a check in that the slices are regularly spaced (up to some tolerance of course)

**Comment by johannesmayer** [comment]
There is such a check already at 
 
https://github.com/SyneRBI/SIRF/blob/43f00027d0fc521d64123bbaa49f6ad6ebdd9c09/src/xGadgetron/cGadgetron/gadgetron_data_containers.cpp#L1636

However, once you guys can breathe again, we could have a discussion on how to marry the 3D Nifti images with our MR containers having multiple slices, and contrasts, and phases etc. all in one container. 
There could be a conceptual problem of trying to convert a whole bunch of images that all represent different things into one single 3D Nifti, which might not be possible.

**Comment by DANAJK** [comment]
In spinal imaging, slices may follow the curvature of the spine and aren't always parallel ....  DICOM of course can cope with this....

**Comment by johannesmayer** [comment]
I mean we do have all these individual slice orientation and offset information inside our `ISMRMRD::Image` headers that we hold after the reconstruction.

**Comment by KrisThielemans** [comment]
> In spinal imaging, slices may follow the curvature of the spine and aren't always parallel .... DICOM of course can cope with this....

amazing.

Of course our `GeometricalInfo` doesn't. The only way to support such a thing would be to have a `vector` of `GeometricalInfo`.
