### ISSUE TITLE
STIR.IterativeReconstructor.set_current_estimate stores a reference

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#965]
When doing
```python
recon.set_current_estimate(initial_image)
recon.process()
reconstructed_image=recon.get_current_estimate()
```
the reconstruction updates the `initial_image` variable. Also, re-running a reconstruction but assigning to a different variable would still update `reconstructed_image`. I don't think anyone will expect this.

Reason is https://github.com/SyneRBI/SIRF/blob/ce6c26c6de6ad6b11a57b4b12fc97170ef4ad26e/src/xSTIR/pSTIR/STIR.py#L2470-L2473 and https://github.com/SyneRBI/SIRF/blob/ce6c26c6de6ad6b11a57b4b12fc97170ef4ad26e/src/xSTIR/pSTIR/STIR.py#L2482-L2484
(and equivalent in MATLAB). I think these should be using `clone()`. Less efficient, but less surprising.

@ckolbPTB would you agree?

**Comment by KrisThielemans** [comment]
If we do this, `update` will become less efficient, as it's going to make 2 copies, while currently it doesn't.
https://github.com/SyneRBI/SIRF/blob/ce6c26c6de6ad6b11a57b4b12fc97170ef4ad26e/src/xSTIR/pSTIR/STIR.py#L2514-L2516

**Comment by ckolbPTB** [comment]
I agree that we should use clone()

**Comment by paskino** [comment]
Although you've been quicker than me replying, I don't know what's to be expected. It really depends who owns the memory in the first place. 

In VTK, filters normally own their output, so the behaviour is exactly the one you say it's not right.
