### ISSUE TITLE
Dicom writer fails for complex MR images

### ISSUE THREAD

**Issue by johannesmayer** [SyneRBI/SIRF#967]
When I run the `Python` code 
```

from sirf.Gadgetron import *
import sirf.Reg as sreg

rawdata = AcquisitionData(data_path + '/CV_2D_Stack_144.h5')
rawdata = preprocess_acquisition_data(rawdata)
rawdata.sort()

recon = FullySampledReconstructor()
recon.set_input(rawdata)
recon.process()
img_data = recon.get_output()

img_data = img_data.abs()
img_data.write("/home/sirfuser/tmp_mrgeometry.dcm")

nii_img = sreg.NiftiImageData(img_data)
nii_img.write('/media/sf_CCPPETMR/tmp_mrgeometry.nii')

```
then there are no DICOM images written but the Nifti ones will appear. 
Somewhere in the stream there is:
```
....
06-23 08:23:56.973 INFO [GadgetStreamController.cpp:356] Gadget Stream configured
06-23 08:23:56.976 ERROR [DicomFinishGadget.cpp:138] DicomFinishGadget::process, does not supprot ISMRMRD_CXFLOAT data type
06-23 08:23:56.976 ERROR [Gadget.h:258] Gadget (DicomFinish) process failed
06-23 08:23:56.976 DEBUG [Gadget.h:174] Gadget (DicomFinish) Close Called with flags = 0
06-23 08:23:56.976 ERROR [GadgetStreamController.cpp:135] Failed to put stuff on stream, too long wait, 0
06-23 08:23:56.977 DEBUG [GadgetStreamController.cpp:159] handle_close called
06-23 08:23:56.977 INFO [GadgetStreamController.cpp:164] Shutting down stream and closing up shop...
...
```
This is because Gadgetron checks the datatype of the `ISMRMRD::Image` header that it gets, and `.abs()` does not modify that.
I guess `.abs()` for MRI data would have to modify the data type on the C++ layer.

**Comment by johannesmayer** [comment]
So I checked again and the DICOM writer checks for the field `data_type` in the header.
I think this can't be changed easily during runtime without shifting pointers around.

**Comment by evgueni-ovtchinnikov** [comment]
@johannesmayer the problem is, the current temporary `abs()` return a complex image filled with absolute values of `self` data.

What we need is C++ `abs()` that would return `ImageData` that holds wraps of `ISMRMRD::Image<float>` objects, each with the header copied from the respective input `ISMRMRD::Image<complex_float_t>` and holding the `float` array of absolute values of the input complex values.

I  will be away on holiday the next two weeks - perhaps you might have a go at this yourself? Just do not merge on master before I return, please.

**Comment by johannesmayer** [comment]
Hi that sounds plausible. 
However, I am currently also on holiday for another week now.
I could give it a go in about a weeks time.

**Comment by evgueni-ovtchinnikov** [comment]
@DANAJK @johannesmayer @KrisThielemans reopening following the discussion in https://github.com/SyneRBI/SIRF/commit/05fbce2c5b1fa6764fa4fbff568c0603de22ac45

need to do a proper `DataContainer.abs()` and add `DataContainer.real()` to let the user choose how to convert a complex image into a real one before writing to file in `dicom` format (error message to be issued if writing a complex image is attempted)
