### ISSUE TITLE
OSMAPOSLReconstruction save images every iteration

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#968]
I tried
```
recon.set_output_filename_prefix("OSEM")
recon.set_save_interval(1)
```
but don't get any output

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans you forgot to enable output

added enabling output to `set_save_interval()` as the user is even more likely to forget it than you

**Comment by KrisThielemans** [comment]
great. thanks!
