### ISSUE TITLE
AcquisitionSensitivityModel.forward does not seem to do anything

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#976]
I tried to create a sinogram of detection efficiencies for the NEMA data
```python
asm_norm.set_up(acq_data)
det_efficiencies=acq_data.get_uniform_copy(1)
asm_norm.forward(det_efficiencies)
```
just gives 1s. `unnormalise` does work.

**Comment by evgueni-ovtchinnikov** [comment]
>>> import sirf
>>> help(sirf.STIR.AcquisitionSensitivityModel.forward)
Help on function forward in module sirf.STIR:

forward(self, ad)
    Alias of unnormalise except the argument remains unchanged

    and a new AcquisitionData equal to the argument multiplied
    by S is returned.

>>>

**Comment by KrisThielemans** [comment]
ok. sorry. I guess I need
```
det_efficiencies=asm_norm.forward(acq_data.get_uniform_copy(1))
```
makes sense!
