### ISSUE TITLE
STIR.acq_model background-term is ignored by the reconstruction

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#983]
We currently only use the additive term, but ignore the background term
https://github.com/SyneRBI/SIRF/blob/699b12ceb2e8d74d804c2a3620875d8a969a7843/src/xSTIR/cSTIR/include/sirf/STIR/stir_x.h#L913-L922
resulting in all reconstructions that used `set_background_term` to be incorrect.

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans 
`stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData` does not seem to handle the background term at all, only additive, so it looks like a STIR issue to me.
`sirf::PETAcquisitionModel` does have  the background term and its method `forward` does add it.

**Comment by KrisThielemans** [comment]
STIR only has an additive term. It's up to SIRF to convert its input to STIR compatible input.

@evgueni-ovtchinnikov did you address this already?

**Comment by KrisThielemans** [comment]
yes, that is ok. I guess that `get_constant_term` computes `a/n+b`, so it's not quite what we want.
