### ISSUE TITLE
implement a version of np.nan_to_num for ImageData

### ISSUE THREAD

**Issue by AnderBiguri** [SyneRBI/SIRF#984]
If we want to take an image and remove NaNs and Infs, the current way is
```
        img.ImageData()

        imga=img.as_array()   #50 % of the time
        imga[np.isnan(imga)]=0.0
        imga[np.isposinf(imga)]=0.0
        # np.nan_to_num(imga,copy=False,nan=0,posinf=0) # alternative
        img.fill(imga)              # 50% of the time
```

For 50 iterations of the above, I measured with `time.time()` (yes, bad measurement technique) and the results are that it takes in total 13 seconds. 6.4 are `as_array()` and 6.3 are `fill()`. This is very non ideal to do anything in SIRF that its not something that STIR can already do. 

I assume the answer to "make these faster" is "we can't because the design of SIRF". An alternative to that is to make these functions that delete nans and infs to work directly on the data pointer, then expose them as a method of `ImageData`. That should be quite fast.

**Comment by KrisThielemans** [comment]
Hard. There is no `data pointer` to STIR arrays.

it's obviously surprising that `as_array` takes 5s. No clue why that would be.

**Comment by AnderBiguri** [comment]
5/50 seconds, this is the result of 50 runs.

**Comment by AnderBiguri** [comment]
> Hard. There is no `data pointer` to STIR arrays.

I was thinking if this could be done in STIR itself, so no need to access data pointer, just make a `ImageData.nan_to_num()` function. Again, not sure if this is easy.

**Comment by KrisThielemans** [comment]
"easy" enough, (add it to STIR, wrap it in SIRF Python/MATLAB, i.e. edit about 6 files) but you'd need it for `NiftiImageData` and `ISMRMRDImageData` as well then logically. @paskino does CIL have/need anything like this?

TBH, 0.2s overhead is the sort of thing that I generally don't worry about. Would make more sense to invest the time into converting `stir::Array` to be return a contiguous pointer (which it is all set-up to do, but...)

**Comment by AnderBiguri** [comment]
I agree with that last thing, if it's possible that would be ideal.

**Comment by AnderBiguri** [comment]
But just to clarify, 0.2s in a trivial task is a serious issue, and if you want people to use SIRF to develop algorithms, this (and possibly others) are critical failure points that will turn people away. 

Example: I wrote a nested direct reconstruction algorithm. All good. However, I need to do what I posted above, remove singularities from a division. Currently on my PC, its 0.25 time to `as_array()` and `fill()` together per image. 

A nested direct recon can have, say 15 frames. 20 nested iteration (per subset) . 17 subsets. 2 iterations. 

`0.25*15*20*17*2=2550s -> 42 minutes`

This is not even a large amount of iterations, and I need to wait almost 1h in something this trivial. I'd argue that this is something that we should generally very much worry about.

**Comment by evgueni-ovtchinnikov** [comment]
I for one am very uneasy about this "papering over the crack" approach - the appearance of nan or inf signals that something is not quite right, and we just try to ignore it?

**Comment by AnderBiguri** [comment]
@evgueni-ovtchinnikov they appear naturally on the EM update.  Some areas of the image and the sensitivity image can be, and should be, zero. As EM takes the division of the measurement against the current update, getting zero divide by zero is OK and expected. STIR handles this internally, but if we write our own stuff in SIRF using the `forward` and `adjoint`, then we need to hand-correct for these.

**Comment by evgueni-ovtchinnikov** [comment]
@AnderBiguri then the check should be where the division is, to be sure about what produced `inf`

**Comment by AnderBiguri** [comment]
@evgueni-ovtchinnikov right, maybe I was not clear, sorry. I am writing an algorithm that its not in STIR, so my code looks like this:


        img= imagedata1/ imagedata2
        
        # this is the code from above.  
        imga=img.as_array()   #50 % of the time
        imga[np.isnan(imga)]=0.0
        imga[np.isposinf(imga)]=0.0
        # np.nan_to_num(imga,copy=False,nan=0,posinf=0) # alternative
        img.fill(imga)              # 50% of the time

So, this is where the division is at. 
If you meant instead that the operator `/` should be doing this, that is reasonable, but I don't necessarily agree, because the reason I am doing this is because the STIR operator is doing the `nan_to_num`, but its taking real image values as below the threshold to make zero, and destroying my reconstruction. Unless you have a constraint on what `ImageData` can contain in physical units (in my case, parametric macroparameters), there is no solution that fits all cases. 

In any case, I think the ideal solution would be to make `as_array()` and `fill()` fast, as the only reason they are not is arguably very obsolete `stir::vector` code. If it were a `std::vector`, then the array could be shuffled in and out from python by reference, and this would solve many more future problems (i.e. what if I want to mask the ImageData? or just do anything to the data many times in each iteration).

**Comment by evgueni-ovtchinnikov** [comment]
@AnderBiguri 

>  its taking real image values as "small values" below the threshold to make zero

Sorry, you have lost me here - can you try to reword this statement? I feel though it might be related to

> there can be a `small_num/0 ->inf` and sometimes a `0/0->nan`

is it not?

>  Some areas of the image and the sensitivity image can be, and should be, zero

So, I understand there are some theoretical reasons for the numerator to be zero (or nearly zero - because of the computation error) where the denominator is exactly zero. If that is the case, I would simply set the ratio to zero whenever the denominator is zero - would that do?

**Comment by AnderBiguri** [comment]
@evgueni-ovtchinnikov 

Sorry, better explained: for the division "by zero", in STIR, "zero" is defined as "a number smaller than `float small_num;`". Otherwise, you get near-infinites, or infinite, depending on the number on the denominator. STIR sets whatever smaller than `0.0001` or something like that to zero, and if it is, then does exactly what you propose: return zero in that case.

However, while for a PET image for concentration values `0.0001` is equal to zero, a parametric image is not, this is a real world value for the stuff we are trying to reconstruct. STIR treated my values to be reconstructed as zero, thus destroying my recon (filling large chunks of it with zeroes). In general, unless the range of values in `ImageData` is constrained, this approach won't work. 

Perhaps setting the denominator values that are exactly zero would work, but I think there is a reason why Kris has it set to `small_num`, and definitely I can see this in TIGRE: near zeros create very large images (say, the denominator is `1e-16`) and this gets propagated to the image quite badly in the interative process (particularly due to forward/backprojectors), so stuff can go bad easy. 

I guess a solution could be having a `small_num` in SIRF too, but one that could be passed as an optional input to a division function. 

I still think this is a patch to a problem that would need to be tackled at some point (`stir::vector`), but would work for this particular issue.

**Comment by evgueni-ovtchinnikov** [comment]
@AnderBiguri I appreciate there are plenty of issues related to nearly-zeros, but let us concentrate on the one you raised. You wanted to quickly replace nans and infs with zeros, but those nans and infs are the results of division by exact zero, therefore instead of performing division by exact zero in C++ code we can simply set the ratio to zero right away, as I suggested, can we not?

**Comment by AnderBiguri** [comment]
@evgueni-ovtchinnikov You are right, but I mention it because numerically, `inf` can also happen (and may be happening here, have not checked all) with `1e40/1e-7`. So the solution you propose _may_ work, but also may not... My mention of TIGRE was because in TIGRE (where sensitivity is the only divisor really) it does not work, by experience. 

If the implementation is easy we can always just try, but I am not 100% convinced this will entirely resolve the issue.

**Comment by evgueni-ovtchinnikov** [comment]
@AnderBiguri the implementation I suggested is just a few minutes work: first checking if the denominator is zero and if it is, setting the ratio to zero, otherwise dividing, and if the ratio is inf, setting it to zero. I just want to make sure you would be happy enough with this solution to your issue before I implement it.

Improving `stir::DiscretisedDensity` is a much much more laborious issue...

**Comment by AnderBiguri** [comment]
@evgueni-ovtchinnikov it may fix the issue, I will be trying to run some tests later today or tomorrow to see if I can see this happening with small numbers too, but I think making divisions by exact zeros return zero is possibly the solution. 

However, if you need to do the `as_array()` and `fill` for that (or a similar think under the hood) such that it takes the same computational cost, then don't worry for now, as currently its the time that bothers me, not the fact that I need to manually correct it.

**Comment by KrisThielemans** [comment]
hi guys. I did not read all this, but let's **not** modify SIRF division with specific cases to handle nan/0/0 etc. We could add a specific implementation of the division as a separate function if that'd help.

As I explained in the training school during one of the sessions, it depends where you are in the reconstruction process how you should handle 0/0 (for Poisson case: sinogram division: set it to 0, for MLEM sensitivity division: set it to 1). So I guess you could make a function that takes an optional argument

```
careful_division(x, y, float zero_by_zero = 0.F/0.F)
```
I wrote the default like this, as there is no standard way to construct a NaN.

Not sure if this is what you're looking for

**Comment by AnderBiguri** [comment]
@KrisThielemans yes that could work indeed. Ultimately what bothers me is the _speed_ checking for NaN and Infs, but if we can avoid them with this, great.

**Comment by evgueni-ovtchinnikov** [comment]
@AnderBiguri no, no `as_array()` or `fill()` will be involved, just do `img= imagedata1/ imagedata2` and you have it

pushing now, please check...

**Comment by evgueni-ovtchinnikov** [comment]
@AnderBiguri please try the new division with time measurements (Kris wants me to revert back to unsafe one)
