### ISSUE TITLE
create a CITATION.cff file

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#992]
See https://github.com/citation-file-format/citation-file-format/blob/main/README.md

@paskino, @evgueni-ovtchinnikov this seems worth discussing in CoSeC as well

**Comment by KrisThielemans** [comment]
done in https://github.com/SyneRBI/SIRF/commit/3b87784e43c7b79276949f6263f8847a7f921916

**Comment by DANAJK** [comment]
Should be OK, but not tested fully as SIRF has not yet had a new release (that will trigger Zenodo integration).

**Comment by KrisThielemans** [comment]
yup. once that's done, hopefully we can close #1086
