### ISSUE TITLE
sirf/STIR set_up(),process() shouldn't return stir::Succeeded in C++

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#994]
SIRF follows the general strategy of throwing an exception when there's a run-time error, as opposed to hoping that the user will check a return value. This is a bit different from STIR (although we're slowly converting to that strategy as well).

In Python, we already just call set_up() (hopefully checking STIR's return value), but in C++ we still return stir::Succeeded in some places. We should replace those with `void` return, and an check on the STIR return value.

**Comment by KrisThielemans** [comment]
Same for `process()`

**Comment by evgueni-ovtchinnikov** [comment]
In
```
float ListmodeToSinograms::get_time_at_which_num_prompts_exceeds_threshold(const unsigned long threshold) const
```
I see this:
```
        // no more events in file for some reason
        if (lm_data_ptr->get_next_record(record) == Succeeded::no)
            return -1.f;
```
I do not quite understand this, but I feel throwing exception here would not be the right move - or would it?

**Comment by evgueni-ovtchinnikov** [comment]
What I actually wanted to say in my previous comment is: we might not be able to totally get rid of `stir::Succeeded`.

**Comment by KrisThielemans** [comment]
> What I actually wanted to say in my previous comment is: we might not be able to totally get rid of `stir::Succeeded`.

we certainly don't need to get rid of `stir::Succeeded` in the internal implementation. However, we don't want to expose it the SIRF user. (ok, I know that some classes are derived from `stir` classes, therefore they will have it, but I think at some point we could do a `private` derivation and only exposes the ones we feel should be exposed, or find some other way to present a "clean" SIRF interface for most people).

**Comment by KrisThielemans** [comment]
> I see this:
> 
> ```
>         // no more events in file for some reason
>         if (lm_data_ptr->get_next_record(record) == Succeeded::no)
>             return -1.f;
> ```
> 
> I do not quite understand this, but I feel throwing exception here would not be the right move - or would it?

The code at [https://github.com/SyneRBI/SIRF/blob/34f49e217d3a82c098d1f4deab1028142adc16ca/src/xSTIR/cSTIR/stir_x.cpp#L72-L73] seems incorrect to me. It should return `current_time`, not `-1`. What do you think?

In any case, this doesn't have anything to do with this issue.
